Repository kubevirt/project-infra, pull requests merged in 2019-07, with the labels that each got.

#128 Added automerges over community repo
  github/ci/prow/files/config.yaml
Labels: approved, lgtm, size/XS

#129 Add automatic retest capability for kubevirt/kubevirt
  github/ci/prow/files/jobs/project-infra/project-infra-periodics.yaml
  github/ci/prow/files/plugins.yaml
Labels: approved, lgtm, size/M

#130 Use dedicated disks for docker mirror and bazel cache
  github/ci/prow/templates/greenhouse-deployment.yaml
  github/ci/prow/templates/mirror.yaml
Labels: approved, lgtm, size/XS

#131 Give caches their own serviceaccount
  github/ci/prow/templates/accounts.yaml
  github/ci/prow/templates/greenhouse-deployment.yaml
  github/ci/prow/templates/mirror.yaml
Labels: approved, lgtm, size/XS

#132 Bump from v20190523-832050b39 to v20190703-132f32f32
  github/ci/prow/files/config.yaml
  github/ci/prow/files/jobs/project-infra/project-infra-presubmits.yaml
  github/ci/prow/templates/deck-deployment.yaml
  github/ci/prow/templates/ghproxy.yaml
  github/ci/prow/templates/hook.yaml
  github/ci/prow/templates/horologium-deployment.yaml
  github/ci/prow/templates/needs-rebase_deployment.yaml
  github/ci/prow/templates/plank-deployment.yaml
  github/ci/prow/templates/sinker-deployment.yaml
  github/ci/prow/templates/statusreconciler-deployment.yaml
  github/ci/prow/templates/tide-deployment.yaml
Labels: size/S

#133 Convert lense config to new config format
  github/ci/prow/files/config.yaml
Labels: approved, lgtm, size/S

#134 Tide for kubevirt/kubevirt
  github/ci/prow/files/config.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, lgtm, size/M

#135 Allow jobs which run always to run more often
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS

#136 Add commenter bot token
  github/ci/prow/files/jobs/project-infra/project-infra-periodics.yaml
  github/ci/prow/tasks/main.yml
Labels: approved, lgtm, size/S

#139 Use more memory to reduce the amount of parallel jobs
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: size/S

#137 Actually check if limit really is exceeded
  limiter/limiter.go
Labels: approved, lgtm, size/S

#140 Increase timeout on KubeVirt jobs
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: size/S

#141 Make all jobs mandatory again
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, lgtm, size/S

#144 Added kubevirtci base and centos7 presubmit jobs
  github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, lgtm, size/L

#145 Add the okd 4.1.2 provider to prow
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, lgtm, size/S

#138 Add job for sriov ci
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, lgtm, size/M

#147 Fix the pod antiaffinity spec under affinity
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, lgtm, size/S

#148 Jobs for k8s 1.15.1
  github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, lgtm, size/M

#149 Deploy gcsweb viewer
  github/ci/prow/files/config.yaml
  github/ci/prow/tasks/main.yml
  github/ci/prow/templates/gcsweb-deployment.yaml
  github/ci/prow/templates/gcsweb-service.yaml
  github/ci/prow/templates/routes.yaml
Labels: approved, lgtm, size/M
