Repository kubevirt/project-infra, pull requests merged in 2019-03, with the labels that each got.

#80 Remove trailing whitespaces in prow playbook
  github/ci/prow/tasks/main.yml
Labels: approved, lgtm, size/XS

#81 Add presubmit jobs for the provider k8s-1.13.3
  github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, lgtm, size/M

#82 Add memory limits to Prow deployment
  github/ci/prow/tasks/main.yml
  github/ci/prow/templates/cherrypicker_deployment.yaml
  github/ci/prow/templates/deck-deployment.yaml
  github/ci/prow/templates/ghproxy.yaml
  github/ci/prow/templates/greenhouse-deployment.yaml
  github/ci/prow/templates/hook.yaml
  github/ci/prow/templates/horologium-deployment.yaml
  github/ci/prow/templates/label-sync.yaml
  github/ci/prow/templates/memory-defaults.yaml
  github/ci/prow/templates/needs-rebase_deployment.yaml
  github/ci/prow/templates/plank-deployment.yaml
  github/ci/prow/templates/pushgateway.yaml
  github/ci/prow/templates/sinker-deployment.yaml
  github/ci/prow/templates/statusreconciler-deployment.yaml
  github/ci/prow/templates/tide-deployment.yaml
Labels: approved, lgtm, size/M

#83 Add push job for k8s-1.13.3-multus
  github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, lgtm, size/S

#84 Separate namespace
  github/ci/prow/files/config.yaml
  github/ci/prow/tasks/main.yml
  github/ci/prow/templates/accounts.yaml
  github/ci/prow/templates/deck-rbac.yaml
  github/ci/prow/templates/hook-rbac.yaml
  github/ci/prow/templates/horologium-rbac.yaml
  github/ci/prow/templates/memory-job-defaults.yaml
  github/ci/prow/templates/plank-rbac.yaml
  github/ci/prow/templates/sinker-rbac.yaml
  github/ci/prow/templates/statusreconciler-rbac.yaml
  github/ci/prow/templates/tide-rbac.yaml
Labels: approved, lgtm, size/L

#85 Separate namespace final fixes
  github/ci/prow/tasks/main.yml
  github/ci/prow/templates/deck-rbac.yaml
  github/ci/prow/templates/hook-rbac.yaml
  github/ci/prow/templates/horologium-rbac.yaml
  github/ci/prow/templates/plank-rbac.yaml
  github/ci/prow/templates/sinker-rbac.yaml
  github/ci/prow/templates/statusreconciler-rbac.yaml
  github/ci/prow/templates/tide-rbac.yaml
Labels: approved, lgtm, size/M
