Repository kubevirt/project-infra, pull requests merged in 2019-09, with the labels that each got.

#179 disable k8s 1.11, enable k8s 1.15 with ceph
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS

#169 Remove pci-utils, install gettext in for sriov lane (switch to sriov-operator)
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, lgtm, size/XS

#181 Minor improvements for report
  github/ci/prow/files/jobs/kubevirt/kubevirt-periodics.yaml
  robots/flakefinder/main.go
  robots/flakefinder/report.go
  robots/flakefinder/report_test.go
Labels: approved, lgtm, size/M

#182 Added build-change label
  github/ci/prow/files/labels.yaml
Labels: approved, lgtm, size/XS

#183 Fixed label config of area/virtctl
  github/ci/prow/files/labels.yaml
Labels: approved, lgtm, size/XS

#180 Add 1.14.6 to kubevirtci-presubmits
  github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, lgtm, size/M

#184 Added k8s 1.15 with ceph for release-0.20 branch, disabled k8s 1.11
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits-0.20.yaml
Labels: approved, lgtm, size/M

#185 Create new test lane for k8s-1.14.6
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, lgtm, size/M

#187 CI lane cleanup after k8s-1.14 addition
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, lgtm, size/M

#188 Sort report data descending by severity
  github/ci/prow/files/jobs/kubevirt/kubevirt-periodics.yaml
  robots/flakefinder/index.go
  robots/flakefinder/main.go
  robots/flakefinder/report.go
  robots/flakefinder/report_test.go
Labels: approved, lgtm, size/L

#190 Enable dco plugin for kubevirt and kubevirtci
  github/ci/prow/files/plugins.yaml
Labels: approved, lgtm, size/XS

#195 create okd-4.2 provisioning jobs
  github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, lgtm, size/M

#193 Add build push and test for k8s multus 1.15.1
  github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, lgtm, size/M

#196 Improve flakefinder test sorting
  github/ci/prow/files/jobs/kubevirt/kubevirt-periodics.yaml
  robots/flakefinder/BUILD.bazel
  robots/flakefinder/index_test.go
  robots/flakefinder/report.go
  robots/flakefinder/report_test.go
  vendor/github.com/onsi/ginkgo/extensions/table/BUILD.bazel
  vendor/github.com/onsi/ginkgo/extensions/table/table.go
  vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#192 Add dco-signoff:no to missingLabels for tide
  github/ci/prow/files/config.yaml
  github/ci/prow/files/plugins.yaml
Labels: approved, lgtm, size/XS

#198 Filter test results before start of report
  github/ci/prow/files/jobs/kubevirt/kubevirt-periodics.yaml
  robots/flakefinder/downloader.go
  robots/flakefinder/main.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#199 Add test job for flakefinder
  github/ci/prow/files/jobs/project-infra/project-infra-presubmits.yaml
  limiter/limiter_test.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#204 Disable go cache
  github/ci/prow/files/jobs/project-infra/project-infra-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#207 Enable DCO plugin for virtblocks org
  github/ci/prow/files/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#206 Convert boolean logging flag into command line flag
  robots/flakefinder/flakefinder_suite_test.go
  robots/flakefinder/index_test.go
  robots/flakefinder/report_test.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#208 Use image with the bazel 0.28.1 for kubevirtci jobs
  github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#205 Add e2e job for virtblocks
  github/ci/prow/files/jobs/virtblocks/virtblocks/virtblocks-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#202 Filter PRs on base branch, add output path config
  github/ci/prow/files/jobs/kubevirt/kubevirt-periodics.yaml
  robots/flakefinder/BUILD.bazel
  robots/flakefinder/main.go
  robots/flakefinder/main_test.go
Labels: approved, dco-signoff: yes, lgtm, size/M
