Repository kubevirt/project-infra, pull requests merged in 2019-11, with the labels that each got.

#240 Disable automatic running of OKD and remove coveralls branch protection.
  github/ci/prow/files/config.yaml
  github/ci/prow/files/jobs/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#242 Add cluster-provision and push for k8s-1.16.2
  github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#243 Remove travis protection from hostpath provisioner and operator.
  github/ci/prow/files/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#245 Remove okd-4.2
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits-0.22.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#246 Make k8s 1.15 and OS 3.11 lanes required in CDI
  github/ci/prow/files/jobs/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#251 Prepare PROW for hostpath provisioner
  github/ci/prow/files/config.yaml
  github/ci/prow/files/jobs/hostpath-provisioner/OWNERS
  github/ci/prow/files/jobs/hostpath-provisioner/hostpath-provisioner-presubmits.yaml
  github/ci/prow/files/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#252 Fix call to the cluster up script for hostpath provisioner.
  github/ci/prow/files/jobs/hostpath-provisioner/hostpath-provisioner-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#247 Use source PR IDs instead of report PRs
  github/ci/prow/files/jobs/kubevirt/kubevirt-periodics.yaml
  robots/flakefinder/main.go
  robots/flakefinder/report.go
  robots/flakefinder/report_test.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#249 Add pull-kubevirt-e2e-k8s-1.16.2 test lane.
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#250 Add Katacoda-Scenarios for tide
  github/ci/prow/files/config.yaml
  github/ci/prow/files/labels.yaml
  github/ci/prow/files/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#253 Fix source PR numbers
  github/ci/prow/files/jobs/kubevirt/kubevirt-periodics.yaml
  robots/flakefinder/main.go
  robots/flakefinder/report.go
  robots/flakefinder/report_test.go
Labels: approved, bug, dco-signoff: yes, lgtm, size/M

#255 Always run k8s-1.16 test lane
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#256 add kubevirt/common-templates under prow
  github/ci/prow/files/jobs/common-templates/OWNERS
  github/ci/prow/files/jobs/common-templates/common-templates-presubmits.yaml
  github/ci/prow/files/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#254 Add kubevirt/demo under prow control
  github/ci/prow/files/config.yaml
  github/ci/prow/files/labels.yaml
  github/ci/prow/files/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M
