Repository kubevirt/project-infra, pull requests merged in 2019-05, with the labels that each got.

#100 Add OKD 4.1.0-rc.0 provision and push jobs
  github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, lgtm, size/XS

#99 Add okd-4.1.0-rc.0 KubeVirt job
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, lgtm, size/S

#102 Use newer boostrap image with newer docker
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, lgtm, size/M

#101 Add limiter for gce buckets
  .gcloudignore
  .gitignore
  BUILD.bazel
  WORKSPACE
  limiter/BUILD.bazel
  limiter/Makefile
  limiter/README.md
  limiter/go.mod
  limiter/go.sum
  limiter/limiter.go
  limiter/limiter_test.go
Labels: approved, lgtm, size/L

#92 Always run kubevirt e2e with prow instead of stdci
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, lgtm, size/M

#104 Update prow to v20190523 832050b39
  github/ci/prow/files/config.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow/files/jobs/project-infra/project-infra-presubmits.yaml
  github/ci/prow/templates/deck-deployment.yaml
  github/ci/prow/templates/ghproxy.yaml
  github/ci/prow/templates/hook.yaml
  github/ci/prow/templates/horologium-deployment.yaml
  github/ci/prow/templates/needs-rebase_deployment.yaml
  github/ci/prow/templates/plank-deployment.yaml
  github/ci/prow/templates/sinker-deployment.yaml
  github/ci/prow/templates/statusreconciler-deployment.yaml
  github/ci/prow/templates/tide-deployment.yaml
Labels: approved, lgtm, size/M

#94 Document how to create jobs from local configurations
  github/ci/README.md
Labels: approved, lgtm, size/S

#106 Add k8s-1.13.3 kubevirt job
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, lgtm, size/S

#107 kubevirt-presubmits: create shared-iso mount type if needed
  github/ci/prow/files/config.yaml
Labels: approved, lgtm, size/XS
