Repository kubevirt/project-infra, pull requests merged in 2019-08, with the labels that each got.

#143 Feat: Added Kubevirt-Tutorial related jobs for lab testing
  github/ci/prow/files/jobs/kubevirt-tutorial/kubevirt-tutorial-periodics.yaml
  github/ci/prow/files/jobs/kubevirt-tutorial/kubevirt-tutorial-presubmits.yaml
  github/ci/prow/files/jobs/kubevirt.github.io/kubevirt-github-io-periodics.yaml
Labels: approved, lgtm, size/M

#150 Feat: Added OWNERS per job folder in order to manage just those jobs
  github/ci/prow/files/jobs/kubevirt-tutorial/OWNERS
  github/ci/prow/files/jobs/kubevirt.github.io/OWNERS
Labels: approved, lgtm, size/S

#152 Release 0.17 jobs
  github/ci/README.md
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits-0.17.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, lgtm, size/L

#153 Enable CI integration for Virtblocks
  github/ci/prow/files/jobs/virtblocks/virtblocks/OWNERS
  github/ci/prow/files/jobs/virtblocks/virtblocks/virtblocks-periodics.yaml
  github/ci/prow/files/plugins.yaml
Labels: approved, lgtm, size/M

#154 Use same container image for all Virt Blocks jobs
  github/ci/prow/files/jobs/virtblocks/virtblocks/virtblocks-periodics.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#155 Add machine-remediation-operator to supported by prow repos
  github/ci/prow/files/config.yaml
  github/ci/prow/files/plugins.yaml
Labels: size/S

#156 virtblocks: Set VIRTBLOCKS_LANGUAGE=golang
  github/ci/prow/files/jobs/virtblocks/virtblocks/virtblocks-periodics.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#157 Added k8s 1.15 presubmit job with Ceph enabled for Kubevirt
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: size/M

#158 Added Kubevirt presubmit jobs for release-0.20 branch
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits-0.20.yaml
Labels: approved, size/L

#160 Create presubmit job for flakefinder for testing
  github/ci/prow/files/jobs/project-infra/project-infra-presubmits.yaml
Labels: size/S

#161 Remove command from job spec
  github/ci/prow/files/jobs/project-infra/project-infra-presubmits.yaml
Labels: size/XS

#162 Correct yaml formatting
  github/ci/prow/files/jobs/project-infra/project-infra-presubmits.yaml
Labels: approved, lgtm, size/S

#163 Flakefinder job
  github/ci/prow/files/jobs/project-infra/project-infra-presubmits.yaml
Labels: approved, lgtm, size/XS

#164 Add gcs credentials to arg list
  github/ci/prow/files/jobs/project-infra/project-infra-presubmits.yaml
Labels: approved, lgtm, size/XS

#166 added Daniel to owners
  OWNERS
Labels: approved, size/XS

#167 remove patch version from okd 4.1 jobs
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/M

#170 timeout, k8s 1.15
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: size/S

#171 reverted k8s-1.11.0 / k8s-1.15.1-ceph change
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS

#172 Virt Blocks update
  github/ci/prow/files/jobs/virtblocks/virtblocks/virtblocks-periodics.yaml
Labels: approved, lgtm, ok-to-test, size/M

#173 Virt Blocks update
  github/ci/prow/files/jobs/virtblocks/virtblocks/virtblocks-periodics.yaml
Labels: approved, lgtm, ok-to-test, size/S

#176 Fixed formatting of virtblocks OWNERS file
  github/ci/prow/files/jobs/virtblocks/virtblocks/OWNERS
Labels: size/XS

#175 Virt Blocks: Use newer container image
  github/ci/prow/files/jobs/virtblocks/virtblocks/virtblocks-periodics.yaml
Labels: approved, lgtm, ok-to-test, size/S

#178 Fix README issues
  robots/flakefinder/README.md
Labels: approved, lgtm, size/M
