Repository kubevirt/project-infra, pull requests merged in 2019-10, with the labels that each got.

#211 Add okd-4.2
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#209 Add automatic branch protection via prow job for kubevirt org and possibly virtblocks org
  github/ci/prow/files/config.yaml
  github/ci/prow/files/jobs/project-infra/project-infra-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#213 Revert "Add automatic branch protection via prow job for kubevirt org and possibly virtblocks org "
  github/ci/prow/files/config.yaml
  github/ci/prow/files/jobs/project-infra/project-infra-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#214 Add branch protection to kubevirt org
  github/ci/prow/files/config.yaml
  github/ci/prow/tasks/main.yml
  github/ci/prow/templates/branch-protector.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#215 Create a okd network 4.1 provider build and deploy jobs
  github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#218 Prepare prow for CDI
  github/ci/prow/files/config.yaml
  github/ci/prow/files/jobs/containerized-data-importer/OWNERS
  github/ci/prow/files/jobs/containerized-data-importer/containerized-data-importer-presubmits.yaml
  github/ci/prow/files/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#219 Make flakefinder weekly report execute daily
  github/ci/prow/files/jobs/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#220 Adjust owners for community projects
  github/ci/prow/files/jobs/kubevirt-tutorial/OWNERS
  github/ci/prow/files/jobs/kubevirt.github.io/OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/XS

#221 Add ProwJob Metrics exporter
  github/ci/prow/tasks/main.yml
  github/ci/prow/templates/accounts.yaml
  github/ci/prow/templates/exporter-deployment.yaml
  github/ci/prow/templates/exporter-rbac.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#222 Changing periodic Jobs for Kubevirt.github.io
  github/ci/prow/files/jobs/kubevirt.github.io/kubevirt-github-io-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#223 Add command line options org and repo for report generation.
  github/ci/prow/files/jobs/kubevirt/kubevirt-periodics.yaml
  robots/flakefinder/index.go
  robots/flakefinder/index_test.go
  robots/flakefinder/main.go
  robots/flakefinder/report.go
  robots/flakefinder/report_test.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#227 Fork release jobs for 0.22
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits-0.22.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#228 Remove openshift-docker testlane for master
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#224 Use latest image on KubeVirt tutorial tests
  github/ci/prow/files/jobs/kubevirt-tutorial/kubevirt-tutorial-periodics.yaml
  github/ci/prow/files/jobs/kubevirt-tutorial/kubevirt-tutorial-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#230 Make CDI jobs required on the CDI repo
  github/ci/prow/files/config.yaml
  github/ci/prow/files/jobs/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#233 Always run the OKD 4.1 job
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#235 Add branch protection for hostpath-provisoner
  github/ci/prow/files/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#236 Add label for openshift CI
  github/ci/prow/files/labels.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#237 Add jobs for okd-4.3 provider
  github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#238 Disable okd-4.1 lane
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS
