Repository kubevirt/project-infra, pull requests merged in 2020-03, with the labels that each got.

#375 changing kustomize path to /usr/bin
  images/kubevirt-infra-bootstrap/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#376 updating the base image so that kustomize will be accessible to dash
  github/ci/prow/files/jobs/k8snetworkplumbingwg/kubemacpool-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#380 add CNAO GitHub release automation
  github/ci/prow/files/jobs/cluster-network-addons-operator/cluster-network-addons-operator-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#381 Add 4.3 jobs to NMO
  github/ci/prow/files/jobs/node-maintenance-operator/node-maintenance-operator-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#382 NMO 4.3 update the test image
  github/ci/prow/files/jobs/node-maintenance-operator/node-maintenance-operator-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#378 kubevirt: Add ipv6 lane
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#383 Add macvtap-cni postsubmit jobs
  github/ci/prow/files/jobs/macvtap-cni/macvtap-cni-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#368 Adjust kubevirt jobs to the simplified provision layout
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, do-not-merge/hold, lgtm, size/M

#384 allow rerun of builds through UI
  github/ci/prow/files/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#385 Enable rerun functionality in deck
  github/ci/prow/templates/deck-deployment.yaml
  github/ci/prow/templates/deck-rbac.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#386 Add a release postcommit hook for the macvtap-cni project.
  github/ci/prow/files/jobs/macvtap-cni/macvtap-cni-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#388 Add new ember ci lane.
  github/ci/prow/files/jobs/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#391 rename ovs-cni e2e tests target
  github/ci/prow/files/jobs/ovs-cni/ovs-cni-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#387 Backport ipv6 lane to 0.26
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits-0.26.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#393 Enable flaky tests check
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#379 kubevirt: Add cnao k8s 1.17 lane.
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#390 Export snapshot/block sc properly in ember lane.
  github/ci/prow/files/jobs/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#395 sriov: silence tar extracting
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#396 Enable reporting for test flake check
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#397 Set TARGET_COMMIT to base sha
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#401 Increase timeouts for certain CDI lanes so they don't fail.
  github/ci/prow/files/jobs/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#400 remove Genie test lane from kubevirt
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#402 Replace kubevirt multus lane with k8s-cnao-1.17
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M
