Repository kubevirt/project-infra, pull requests merged in 2020-04, with the labels that each got.

#403 Add labels support to kubernetes-nmstate project
  github/ci/prow/files/labels.yaml
  github/ci/prow/files/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#404 Map the current knmstate labels to prow
  github/ci/prow/files/labels.yaml
  github/ci/prow/templates/label-sync.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#405 knmstate: Remove duplicated labels
  github/ci/prow/files/labels.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#399 Add vm-import-operator job
  github/ci/prow/files/jobs/vm-import-operator/OWNERS
  github/ci/prow/files/jobs/vm-import-operator/vm-import-operator-periodics.yaml
  github/ci/prow/files/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#407 Create job to build and push kubevirt nightly to docker
  github/ci/prow/files/config.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt-periodics.yaml
  github/ci/prow/files/jobs/kubevirtci/kubevirtci-presets.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#410 Start periodic job for KubeVirt nightly build shortly after 1 AM
  github/ci/prow/files/jobs/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#411 Delete k8s genie and multus jobs
  github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#414 Kubernetes 1.14 is EOL
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#413 Make k8s-1.17 job report, but don't run it always
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#415 Build and push HCO test utils image
  github/ci/prow/files/jobs/hyperconverged-cluster-operator/hyperconverged-cluster-operator-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#416 Always run kind-k8s-1.17.0-ipv6
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#417 Use docker login in vm-import-operator job
  github/ci/prow/files/jobs/vm-import-operator/vm-import-operator-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#418 Use bash instead of sh in vm-import-operator
  github/ci/prow/files/jobs/vm-import-operator/vm-import-operator-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#419 Add github token to HCO to be able to call github API
  github/ci/prow/files/jobs/hyperconverged-cluster-operator/OWNERS
  github/ci/prow/files/jobs/hyperconverged-cluster-operator/hyperconverged-cluster-operator-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#420 knmstate: Operator e2e jobs
  github/ci/prow/files/jobs/nmstate/kubernetes-nmstate-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/M
