Repository kubevirt/project-infra, pull requests merged in 2020-10, with the labels that each got.

#656 Make pull-kubevirt-unit-test report to GH and required
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.31.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.32.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.33.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#657 Make travis ci run required for the last ten release branches
  github/ci/prow/files/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#658 Use go mod vendor after updating client-go
  github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#660 Reduce the max job execution time for windows jobs
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#659 Release configs for kubevirt/kubevirt release branch release-0.34
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.34.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XL

#661 Bump golang to 1.15.2 for HCO nightly
  github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#662 Make pull-kubevirt-build required
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.31.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.32.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.33.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.34.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#663 Add configuration for kubevirt/must-gather
  github/ci/prow/files/config.yaml
  github/ci/prow/files/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#664 Add section for updating prow configuration manually
  github/ci/README.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#665 labels: Fix sig/* entries by specifying missing properties
  github/ci/prow/files/labels.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#602 Add automated deployment to rehearse image
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow/tasks/main.yml
  images/rehearse
Labels: approved, dco-signoff: yes, lgtm, size/L

#638 Add gosec as presubmit job
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#668 Use for kubevirtci jobs an image which includes go
  github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#666 Job modifications required for removing manual steps from kubevirtci
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#669 Login to dockerhub in the kubevirtci release job
  github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#670 k8s 1.16 is EOL, remove kubevirt/kubevirt e2e test
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#667 Add configurations for HCO release-1.2 branch
  github/ci/prow/files/config.yaml
  github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.2.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#674 Let required kubevirtci lanes always run
  github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#675 Add new test to HCO CI, to check node placement
  github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#676 Remove HCO's node placement test
  github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#677 Disable goveralls prow job
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#552 Add tests binary to nightly
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#633 Adding persistent storage volume for Grafana data
  github/ci/prometheus/templates/grafana.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#648 Enable reporting for k8s-1.19
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#680 enable sriov lane
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.30.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.31.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.32.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.33.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.34.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#682 sriov lane: turn-off reporting
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#545 macvtap: update repo merge strategy
  github/ci/prow/files/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS
