Repository kubevirt/project-infra, pull requests merged in 2020-07, with the labels that each got.

#526 flakefinder: add rolling window report
  github/ci/prow/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-periodics.yaml
  github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-periodics.yaml
  robots/flakefinder/index.go
  robots/flakefinder/main.go
  robots/flakefinder/main_test.go
  robots/flakefinder/report.go
  robots/flakefinder/report_test.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#536 Fix arg for rolling window flakefinder job
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#533 Make the k8s-1.18 lanes mandatory for CDI
  github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits-1.19.yaml
  github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#540 Specify repo, so we don't default to "kubevirt"
  github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#542 Add missing K8s context to the playbook
  github/ci/prow/tasks/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#541 Change weekly flakefinder report to run as cron
  github/ci/prow/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-periodics.yaml
  github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
  github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#534 Fix popup bug
  robots/flakefinder/report.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#535 Release configs for kubevirt/kubevirt release branch release-0.31
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.31.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XL

#544 Update test lanes for NMO
  github/ci/prow/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#530 hide results of SR-IOV lane
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#547 Remove ocp/okd jobs since they are going to be deprecated
  github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XL

#527 Update pull-kubevirt-e2e-k8s-1.18 to be mandatory
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#548 Removed deprecated OCP test lane for NMO
  github/ci/prow/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#517 Automate the master index page creation for the flakefinder entry page
  Makefile
  github/ci/prow/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-periodics.yaml
  github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
  github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-periodics.yaml
  robots/flakefinder/BUILD.bazel
  robots/flakefinder/downloader.go
  robots/flakefinder/index.go
  robots/flakefinder/main.go
  robots/flakefinder/main_test.go
  robots/flakefinder/report.go
  robots/flakefinder/report_test.go
  robots/indexpagecreator/BUILD.bazel
  robots/indexpagecreator/Makefile
  robots/indexpagecreator/main.go
  robots/indexpagecreator/update-jobs-with-latest-indexpagecreator-image.sh
  robots/pkg/flakefinder/BUILD.bazel
  robots/pkg/flakefinder/flakefinder.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#550 Enable invalidcommitmsg plugin for kubevirt org
  github/ci/prow/files/config.yaml
  github/ci/prow/files/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#551 Increase pod timeout for k8s check provision and push
  github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#553 Add dry-run flag for cnao jobs
  github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#555 Change cnao flakefinder daily to cron
  github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#556 Fix git commit reference in nightly publish job
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#557 Add a script to provide github credentials to git
  hack/git-askpass.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#559 Run kubernetes-nmstate release job at tagging
  github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#561 Enable kubevirt-bot for ssp-components
  github/ci/prow/files/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#565 Delete obsolete lanes for CDI
  github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M
