Repository kubevirt/project-infra, pull requests merged in 2020-11, with the labels that each got.

#678 remove common-templates jobs
  github/ci/prow/files/jobs/kubevirt/common-templates/common-templates-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#671 [rehearsal] Rebase PRs on target branch
  external-plugins/rehearse/plugin/go.mod
  external-plugins/rehearse/plugin/handler/handler.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#685 Mitigate docker hub push fails on EOF with RestartPolicy=OnFailure
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#688 Make k8s-1.19 lane mandatory
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.34.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#689 Add pull-kubernetes-nmstate-docs job
  github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#687 Added uploader periodic job and uploader plugin readme
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  plugins/cmd/uploader/README.md
  plugins/cmd/uploader/uploader.go
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/M

#683 Release configs for kubevirt/kubevirt release branch release-0.35
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.35.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XL

#693 knmstate: Branchout jobs for v0.31
  github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.31.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#582 cnao, Add components tier1 functests
  github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#697 install bazelisk in temp dir for mirror uploader periodic job
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#695 cnao, Add components tier1 functests cont.
  github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#699 knmstate: Skip gh-pages branch at publish job
  github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#673 Initial commit for Dockerfiles and yaspeller files to support new tooling
  images/casperjs/Dockerfile
  images/kubevirt-userguide/Dockerfile
  images/yaspeller/.yaspeller.json
  images/yaspeller/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, size/L

#637 Add presubmit jobs for kubectl-virt-plugin
  github/ci/prow/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#703 knmstate: Always run as non optional the docs lane
  github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#708 Remove kubevirtci kind ipv6 lane
  github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#705 knmstate, publish: Use GIT_ASKPASS
  github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#704 Add bootstrap image with docker mirror proxy support
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  images/bootstrap/Dockerfile
  images/bootstrap/runner.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#701 cnao, Run macvtap-cni, ovs-cni tier1 tests on evey PR
  github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#707 cnao, Change all tier1 tests to be mandatory
  github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#706 Add docker mirror proxy
  github/ci/prow/files/config.yaml
  github/ci/prow/tasks/main.yml
  github/ci/prow/templates/mirror-proxy-config.yaml
  github/ci/prow/templates/mirror-proxy-service.yaml
  github/ci/prow/templates/mirror-proxy.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#692 Notify coreos/eko channel on all job failures for kubevirt.github.io
  github/ci/prow/files/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#712 Add missing tasks for deploying docker mirror proxy resources
  github/ci/prow/tasks/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/M

#713 Fix docker registry proxy image name
  github/ci/prow/templates/mirror-proxy.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#622 Add ghproxy to autoowners job
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#715 Add fgimenez to OWNERS
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/XS

#714 Add requirements file for ansible roles
  github/ci/README.md
  github/ci/prow.yaml
  github/ci/remote-cluster.yaml
  github/ci/requirements.txt
Labels: approved, dco-signoff: yes, lgtm, size/S

#717 Modify jobs to use docker mirror proxy
  github/ci/prow/files/config.yaml
  github/ci/prow/tasks/main.yml
  github/ci/shared-deployments/files/docker-daemon-mirror-proxy.conf
  github/ci/shared-deployments/tasks/main.yml
  github/ci/shared-deployments/templates/docker-daemon-mirror-config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#720 Do not configure docker on bootstrap containers
  images/bootstrap/runner.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#719 SRIOV lane, Prevent Resources Leak
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#722 Add requirements for kubernetes_crud
  github/ci/kubernetes_crud/README.md
  github/ci/kubernetes_crud/molecule/default/cleanup.yml
  github/ci/kubernetes_crud/molecule/default/converge.yml
  github/ci/kubernetes_crud/molecule/default/molecule.yml
  github/ci/kubernetes_crud/requirements.txt
Labels: approved, dco-signoff: yes, lgtm, size/M

#723 Update kubevirt e2e jobs on bare-metal to use docker proxy.
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#724 Include all the required modules in ansible requirements
  github/ci/README.md
  github/ci/kubernetes_crud/README.md
  github/ci/kubernetes_crud/requirements.txt
  github/ci/requirements.txt
Labels: approved, dco-signoff: yes, lgtm, size/XS

#727 Add job to upload testing manifests for releases
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#725 Add lane for nmstate with parallel nncp rollout
  github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#732 Use docker proxy for kubevirt nightly
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#730 cnao, 0.42: Increase lifecycle test timeouts
  github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.42.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#733 Make srivo kind up lane mandatory
  github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#734 knmstate, publish: Use env var for github email
  github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#736 SRIOV lane jobs remove Go download progress
  github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#738 Adapt nightly HCO to new build-manifests
  github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#716 Move cnao lane to 1.19
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#737 cnao: Add quay.io loging to release job
  github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#741 knmstate, docs: Don't skip github report
  github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#740 Knmstate mount GitHub token publish
  github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#742 Use docker proxy for nightly HCO
  github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#739 Make nmstate parallel lane required
  github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#731 Deploy docker proxy components in both clusters
  github/ci/prow/tasks/main.yml
  github/ci/remote-cluster/tasks/main.yml
  github/ci/remote-cluster/templates/mirror-proxy.yaml
  github/ci/shared-deployments/tasks/main.yml
  github/ci/shared-deployments/templates/mirror-proxy-config.yaml
  github/ci/shared-deployments/templates/mirror-proxy-service.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#743 SRIOV lane jobs: use bash
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#745 Add retry to push of kubevirt nightly
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#746 Use bash for running the nightly script
  github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#747 Make counter work with bourne shell
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#479 Move SR-IOV passthrough CNI to this repo
  cni-plugins/sriov-passthrough-cni/Dockerfile
  cni-plugins/sriov-passthrough-cni/README.md
  cni-plugins/sriov-passthrough-cni/deploy/multus-cni.yaml
  cni-plugins/sriov-passthrough-cni/install-plugin
  cni-plugins/sriov-passthrough-cni/plugin/90-sriov-passthrough-cni.conf
  cni-plugins/sriov-passthrough-cni/plugin/sriov-passthrough-cni
Labels: approved, dco-signoff: yes, lgtm, size/L
