Repository kubevirt/project-infra, pull requests merged in 2020-08, with the labels that each got.

#566 Release configs for kubevirt/kubevirt release branch release-0.32
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.32.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XL

#457 Add Kubemacpool functests on CNAO job
  github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#571 Enable Kubemacpool tests on CNAO lane
  github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#572 sriov-lane job: disable
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#570 Add an optional lane with a newer version of base image.
  github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#574 Make kubevirts generate prowjob required
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#573 Optional test lane needs to install libdevmapper.
  github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#575 If things look bad in CI, the one hour retest is an issue
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#576 Add permissions for hook to list ProwJobs
  github/ci/prow/templates/hook-rbac.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#568 Fix the bot command list link
  github/ci/prow/files/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#578 Update base image for testing.
  github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#581 Merge ssp repositories PRs when approved
  github/ci/prow/files/config.yaml
  github/ci/prow/files/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#579 Schedule our caches on a dedicated node.
  github/ci/prow/templates/greenhouse-deployment.yaml
  github/ci/prow/templates/mirror.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#585 Disable statusreconciler
  github/ci/prow/templates/statusreconciler-deployment.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#591 Fix make generate to run the right target
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#580 labels: Rename topic/network to sig/network
  github/ci/prow/files/labels.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#592 Run only one kind lane per node at the time
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#586 Move coverage from travis to prow - add prow job
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#593 Allow more executions in parallel of the core kubevirt/kubevirt lanes
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#577 Let the reconciler use our github request cache
  github/ci/prow/templates/statusreconciler-deployment.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#594 Update rerun_auth_config to the not deprecated form
  github/ci/prow/files/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#599 Change the retest timeout back to one hour
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#600 Unblock status reconciler by removing pull-kubevirt-generate from release branches
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.31.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.32.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#605 Make coveralls non-required until it is fixed
  github/ci/prow/files/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#595 Re-enable statusreconciler and store the state on GCS
  github/ci/prow/templates/statusreconciler-deployment.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#606 Allow non org admins but project owners to override jobs
  github/ci/prow/files/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#601 Ignore pull-kubevirt-goveralls for batch jobs
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#597 flakefinder: Create switch skip_results_before_start_of_report
  github/ci/prow/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-periodics.yaml
  github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
  github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-periodics.yaml
  robots/flakefinder/downloader.go
  robots/flakefinder/main.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#607 Add jobs for provisioning and pushing k8s 1.19 provider
  github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M
