Repository kubevirt/project-infra, pull requests merged in 2020-01, with the labels that each got.

#294 Make sriov lane optional
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#296 Add knmstate unit/test job
  github/ci/prow/files/jobs/nmstate/kubernetes-nmstate-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#297 Disable auto-run for the sr-iov lane
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#295 Add optional ocp-4.3 lane to kubevirt
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#298 Add knmstate job to publish after master merge
  github/ci/prow/files/jobs/nmstate/kubernetes-nmstate-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#300 Remove limits from knmstate publish job
  github/ci/prow/files/jobs/nmstate/kubernetes-nmstate-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#301 Fork release-0.24 jobs
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits-0.24.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#302 Add a release job for kubernetes-nmstate
  github/ci/prow/files/jobs/nmstate/kubernetes-nmstate-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#305 Fix cnao name and drop okd
  github/ci/prow/files/jobs/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#306 enable optional 1.17 host path provisioner lane for CDI
  github/ci/prow/files/jobs/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#304 add OCP job to knmstate
  github/ci/prow/files/jobs/nmstate/kubernetes-nmstate-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#264 enable windows 2019 test for common templates
  github/ci/prow/files/jobs/common-templates/common-templates-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#309 Add specific upgrade lane that upgrades from multiple different previ…
  github/ci/prow/files/jobs/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#307 Add kubernetes-nmstate flakefinder
  github/ci/prow/files/jobs/nmstate/kubernetes-nmstate-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#311 Increase ocp-4.3 provision jobs timeout
  github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#310 Add nmstate/kubernetes-nmstate branch protection
  github/ci/prow/files/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#312 Duplicate memory for ocp-4.3 jobs
  github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#313 Disable knmstate OKD lane
  github/ci/prow/files/jobs/nmstate/kubernetes-nmstate-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#315 Add ocp-4.4 jobs
  github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#316 add qinqon and phoracek to OWNERS
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/XS

#314 Make the multi upgrade lane required and automatic.
  github/ci/prow/files/jobs/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#317 Add k8s kind jobs
  github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#319 Add ipv6 config for docker daemon
  github/ci/prow/files/docker-daemon-mirror.conf
Labels: approved, dco-signoff: yes, lgtm, size/XS

#322 K8s fedora jobs
  github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#325 Add fedora base image jobs
  github/ci/prow/files/jobs/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#320 Revert "Disable auto-run for the sr-iov lane (#297)"
  github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#326 Add optional NFS storage lane for CDI
  github/ci/prow/files/jobs/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M
