Repository kubevirt/project-infra, pull requests merged in 2021-02, with the labels that each got.

#908 Add prow deploy test image
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  images/prow-deploy/Dockerfile
  images/prow-deploy/requirements.txt
Labels: approved, dco-signoff: yes, lgtm, size/L

#884 sriov CNI, Allocate only one sriov PF
  cni-plugins/sriov-passthrough-cni/Dockerfile
  cni-plugins/sriov-passthrough-cni/README.md
  cni-plugins/sriov-passthrough-cni/deploy/multus-cni.yaml
  cni-plugins/sriov-passthrough-cni/install-plugin
  cni-plugins/sriov-passthrough-cni/plugin/90-sriov-passthrough-cni.conf
  cni-plugins/sriov-passthrough-cni/plugin/sriov-passthrough-cni
Labels: approved, dco-signoff: yes, lgtm, size/L

#859 prow-deploy: reduce test execution time
  github/ci/prow-deploy/README.md
  github/ci/prow-deploy/kustom/base/manifests/local/greenhouse-deployment.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirtci-testing/kustomization.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirtci-testing/patches/StrategicMerge/ghproxy.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirtci-testing/patches/StrategicMerge/greenhouse-deployment.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirtci-testing/resources/bootstrap.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirtci-testing/resources/ghproxy-persistent-volume.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirtci-testing/resources/greenhouse-persistent-volume.yaml
  github/ci/prow-deploy/kustom/render-environment-configs.sh
  github/ci/prow-deploy/molecule/default/collect.yml
  github/ci/prow-deploy/molecule/default/collect_resource.yml
  github/ci/prow-deploy/molecule/default/converge.yml
  github/ci/prow-deploy/molecule/default/destroy.yml
  github/ci/prow-deploy/molecule/default/molecule.yml
  github/ci/prow-deploy/molecule/default/prepare.yml
  github/ci/prow-deploy/molecule/default/smoke_tests.yml
  github/ci/prow-deploy/molecule/default/vars/collect.yml
  github/ci/prow-deploy/molecule/default/vars/kubevirtci-testing.yml
  github/ci/prow-deploy/tasks/cleanup.yml
  github/ci/prow-deploy/tasks/deploy.yml
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#913 periodic-kubevirt-update-release-0.36-testing-manifests: Check whether folder exists before trying to delete it
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#910 Enable org mutations
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/prow/files/orgs.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#916 Add nelsonspbr to org members
  github/ci/prow/files/orgs.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#920 Fix target calculation for kubevirt periodic master e2e
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#921 Remove user-guide periodics
  github/ci/prow/files/jobs/kubevirt/user-guide/user-guide-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#905 Move ok-to-test to default section
  github/ci/prow/files/labels.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#855 Assign to prow-job-taskforce
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow/files/orgs.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#923 Make k8s 1.20 lane run always
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#924 Add libvirt-devel to bootstrap image
  images/bootstrap/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, size/M

#784 Introduce sriov patch nodes script
  cni-plugins/sriov-passthrough-cni/README.md
  hack/patch_node.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#925 Add alonsadan as a member to kubevirt org
  github/ci/prow/files/orgs.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#931 Execute periodic e2e from master twice a day
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#930 Increase timeout for publish-kubevirtci
  github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#914 Release configs for kubevirt/kubevirt release branch release-0.38
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.38.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XL

#936 Add sippy deployment
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/services/common/k8s/pkg/wait/wait.go
  github/ci/services/sippy/BUILD.bazel
  github/ci/services/sippy/README.md
  github/ci/services/sippy/e2e/e2e_test.go
  github/ci/services/sippy/hack/deploy.sh
  github/ci/services/sippy/manifests/full.yaml
  github/ci/services/sippy/manifests/ingress.yaml
  github/ci/services/sippy/overlays/testing/cluster-issuer.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#935 Update yaspeller dictionary file
  images/yaspeller/.yaspeller.json
Labels: approved, dco-signoff: yes, lgtm, size/M

#940 Add periodic job that syncs OpenSuse Crio repo
  github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#932 Add ci-health to prometheus scrape targets
  github/ci/prometheus/templates/prometheus-config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#942 Fix missing reposync in kubevirtci crio sync periodic
  github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#944 Fix missing $ sign
  github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#943 Add job failures 4h grafana dashboard
  github/ci/prometheus/templates/dashboards.yaml
  github/ci/services/prometheus-stack/manifests/grafana.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#945 Add missing curly braces around BASE_REPOID var
  github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#939 Add alicefr to kubevirt members.
  github/ci/prow/files/orgs.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#937 Add list of jobs
  github/ci/prow/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-periodics.yaml
  github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
  github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-periodics.yaml
  robots/flakefinder/BUILD.bazel
  robots/flakefinder/Makefile
  robots/flakefinder/push.sh
  robots/flakefinder/report.go
  robots/flakefinder/report_test.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#929 Add shellyka13 to org members
  github/ci/prow/files/orgs.yaml
Labels: approved, dco-signoff: yes, lgtm, needs-ok-to-test, size/XS

#948 Use fedora image instead of debian and download metadata for crio mirror
  github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#950 Update yaspeller dictionary file
  images/yaspeller/.yaspeller.json
Labels: approved, dco-signoff: yes, lgtm, size/L

#947 Several grafana fixes
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/services/prometheus-stack/manifests/grafana.yaml
  github/ci/services/prometheus-stack/manifests/ingress.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#952 prow-deploy: add SRIOV node patch action
  github/ci/prow-deploy/molecule/default/prepare.yml
  github/ci/prow-deploy/molecule/default/smoke_tests.yml
  github/ci/prow-deploy/molecule/default/vars/kubevirtci-testing.yml
  github/ci/prow-deploy/tasks/deploy.yml
  github/ci/prow-deploy/vars/ibmcloud-production/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/S

#953 Add e2e jobs overview dashboard
  github/ci/prometheus/templates/dashboards.yaml
  github/ci/services/prometheus-stack/manifests/grafana.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#957 Add triage labels
  github/ci/prow/files/labels.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#956 use main branch for containerized-data-importer
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#958 Persist merge-queue dashboard
  github/ci/prometheus/templates/dashboards.yaml
  github/ci/services/prometheus-stack/README.md
  github/ci/services/prometheus-stack/manifests/grafana.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#955 Refactor secret management scripts to separate file
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  hack/manage-secrets.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#959 Fix user-guide postsubmit permission issues
  github/ci/prow/files/jobs/kubevirt/user-guide/user-guide-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#962 Update cihealth dashboard to show standard deviation
  github/ci/prometheus/templates/dashboards.yaml
  github/ci/services/prometheus-stack/manifests/grafana.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#971 Add job to upload testing manifests
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#961 Use docker-proxy in CDI jobs
  github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#973 Drop old kubevirt releases and ensure unique names
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.13.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.17.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.20.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.22.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.23.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.24.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.26.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.29.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.30.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.31.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.32.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.33.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.34.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.35.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.36.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#835 Run kubevirt e2e tests without the buider image to make them more lightweight
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presets.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#927 csi-driver presubmits
  github/ci/prow/files/jobs/kubevirt/csi-driver/csi-driver-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#970 Make the dependency mirror tool more fault tolerant
  plugins/cmd/uploader/uploader.go
  plugins/mirror/bazel.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#975 testgrid: set transfigure image tag
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#974 prow-deploy: use quay image for kind test cluster
  github/ci/prow-deploy/molecule/default/prepare.yml
  github/ci/prow-deploy/molecule/default/vars/kubevirtci-testing.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#976 Revert for sriov lane to debian based bootstrap image
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#977 Add sriov lane requirements
  images/bootstrap/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#978 kubevirt push nightly: fix error handling
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M
