Repository kubevirt/project-infra, pull requests merged in 2021-05, with the labels that each got.

#1188 HCO: change the default branch to main
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1187 Add optional k8s-1.20 ceph lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1186 Run quarantined tests in SIG e2e periodic lanes
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1190 Set K8s 1.20 sig-compute lane to run always
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1160 Add validation presubmit for sigs.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/community/community-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1172 Clean up make files for flakefinder and indexpagecreator
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  robots/cmd/flakefinder/Makefile
  robots/cmd/indexpagecreator/BUILD.bazel
  robots/cmd/indexpagecreator/Makefile
  robots/cmd/indexpagecreator/update-jobs-with-latest-indexpagecreator-image.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#1183 Also copy cluster-up directory when adding new provider in kubevirtci bump
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  robots/cmd/kubevirtci-bumper/main.go
  robots/pkg/kubevirtci/kubevirtci.go
  robots/pkg/kubevirtci/kubevirtci_test.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#1193 cnao, Add lanes for new stable branch release-0.53
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.53.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1191 Release configs for kubevirt/kubevirt release branch release-0.41
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.41.yaml
Labels: dco-signoff: yes, size/XXL

#1162 Manage operator tests using its dedicated SIG label
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.40.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1196 Fix superfluous double quote
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1184 Create prow job for new kubernetes release
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  robots/cmd/kubevirtci-presubmit-creator/BUILD.bazel
  robots/cmd/kubevirtci-presubmit-creator/main.go
  robots/cmd/kubevirtci-presubmit-creator/main_test.go
Labels: approved, dco-signoff: yes, lgtm, size/XL

#1198 Fix binary name
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1192 Add periodics and presubmits for k8s-1.21
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1199 Enable 1.20-operator presubmit to run on PRs
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1206 kubemacpool, Add lanes for new stable branch release-v0.21
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits-v0.21.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1200 Remove old lanes
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1197 Include 1.19-sig-compute in reports
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1201 Re-enable prow deploy verify step
  github/ci/prow-deploy/kustom/base/kustomization.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/deck-ingress.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/gcsweb-ingress.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirtci-testing/patches/StrategicMerge/deck-ingress.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirtci-testing/patches/StrategicMerge/gcsweb-ingress.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirtci-testing/resources/ingress-nginx-controller.yaml
  github/ci/prow-deploy/molecule/default/molecule.yml
  github/ci/prow-deploy/molecule/default/prepare.yml
  github/ci/prow-deploy/molecule/default/smoke_tests.yml
  github/ci/prow-deploy/vars/workloads-production/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1205 Automated prow bump
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  hack/bump-prow.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#1209 Reenable reporting to GitHub for kubevirt goveralls
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1212 Add periodics to kubevirt flakefinder weeklies
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1208 Filter sig-compute on 1.19 lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1215 Add labels to uploader PR
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  hack/git-pr.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#1216 Enable goveralls to always run for kubevirt
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1189 Create periodic job for kubevirt/libguestfs-appliance
  github/ci/prow-deploy/files/jobs/kubevirt/libguestfs-appliance/libguestfs-appliance-periodics.yaml
Labels: dco-signoff: yes, lgtm, size/M

#1213 Run all remaining storage and networking tests with cgroupv2
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1218 Deploy prometheus-operator on prow-workloads cluster
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/services/prometheus-stack/BUILD.bazel
  github/ci/services/prometheus-stack/e2e/e2e_test.go
  github/ci/services/prometheus-stack/hack/deploy.sh
  github/ci/services/prometheus-stack/manifests/stack/common/kube-prometheus-stack.yaml
  github/ci/services/prometheus-stack/manifests/stack/common/namespace.yaml
  github/ci/services/prometheus-stack/manifests/stack/common/node-exporter.yaml
  github/ci/services/prometheus-stack/manifests/stack/loki-stack.yaml
  github/ci/services/prometheus-stack/manifests/stack/production-control-plane/grafana.yaml
  github/ci/services/prometheus-stack/manifests/stack/production-control-plane/ingress.yaml
  github/ci/services/prometheus-stack/manifests/stack/production-e2e-workloads/.gitkeep
  github/ci/services/prometheus-stack/manifests/stack/testing
  github/ci/services/prometheus-stack/patches/production-e2e-workloads/prometheus-storage.yaml
  github/ci/services/prometheus-stack/secrets/production-control-plane/grafana/.gitkeep
Labels: approved, dco-signoff: yes, lgtm, size/XL

#1219 Bump builder tag to prevent pr-creator errors
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1223 fix libguestfs appliance periodic job
  github/ci/prow-deploy/files/jobs/kubevirt/libguestfs-appliance/libguestfs-appliance-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1221 Adapt TestGrid config managment to Config Merger
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/testgrid/hack/check.sh
  github/ci/testgrid/hack/common.sh
  github/ci/testgrid/hack/update.sh
  github/ci/testgrid/hack/upload.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#1225 Fix test-infra repo path.
  github/ci/testgrid/hack/common.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1210 Update dictionary file
  images/yaspeller/.yaspeller.json
Labels: approved, dco-signoff: yes, lgtm, size/S

#1224 Migrate ovs-cni repository under network plumbing working group organization
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/ovs-cni/OWNERS
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/ovs-cni/ovs-cni-presubmits.yaml
  github/ci/prow-deploy/files/orgs.yaml
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1227 Fix project-infra paths in pull-project-infra-check-testgrid-config
  github/ci/testgrid/hack/common.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1217 Enable report of 1.20-sig-storage
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1229 Enable DCO plugin on OVS CNI project
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1235 Fix OVS CNI branch protection configuration
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1233 macvtap-cni: rename the main branch
  github/ci/prow-deploy/files/jobs/kubevirt/macvtap-cni/macvtap-cni-postsubmits.yaml
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1228 Use new kubernetes-nmstate default branch "main"
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1238 Updated prow deployment
  github/ci/prow-deploy/kustom/base/kustomization.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/cherrypicker_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/exporter-deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/exporter-rbac.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/greenhouse-deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/label-sync-kubevirt.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/label-sync-nmstate.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/prow-rehearse-deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/release-blocker_deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/kustomization.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/deck_deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/prow_controller_manager_deployment.yaml
  github/ci/prow-deploy/molecule/default/prepare.yml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1236 Run unit tests for kubevirt unnested
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1239 Configure greenhouse to use PVC
  github/ci/prow-deploy/kustom/base/manifests/local/greenhouse-deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/kustomization.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/StrategicMerge/greenhouse-deployment.yaml
  github/ci/prow-deploy/molecule/default/smoke_tests.yml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1232 Add postsubmit to calculate kubevirt coverage on master branch
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1243 Fix testgrid update job
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/testgrid/hack/check.sh
  github/ci/testgrid/hack/common.sh
  github/ci/testgrid/hack/update.sh
  github/ci/testgrid/hack/upload.sh
  hack/create_bazel_cache_rcs.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#726 add restcoverage lens
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1237 Add lanes for nonroot to increase coverage
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1251 kubemacpool, Add lanes to stable branch release-v0.20
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits-v0.20.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1226 Add victortoso to kubevirt members
  github/ci/prow-deploy/files/orgs.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1230 Build img consolidation and streamline
  images/kubevirt-userguide/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, size/M

#1248 Allow ghproxy to run on any node
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/kustomization.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/ghproxy_deployment.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirtci-testing/resources/bootstrap.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1249 Configure docker-mirror-proxy and greenhouse for prow-workloads
  github/ci/prow-deploy/kustom/base/kustomization.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/docker-daemon_configmap.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/docker-mirror_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/docker-mirror_service.yaml
  github/ci/prow-deploy/kustom/components/docker-mirror-proxy/base/configs/.gitkeep
  github/ci/prow-deploy/kustom/components/docker-mirror-proxy/base/configs/docker
  github/ci/prow-deploy/kustom/components/docker-mirror-proxy/base/configs/docker-proxy
  github/ci/prow-deploy/kustom/components/docker-mirror-proxy/base/kustomization.yaml
  github/ci/prow-deploy/kustom/components/docker-mirror-proxy/base/resources/deployment.yaml
  github/ci/prow-deploy/kustom/components/docker-mirror-proxy/base/resources/service.yaml
  github/ci/prow-deploy/kustom/components/docker-mirror-proxy/base/secrets/.gitkeep
  github/ci/prow-deploy/kustom/components/docker-mirror-proxy/hostpath/kustomization.yaml
  github/ci/prow-deploy/kustom/components/docker-mirror-proxy/hostpath/patches/JsonRFC6902/deployment.yaml
  github/ci/prow-deploy/kustom/components/docker-mirror-proxy/pv/kustomization.yaml
  github/ci/prow-deploy/kustom/components/docker-mirror-proxy/pv/patches/JsonRFC6902/deployment.yaml
  github/ci/prow-deploy/kustom/components/greenhouse/base/kustomization.yaml
  github/ci/prow-deploy/kustom/components/greenhouse/base/resources/deployment.yaml
  github/ci/prow-deploy/kustom/components/greenhouse/base/resources/service.yaml
  github/ci/prow-deploy/kustom/components/greenhouse/hostpath/kustomization.yaml
  github/ci/prow-deploy/kustom/components/greenhouse/hostpath/patches/JsonRFC6902/deployment.yaml
  github/ci/prow-deploy/kustom/components/greenhouse/pv/kustomization.yaml
  github/ci/prow-deploy/kustom/components/greenhouse/pv/patches/JsonRFC6902/deployment.yaml
  github/ci/prow-deploy/kustom/components/greenhouse/pv/resources/pvc.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/kustomization.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/docker-mirror-proxy_pvc.yaml
  github/ci/prow-deploy/kustom/overlays/workloads-production/kustomization.yaml
  github/ci/prow-deploy/kustom/overlays/workloads-production/patches/JsonRFC6902/prow-jobs-namespace.yaml
  github/ci/prow-deploy/molecule/default/vars/kubevirtci-testing.yml
  github/ci/prow-deploy/tasks/configs.yml
  github/ci/prow-deploy/tasks/secrets.yml
  github/ci/prow-deploy/vars/ibmcloud-production/main.yml
  github/ci/prow-deploy/vars/workloads-production/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1250 Enable docker proxy and bazel cache on prow-workloads cluster
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.41.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1254 Fix incorrect dir name
  images/kubevirt-user-guide/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1255 knmstate: Use correct project-infra branch
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1253 Add NMO 0.9 release branch
  github/ci/prow-deploy/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-presubmits-release-0.9.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1257 Add akalenyu to kubevirt members
  github/ci/prow-deploy/files/orgs.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#1138 Sync cri-o version 1.21
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1118 sig-network, k8s-1.19, Move presubmit job to new CI cluster
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1261 Use git-pr script in TestGrid update job
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/testgrid/hack/common.sh
  github/ci/testgrid/hack/update.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#1265 Always run 1.21 provision check
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1246 terraform-provider-kubevirt: Add presubmits file
  github/ci/prow-deploy/files/jobs/kubevirt/terraform-provider-kubevirt/terraform-provider-kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M
