Repository kubevirt/project-infra, pull requests merged in 2021-12, with the labels that each got.

#1780 Add mkpj.sh script
  hack/mkpj.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#1781 add presubmit job for branch release-0.48
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.48.yaml
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#1783 Add default preset with go proxy setting
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1769 Ping prow job task force to review automated Prow bump PRs
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1784 The release job needs golang
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1762 Mirror images from docker.io to quay.io
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  hack/images_to_mirror.csv
  hack/mirror-images.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#1785 knmstate: Install go 1.16
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#1787 knmstate: Use golang image at postsubmit
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#1789 Knmstate release add GitHub token
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1788 knmstate: Don't call publish on release
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1695 Add bump-cdi job
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1792 Fix repository on kubevirtci cdi bump
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1797 k8s-1.22-ipv6: Add kubevirtci presubmit job
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#1791 Add presubmit job to test PRs on qe-tools
  github/ci/prow-deploy/files/jobs/kubevirt/qe-tools/qe-tools-presubmits.yaml
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1798 sriov, release-0.42: Use prow-workloads for running jobs
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.42.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1799 Make maintainers admin for branch-protection to work
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1800 Fix qe-tools path in branch-protection config
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1790 Add sig-monitoring lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1794 updated the kube proxy metrics bind address to use 0.0.0.0
  github/ci/prow-performance-workloads/inventory/prow-performance-workloads/group_vars/kube-proxy.yml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1796 [cdi] move "push-builder" job from periodic to post-submit
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1778 add prow job to deploy prometheus and grafana in the performance cluster
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/services/prometheus-stack/BUILD.bazel
  github/ci/services/prometheus-stack/hack/deploy.sh
  github/ci/services/prometheus-stack/manifests/service-monitors/common/servicemonitors.yaml
  github/ci/services/prometheus-stack/manifests/service-monitors/production-performance-workloads/servicemonitors.yaml
  github/ci/services/prometheus-stack/manifests/stack/common/kube-prometheus-stack.yaml
  github/ci/services/prometheus-stack/manifests/stack/common/node-exporter.yaml
  github/ci/services/prometheus-stack/manifests/stack/k8s-services/k8s-services.yaml
  github/ci/services/prometheus-stack/manifests/stack/production-performance-workloads/grafana-general-dashboards.yaml
  github/ci/services/prometheus-stack/manifests/stack/production-performance-workloads/grafana-kubevirt-dashboards.yaml
  github/ci/services/prometheus-stack/manifests/stack/production-performance-workloads/grafana.yaml
  github/ci/services/prometheus-stack/manifests/stack/production-performance-workloads/local-path-storage.yaml
  github/ci/services/prometheus-stack/manifests/stack/production-performance-workloads/prometheus-sa.yaml
  github/ci/services/prometheus-stack/patches/rules/production-performance-workloads/k8s.yaml
  github/ci/services/prometheus-stack/patches/rules/production-performance-workloads/kube-apiserver.yaml
  github/ci/services/prometheus-stack/patches/rules/production-performance-workloads/kube-scheduler.yaml
  github/ci/services/prometheus-stack/patches/rules/production-performance-workloads/kubernetes-absent.yaml
  github/ci/services/prometheus-stack/patches/rules/production-performance-workloads/kubernetes-apps.yaml
  github/ci/services/prometheus-stack/patches/rules/production-performance-workloads/kubernetes-resources.yaml
  github/ci/services/prometheus-stack/patches/rules/production-performance-workloads/kubernetes-storage.yaml
  github/ci/services/prometheus-stack/patches/rules/production-performance-workloads/kubernetes-system.yaml
  github/ci/services/prometheus-stack/patches/rules/production-performance-workloads/node-exporter-alerting.yaml
  github/ci/services/prometheus-stack/patches/rules/production-performance-workloads/node-exporter-recording.yaml
  github/ci/services/prometheus-stack/patches/rules/production-performance-workloads/node.yaml
  github/ci/services/prometheus-stack/patches/service-monitors/production-performance-workloads/servicemonitors.yaml
  github/ci/services/prometheus-stack/patches/stack/production-control-plane/prometheus.yaml
  github/ci/services/prometheus-stack/patches/stack/production-e2e-workloads/alertmanager.yaml
  github/ci/services/prometheus-stack/patches/stack/production-e2e-workloads/prometheus.yaml
  github/ci/services/prometheus-stack/patches/stack/production-performance-workloads/alertmanager.yaml
  github/ci/services/prometheus-stack/patches/stack/production-performance-workloads/kube-prometheus-stack.yaml
  github/ci/services/prometheus-stack/secrets/production-performance-workloads/grafana/.gitkeep
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#1782 Bump containerdisks repo to golang 1.16
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1804 Add document about CNCF tools
  docs/cncf-tools.md
Labels: size/S, approved, lgtm, dco-signoff: yes

#1803 Add ARM cluster deployment jobs
  github/ci/prow-arm-workloads/bootstrap.yml
  github/ci/prow-arm-workloads/hack/bootstrap.sh
  github/ci/prow-arm-workloads/hack/common.sh
  github/ci/prow-arm-workloads/hack/deploy.sh
  github/ci/prow-arm-workloads/inventory/prow-arm-workloads/group_vars/all/all.yml
  github/ci/prow-arm-workloads/inventory/prow-arm-workloads/group_vars/all/docker.yml
  github/ci/prow-arm-workloads/inventory/prow-arm-workloads/group_vars/etcd.yml
  github/ci/prow-arm-workloads/inventory/prow-arm-workloads/group_vars/k8s-cluster/addons.yml
  github/ci/prow-arm-workloads/inventory/prow-arm-workloads/group_vars/k8s-cluster/k8s-cluster.yml
  github/ci/prow-arm-workloads/inventory/prow-arm-workloads/group_vars/k8s-cluster/k8s-net-calico.yml
  github/ci/prow-arm-workloads/inventory/prow-arm-workloads/inventory.ini
  github/ci/prow-arm-workloads/roles/bootstrap/tasks/additional_kernel_modules.yml
  github/ci/prow-arm-workloads/roles/bootstrap/tasks/main.yml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Labels: size/XL, approved, lgtm, dco-signoff: yes

#1807 NMO: build and push bundle, index and must-gather images
  github/ci/prow-deploy/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-postsubmits.yaml
Labels: size/XS, approved, dco-signoff: yes

#1808 Add Or Raz to org members
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1810 [HCO] Deprecating k8s-1.19 lane for release-1.5
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.5.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1805 Fix presubmit and periodic TARGET value for k8s-1.23
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1812 Reduce the scope of cgroups v2 periodic job
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1806 Make check-provision required for 1.23
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1767 Bump kubespray in prow-performance deployment jobs.
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1809 Updated infra docs to include external clusters
  docs/infra-layout.svg
  docs/infrastructure-components.md
Labels: size/S, approved, lgtm, dco-signoff: yes

#1814 Always run cgroups v2 presubmit job
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1802 k8s-1.22-ipv6, network: Add kubevirt presubmit job
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1815 Bump capik job to golang 1.17
  github/ci/prow-deploy/files/jobs/kubernetes-sigs/cluster-api-provider-kubevirt/cluster-api-provider-kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1817 k8s-1.22-ipv6: Make the lane mandatory
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes
