Repository kubevirt/project-infra, pull requests merged in 2021-06, with the labels that each got.

#1263 Reduce memory requests for e2e jobs
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.40.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.41.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1268 Authenticate to gcloud to perform testgrid config upload
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/testgrid/hack/common.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1195 Switch CDI to k8s 1.19/1.20
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits-1.28.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1267 libguestfs-appliance: periodic: notify by email on failure
  github/ci/prow-deploy/files/jobs/kubevirt/libguestfs-appliance/libguestfs-appliance-periodics.yaml
  github/ci/testgrid/gen-config.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#1281 Deploy secret for Windows Sysprep testing
  github/ci/prow-deploy/kustom/overlays/workloads-production/kustomization.yaml
  github/ci/prow-deploy/tasks/secrets.yml
  github/ci/prow-deploy/vars/kubevirtci-testing/secrets.yml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1277 Fix testgrid config upload and simplify update workflow
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/testgrid/config.yaml
  github/ci/testgrid/default.yaml
  github/ci/testgrid/hack/check.sh
  github/ci/testgrid/hack/common.sh
  github/ci/testgrid/hack/update.sh
  github/ci/testgrid/hack/upload.sh
Labels: approved, dco-signoff: yes, lgtm, size/XL

#1283 Add new k8s-1.20-hpp-istio (Istio deployed) lane to CDI
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1284 Add a temporary lane to test regex for ignoring documentation changes
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1282 Fix project_infra_root for workloads-production overlay
  github/ci/prow-deploy/vars/workloads-production/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1286 knmstate: Branch protection for release-0.37
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1287 publish latest-version.txt
  github/ci/prow-deploy/files/jobs/kubevirt/libguestfs-appliance/libguestfs-appliance-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1289 publish libguestfs appliance only on new versions
  github/ci/prow-deploy/files/jobs/kubevirt/libguestfs-appliance/libguestfs-appliance-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1290 Add ingress controller to prow-workloads
  github/ci/prow-deploy/kustom/overlays/workloads-production/kustomization.yaml
  github/ci/prow-deploy/kustom/overlays/workloads-production/resources/ingress-controller.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#1271 Added presubmit to check for unassigned tests
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1299 Move kubevirtci jobs to prow-workloads
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1296 Set pushgateway resources
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/kustomization.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/pushgateway_deployment.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1300 Add push to latest on post submit of main for CDI
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1288 Remove pull-kubevirt-e2e-k8s-1.19 lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1252 Prow workloads bootstrap automation
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-workloads/bootstrap.yml
  github/ci/prow-workloads/hack/bootstrap.sh
  github/ci/prow-workloads/hack/common.sh
  github/ci/prow-workloads/hack/deploy.sh
  github/ci/prow-workloads/roles/bootstrap/tasks/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1292 Add prow-workloads metrics ingress
  github/ci/services/prometheus-stack/manifests/stack/production-e2e-workloads/metrics-ingress.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1291 Deploy cert-manager in prow-workloads
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/services/cert-manager/BUILD.bazel
  github/ci/services/cert-manager/overlays/testing-issuers/cluster-issuer.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1302 Add required secrets to prow-workloads cluster
  github/ci/prow-deploy/kustom/overlays/workloads-production/kustomization.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1301 Add kubevirt/containerized-data-importer presubmits to testgrid
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
  github/ci/testgrid/gen-config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1306 Prevent slack reports on periodic lanes that run quarantined tests
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1304 Run SR-IOV job on phx-prow
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1308 asking to be added to approvers list
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1307 Update yasspeller dictionary file
  images/yaspeller/.yaspeller.json
Labels: approved, dco-signoff: yes, lgtm, size/M

#1309 Bump builder image in kubevirtci bump job for new pr-creator
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1314 Fix image for job that bumps kubevirtci on kubevirt
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1295 Add kubevirt e2e presubmit requirer
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  hack/git-pr.sh
  robots/cmd/kubevirt-presubmit-requirer/BUILD.bazel
  robots/cmd/kubevirt-presubmit-requirer/main.go
  robots/cmd/kubevirt-presubmit-requirer/main_test.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#1313 Set default branch to main
  github/ci/prow-deploy/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-postsubmits.yaml
  github/ci/prow-deploy/files/orgs.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1315 Set default branch for kubevirtci to main
  github/ci/prow-deploy/files/jobs/kubevirt/common-templates/common-templates-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow-deploy/files/orgs.yaml
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1318 Continuous Deployment of Prow components
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1317 Update OVS CNI branch to main
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1322 Knmstate release 0.43
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.43.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1321 Remove Istio focus from k8s-1.20-hpp-istio CDI lane
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1323 Update to yaspeller dictionary file
  images/yaspeller/.yaspeller.json
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1324 knmstate-jobs-release-0.47
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.47.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1325 knmstate-0.47-fix-branches
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.47.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1326 HCO: add lane for 1.20
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1329 Fix wrong image for HCO 1.20 lane
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1316 Changes to deploy Thanos components
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/services/prometheus-stack/BUILD.bazel
  github/ci/services/prometheus-stack/README.md
  github/ci/services/prometheus-stack/hack/deploy.sh
  github/ci/services/prometheus-stack/manifests/stack/common/kube-prometheus-stack.yaml
  github/ci/services/prometheus-stack/manifests/stack/common/node-exporter.yaml
  github/ci/services/prometheus-stack/manifests/stack/production-control-plane/alertmanager.yaml
  github/ci/services/prometheus-stack/manifests/stack/production-control-plane/grafana.yaml
  github/ci/services/prometheus-stack/manifests/stack/production-control-plane/thanos.yaml
  github/ci/services/prometheus-stack/manifests/stack/production-e2e-workloads/metrics-ingress.yaml
  github/ci/services/prometheus-stack/manifests/stack/production-e2e-workloads/prometheus-storage.yaml
  github/ci/services/prometheus-stack/manifests/stack/production-e2e-workloads/thanos.yaml
  github/ci/services/prometheus-stack/monitoring-stack.png
  github/ci/services/prometheus-stack/patches/production-control-plane/prometheus.yaml
  github/ci/services/prometheus-stack/patches/production-e2e-workloads/prometheus-storage.yaml
  github/ci/services/prometheus-stack/patches/production-e2e-workloads/prometheus.yaml
  github/ci/services/prometheus-stack/secrets/production-control-plane/thanos-objstore-config/.gitkeep
  github/ci/services/prometheus-stack/secrets/production-e2e-workloads/thanos-objstore-config/.gitkeep
Labels: approved, dco-signoff: yes, lgtm, size/XL

#1330 Update autoowners to latest version
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  images/autoowners/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, size/M

#1335 Move jobs running on bare metals to prow-workloads
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits-v0.20.yaml
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits-v0.21.yaml
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits-v0.26.yaml
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits.yaml
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/ovs-cni/ovs-cni-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/ansible-kubevirt-modules/ansible-kubevirt-modules-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/bridge-marker/bridge-marker-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.27.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.39.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.42.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.44.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.53.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/common-templates/common-templates-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits-1.13.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits-1.19.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits-1.28.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/controller-lifecycle-operator-sdk/controller-lifecycle-operator-sdk-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner/hostpath-provisioner-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.2.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.3.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.4.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-2.3.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-2.4.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.13.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.30.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.34.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.36.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.37.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.38.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.39.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.40.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.41.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/macvtap-cni/macvtap-cni-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-presubmits-master.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-presubmits-release-0.7.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-presubmits-release-0.8.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-presubmits-release-0.9.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/vm-import-operator/vm-import-operator-presubmits.yaml
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.15.yaml
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.31.yaml
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.35.yaml
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.37.yaml
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits.yaml
  github/ci/prow-deploy/files/jobs/nmstate/nmstate/nmstate-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1334 kubemacpool, Add kubemacpool postsubmits
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1337 Disable check provision lane for 1.17
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1340 bridge-marker, Add postsubmits
  github/ci/prow-deploy/files/jobs/kubevirt/bridge-marker/bridge-marker-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1343 Fix branch for kubevirtci postsubmit
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1338 Execute prow-deploy-test in phx-prow
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1344 Create new jobs for kind-1.19-sriov provider
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1320 Set default branch for kubevirt/kubevirt to main
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow-deploy/files/orgs.yaml
Labels: dco-signoff: yes, do-not-merge/hold, size/M

#1346 kind-1.19-sriov jobs: Cancel always_run
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1328 Set default branch for project-infra to main
  cni-plugins/sriov-passthrough-cni/README.md
  github/ci/prow-deploy/files/jobs/kubevirt/community/community-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/user-guide/user-guide-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml
  github/ci/prow-deploy/files/orgs.yaml
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/molecule/default/vars/kubevirtci-testing.yml
  github/ci/testgrid/README.md
Labels: dco-signoff: yes, do-not-merge/hold, size/M

#1353 bridge-marker, postsubmits, Fix typo
  github/ci/prow-deploy/files/jobs/kubevirt/bridge-marker/bridge-marker-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1341 Fix prow-deploy test
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/prow-deploy/molecule/default/cleanup.yml
  github/ci/prow-deploy/molecule/default/collect.yml
  github/ci/prow-deploy/molecule/default/molecule.yml
  github/ci/prow-deploy/molecule/default/prepare.yml
  github/ci/prow-deploy/molecule/default/vars/kubevirtci-testing.yml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1342 kubevirt: Avoid using k8s-1.17 lanes for ceph, make 1.20 ceph lane mandatory
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1352 ovs-cni, Add postsubmits
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/ovs-cni/ovs-cni-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1339 Include openvswitch kernel module in prow-workloads node bootstrap
  github/ci/prow-workloads/roles/bootstrap/tasks/additional_kernel_modules.yml
  github/ci/prow-workloads/roles/bootstrap/tasks/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1350 Bump kind in prow-deploy file
  images/prow-deploy/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1357 Set kubevirt builder image to tagged version
  github/ci/prow-deploy/files/jobs/kubevirt/community/community-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1358 Add lanes for kubevirt release 0.42 branch
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.42.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#1351 Updates release tool to use main as default branch
  external-plugins/release-blocker/server.go
  releng/release-tool/release-tool.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#1303 Enable reporting for kubevirt release jobs
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1348 Set cpu requests for docker-mirror-proxy
  github/ci/prow-deploy/kustom/components/docker-mirror-proxy/base/resources/deployment.yaml
  github/ci/prow-deploy/kustom/components/docker-mirror-proxy/hostpath/patches/JsonRFC6902/deployment.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1360 Point baseref for kubevirtci minorversion-updater to main
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1359 Set check-up-kind-1.19-sriov as voting lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1362 Remove check-unassigned-tests lane for 0.42
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.42.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1361 Set pull-kubevirt-e2e-kind-1.19-sriov as voting lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1368 Add lgtm,approved labels on release tool config forks
  releng/release-tool/Dockerfile.release-tool-base
  releng/release-tool/release-tool.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1365 Revert "Run all remaining storage and networking tests with cgroupv2"
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1367 Register presubmit for bridge-marker 0.6
  github/ci/prow-deploy/files/jobs/kubevirt/bridge-marker/bridge-marker-presubmits-0.6.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1370 Drop separate rook-ceph lanes
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1371 Drop check-provision lanes for k8s 1.18 and lower
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1376 Move remaining SR-IOV jobs to prow-workloads
  cni-plugins/sriov-passthrough-cni/deploy/multus-cni.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.30.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.34.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.36.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.37.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.38.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.39.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.40.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.41.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
  github/ci/prow-deploy/kustom/overlays/workloads-production/kustomization.yaml
  github/ci/prow-deploy/kustom/overlays/workloads-production/resources/multus-cni.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1366 Add presubmit job for stable OVS CNI 0.19
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/ovs-cni/ovs-cni-presubmits-0.19.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1381 Make sure to use Python3 in prow-deploy
  github/ci/prow-deploy/molecule/default/vars/kubevirtci-testing.yml
  github/ci/prow-deploy/tasks/deploy.yml
  github/ci/prow-deploy/vars/ibmcloud-production/main.yml
  github/ci/prow-deploy/vars/workloads-production/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1372 Update SR-IOV periodic
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1384 terraform-provider-kubevirt: Add the repo to triggers section
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1385 terraform-provider-kubevirt: Add the repo to queries section in prow config
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1356 Add dominikholler to org members
  github/ci/prow-deploy/files/orgs.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#1390 Set k8s-1.20-hpp-istio CDI lane to always_run=true
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1386 Increase Prometheus persistent volume size
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/services/prometheus-stack/manifests/stack/common/kube-prometheus-stack.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1391 Website ci
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt.github.io/kubevirt-github-io-postsubmits.yaml
  images/ruby/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, size/M

#1393 Update branch for repo config, move jobs to ibm cluster
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt.github.io/kubevirt-github-io-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt.github.io/kubevirt-github-io-presubmits.yaml
  github/ci/prow-deploy/files/orgs.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1394 Update Prow urls in ci-search flags
  github/ci/services/ci-search/patches/statefulset.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1395 Fix branch-protector for CDI and CNAO
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1396 Remove experimental lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1369 Set KUBEVIRT_E2E_RUN_ALL_SUITES on periodic sig kubevirt jobs
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1398 kubevirtci k8s-x.yy presubmits, Increase max_concurrency to 2
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS
