Repository kubevirt/project-infra, pull requests merged in 2021-08, with the labels that each got.

#1489 openshift-python-wrapper remove release-note plugin
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1490 Remove openshift-python-wrapper from prow
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1476 Add daily job to run performance density test
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1492 vGPU lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1488 Add CI maintainer membership doc
  OWNERS_ALIASES
  docs/membership-policy.md
Labels: size/M, approved, lgtm, dco-signoff: yes

#1498 Remove rhcos-slb project
  github/ci/prow-deploy/files/jobs/RHsyseng/rhcos-slb/rhcos-slb-presubmits.yaml
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1496 Add sanity and k8s external storage e2e test lane for hostpath provisioner CSI plugin
  github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner/hostpath-provisioner-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1501 Fix path to script in hpp k8s e2e storage job
  github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner/hostpath-provisioner-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1485 Release configs for kubevirt/kubevirt release branch release-0.44
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.44.yaml
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#1487 Add document on how to add CI build clusters
  docs/how-to-add-a-prow-cluster.md
Labels: size/M, approved, lgtm, dco-signoff: yes

#1499 Fix python toolchain definition for Bazel.
  BUILD.bazel
  WORKSPACE
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1473 Include local manifests in bump-prow script
  github/ci/prow-deploy/kustom/base/manifests/local/cherrypicker_deployment.yaml
  hack/bump-prow.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1483 Set the number of kept packages to 2 in workloads cluster nodes
  github/ci/prow-workloads/roles/bootstrap/tasks/main.yml
Labels: size/S, approved, lgtm, dco-signoff: yes

#1477 Do not create HMAC secret
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/kustomization.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirtci-testing/resources/hmac.yaml
  github/ci/prow-deploy/molecule/default/prepare.yml
  github/ci/prow-deploy/tasks/secrets.yml
Labels: size/S, approved, lgtm, dco-signoff: yes

#1495 Do not send slack notifications for batch jobs
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1481 Add infrastructure overview doc
  README.md
  docs/infra-layout.svg
  docs/infrastructure-components.md
Labels: size/XL, approved, lgtm, dco-signoff: yes

#1505 HCO: add 1.21 lane
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1512 HCO: Add tests for the new release-1.5 branch
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.5.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1509 cnao, Add stable lane release-0.58
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.58.yaml
Labels: approved, lgtm

#1508 kubemacpool, Add stable lane release-v0.31
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits-v0.31.yaml
Labels: approved, lgtm

#1514 Change check-provision job and automation to use prow-workloads
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
  robots/cmd/kubevirtci-presubmit-creator/main.go
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1513 Remove slack reporting for kubevirt cgroupsv2 periodic
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1518 Update flakefinder to latest version
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-periodics.yaml
  hack/update-jobs-with-latest-image.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#1521 Make hpp sanity and k8s-storage lane mandatory and gating
  github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner/hostpath-provisioner-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1504 Configuration fixes of KubeVirt Velero Plugin's CI.
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-velero-plugin/kubevirt-velero-plugin-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1519 Make the vGPU lane mandatory
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1520 Make the kubevirt sig-storage 1.19 and 1.20 lanes optional
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1526 Remove cgroupsv2 periodic
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1527 Update ignored files to make harder to leak secrets
  .gitignore
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1529 Add NMO release-0.10, fix release
  github/ci/prow-deploy/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-presubmits-release-0.10.yaml
Labels: size/M, approved, dco-signoff: yes

#1530 Fixing configuration of the functional tests cluster
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-velero-plugin/kubevirt-velero-plugin-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#1511 Add periodic job, code and simple test for kubevirt-job-copier
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  robots/cmd/kubevirt-job-copier/BUILD.bazel
  robots/cmd/kubevirt-job-copier/main.go
  robots/cmd/kubevirt-job-copier/main_test.go
Labels: size/XL, approved, lgtm, dco-signoff: yes

#1531 Add brybacki to maintainers of KubeVirt Velero plugin
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1524 periodic-kubevirtci-bump-kubevirt, Add what changed info to automatic bumps
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
  hack/git-pr.sh
Labels: size/S, approved, lgtm, dco-signoff: yes
