Repository kubevirt/project-infra, pull requests merged in 2021-04, with the labels that each got.

#1001 Update dictionary file
  images/yaspeller/.yaspeller.json
Labels: approved, dco-signoff: yes, lgtm, size/M

#1109 Update to yaspeller dictionary
  images/yaspeller/.yaspeller.json
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1084 sriov, presubmit, Remove redundant trap
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1113 sriov, periodics, Remove redundant trap
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1111 Change the periodic job to point to the master branch of common-templates project
  github/ci/prow-deploy/files/jobs/kubevirt/common-templates/common-templates-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1112 Run some quarantined tests with in-memory etcd
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1108 Release configs for kubevirt/kubevirt release branch release-0.40
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.40.yaml
Labels: dco-signoff: yes, size/XL

#1081 sig-network, Make sig-network job mandatory and always run
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1119 remove unused overlay
  github/ci/services/prometheus-stack/overlays/testing/cluster-issuer.yaml
Labels: dco-signoff: yes, size/S

#1120 update ci-search image
  github/ci/services/ci-search/patches/statefulset.yaml
Labels: dco-signoff: yes, size/XS

#1121 Add new k8s 1.19 and 1.20 lanes to CDI
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1106 sig-storage, enable to always run
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1122 sig-network, presubmit, Update env var style
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1124 Fix push-release-kubevirt-tag quay login
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1107 Add job to bump kubevirtci on kubevirt after new release
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1125 Remove push kubevirt images job
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1130 Change kubevirtci autobump job for kubevirt to periodic
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1123 Create k6t periodic lanes for k8s-1.20
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1126 Update kubevirt RPM dependencies once a week
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1131 Revert running etcd in-memory
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1136 Remove virtblocks job
  github/ci/prow-deploy/files/jobs/virtblocks/virtblocks/OWNERS
  github/ci/prow-deploy/files/jobs/virtblocks/virtblocks/virtblocks-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1132 Add optional arm crosscompile build presubmit
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1137 move to always use new rook/ceph after trying it out
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1110 Added prow-workloads overlay and deployment job
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/prow-deploy/hack/deploy.sh
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/kustomization.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirtci-testing/kustomization.yaml
  github/ci/prow-deploy/kustom/overlays/workloads-production/.gitignore
  github/ci/prow-deploy/kustom/overlays/workloads-production/kustomization.yaml
  github/ci/prow-deploy/kustom/overlays/workloads-production/patches/JsonRFC6902/prow-jobs-namespace.yaml
  github/ci/prow-deploy/kustom/overlays/workloads-production/resources/bootstrap.yaml
  github/ci/prow-deploy/tasks/deploy.yml
  github/ci/prow-deploy/tasks/main.yml
  github/ci/prow-deploy/tasks/secrets.yml
  github/ci/prow-deploy/vars/ibmcloud-production/main.yml
  github/ci/prow-deploy/vars/kubevirtci-testing/secrets.yml
  github/ci/prow-deploy/vars/workloads-production/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1133 Use semver regex to trigger job on tag pushes
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1143 Make the arm cross compile job always run
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1134 Add autoapprove for kubevirt-bot "uploader" PRs
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1140 issues/1139...Consolidate kubevirt.github.io files for disk img builds
  images/kubevirt-kubevirt.github.io/Gemfile
  images/kubevirt-kubevirt.github.io/Rakefile
  images/kubevirt-kubevirt.github.io/_config.yml
  images/kubevirt-kubevirt.github.io/check_selectors.js
  images/kubevirt-kubevirt.github.io/kubevirt_dev_t.te
  images/markdownlint/markdownlint.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1145 Promote k6t 1.20 sig-net presubmit lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1146 kubevirtci, postsubmit, Add docker proxy
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1148 Add provision jobs for k8s-1.21
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1128 Add a periodic job to build the latest CentOS container disk image
  github/ci/prow-deploy/files/jobs/kubevirt/common-templates/common-templates-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1150 Make arm64 crosscompile presubmit required
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1153 Add presubmit job to test plugins
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1142 Remove env variable from sig-compute lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  robots/cmd/flake-issue-creator/cluster_failure_test.go
  robots/cmd/flake-issue-creator/flake_issue_test.go
  robots/cmd/flake-issue-creator/issue_test.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#1154 Enable 1.20-sig-sorage presubmit
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1151 Added kubeconfig to crier options
  github/ci/prow/templates/crier-deployment.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1152 Fix rule attr nil dereference
  plugins/cmd/uploader/uploader.go
  plugins/mirror/bazel.go
  plugins/mirror/bazel_test.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#1158 Declare cluster
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-periodics.yaml
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/ansible-kubevirt-modules/ansible-kubevirt-modules-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/bridge-marker/bridge-marker-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.27.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.39.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.42.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.44.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/common-templates/common-templates-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits-1.13.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits-1.19.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/controller-lifecycle-operator-sdk/controller-lifecycle-operator-sdk-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner/hostpath-provisioner-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.2.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.3.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-2.3.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-2.4.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-tutorial/kubevirt-tutorial-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-tutorial/kubevirt-tutorial-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt.github.io/kubevirt-github-io-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt.github.io/kubevirt-github-io-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.13.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.30.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.34.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.36.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.37.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.38.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.39.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.40.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/macvtap-cni/macvtap-cni-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/macvtap-cni/macvtap-cni-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-presubmits-master.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-presubmits-release-0.7.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-presubmits-release-0.8.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/ovs-cni/ovs-cni-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/user-guide/user-guide-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/vm-import-operator/vm-import-operator-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1161 Temporarily disable docker proxy for prow-workloads lanes
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1164 Add jobs/nmstate/nmstate OWNERS
  github/ci/prow-deploy/files/jobs/nmstate/nmstate/OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/S

#1163 Declare cluster for nmstate presubmit
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-periodics.yaml
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.15.yaml
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.31.yaml
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.35.yaml
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.37.yaml
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits.yaml
  github/ci/prow-deploy/files/jobs/nmstate/nmstate/nmstate-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1156 Add 1.19-sig-compute presubmit
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1157 Add periodics to report
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-periodics.yaml
  robots/cmd/flakefinder/main.go
  robots/cmd/flakefinder/report.go
  robots/pkg/flakefinder/downloader.go
  robots/pkg/flakefinder/flakefinder.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#1165 Remove status filter as PR never reaches success
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1166 Set 12h for autoapprove
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1171 Revert memory increase for e2e periodic
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1168 Several Prow deployment fixes
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/deck_deployment.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1170 Update monitoring stack for new prow deployment
  github/ci/prow-deploy/kustom/base/manifests/local/greenhouse-service.yaml
  github/ci/services/prometheus-stack/BUILD.bazel
  github/ci/services/prometheus-stack/hack/deploy.sh
  github/ci/services/prometheus-stack/manifests/service-monitors/greenhouse.yaml
  github/ci/services/prometheus-stack/manifests/service-monitors/namespace.yaml
  github/ci/services/prometheus-stack/manifests/service-monitors/pushgateway.yaml
  github/ci/services/prometheus-stack/manifests/stack/grafana.yaml
  github/ci/services/prometheus-stack/manifests/stack/ingress.yaml
  github/ci/services/prometheus-stack/manifests/stack/kube-prometheus-stack.yaml
  github/ci/services/prometheus-stack/manifests/stack/loki-stack.yaml
  github/ci/services/prometheus-stack/manifests/stack/namespace.yaml
  github/ci/services/prometheus-stack/manifests/stack/node-exporter.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1173 Update default Prow config
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/yq_scripts/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1174 Fix wrong URL in Prow config
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1167 Flakefinder periodics: Skip job data outside report window for periodics
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-periodics.yaml
  robots/pkg/flakefinder/downloader.go
  robots/pkg/flakefinder/flakefinder.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#1176 Modify CentOS Job to specify the exact stable CentOS version
  github/ci/prow-deploy/files/jobs/kubevirt/common-templates/common-templates-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1175 Fix rehearse deployment
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/prow-rehearse-deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/prow-rehearse-rbac.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/prow-rehearse-deployment.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1178 Integrate kubevirt/libguestfs-appliance
  github/ci/prow-deploy/files/orgs.yaml
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1179 Increase docker proxy timeouts
  github/ci/prow-deploy/kustom/base/manifests/local/docker-mirror-proxy_deployment.yaml
  github/ci/prow/templates/mirror-proxy.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1181 HCO: add new release-1.4 branch
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.4.yaml
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1182 Update the branch for the common-templates project
  github/ci/prow-deploy/files/jobs/kubevirt/common-templates/common-templates-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1177 Add aditional jobs to run non-root implementation
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1180 Create presubmit job for kubevirt/libguestfs-appliance
  github/ci/prow-deploy/files/jobs/kubevirt/libguestfs-appliance/libguestfs-appliance-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S
