Repository kubevirt/project-infra, pull requests merged in 2021-01, with the labels that each got.

#803 Change flakefinder presubmit to robots presubmit
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#802 Use autoowners signoff
  external-plugins/release-blocker/Makefile
  external-plugins/release-blocker/update-job-with-latest-release-blocker-image.sh
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  hack/update-jobs-with-latest-image.sh
  images/autoowners/build_and_push_from_local.sh
  robots/flakefinder/Makefile
  robots/flakefinder/update-jobs-with-latest-flakefinder-image.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#804 Bump plank resources in automated Prow deploy.
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/kustomization.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/plank_deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/StrategicMerge/plank_deployment_replicas.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirtci-testing/kustomization.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirtci-testing/patches/JsonRFC6902/plank_deployment.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirtci-testing/patches/StrategicMerge/plank_deployment_replicas.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#794 ci-search deployment
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/services/ci-search/BUILD.bazel
  github/ci/services/ci-search/e2e/BUILD.bazel
  github/ci/services/ci-search/e2e/e2e_test.go
  github/ci/services/ci-search/hack/deploy.sh
  github/ci/services/ci-search/manifests/full.yaml
  github/ci/services/ci-search/manifests/ingress.yaml
  github/ci/services/ci-search/overlays/testing/cluster-issuer.yaml
  github/ci/services/ci-search/patches/statefulset.yaml
  github/ci/services/ci-search/secrets/production/bugzilla-credentials/.gitkeep
  github/ci/services/ci-search/secrets/testing/bugzilla-credentials/api
  github/ci/services/common/k8s/cmd/wait/main.go
  github/ci/services/common/k8s/pkg/client/client.go
  github/ci/services/common/k8s/pkg/portforwarder/BUILD.bazel
  github/ci/services/common/k8s/pkg/portforwarder/portforwarder.go
  github/ci/services/common/k8s/pkg/wait/wait.go
  go.sum
  vendor/github.com/docker/spdystream/BUILD.bazel
  vendor/github.com/docker/spdystream/CONTRIBUTING.md
  vendor/github.com/docker/spdystream/LICENSE
  vendor/github.com/docker/spdystream/LICENSE.docs
  vendor/github.com/docker/spdystream/MAINTAINERS
  vendor/github.com/docker/spdystream/README.md
  vendor/github.com/docker/spdystream/connection.go
  vendor/github.com/docker/spdystream/handlers.go
  vendor/github.com/docker/spdystream/priority.go
  vendor/github.com/docker/spdystream/spdy/BUILD.bazel
  vendor/github.com/docker/spdystream/spdy/dictionary.go
  vendor/github.com/docker/spdystream/spdy/read.go
  vendor/github.com/docker/spdystream/spdy/types.go
  vendor/github.com/docker/spdystream/spdy/write.go
  vendor/github.com/docker/spdystream/stream.go
  vendor/github.com/docker/spdystream/utils.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/BUILD.bazel
  vendor/k8s.io/apimachinery/pkg/util/httpstream/doc.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/httpstream.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/BUILD.bazel
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/connection.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/upgrade.go
  vendor/k8s.io/apimachinery/third_party/forked/golang/netutil/BUILD.bazel
  vendor/k8s.io/apimachinery/third_party/forked/golang/netutil/addr.go
  vendor/k8s.io/client-go/tools/portforward/BUILD.bazel
  vendor/k8s.io/client-go/tools/portforward/doc.go
  vendor/k8s.io/client-go/tools/portforward/portforward.go
  vendor/k8s.io/client-go/transport/spdy/BUILD.bazel
  vendor/k8s.io/client-go/transport/spdy/spdy.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#806 Fix nodeSelector declaration for presubmit jobs
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#808 Fix ci-search-deploy-test job
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#807 cnao, Add lanes for new branch release-0.44
  github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.44.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#813 prow-deploy: bump kubevirtci tag
  github/ci/prow-deploy/molecule/default/collect_resource.yml
  github/ci/prow-deploy/molecule/default/vars/kubevirtci-testing.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#815 Remove release folder before updating
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#811 cnao, Add unit test job for release and stable jobs
  github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.42.yaml
  github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.44.yaml
  github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#816 Add ci-search readme
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/services/ci-search/README.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#820 Add testgrid configuration
  github/ci/prow/files/config.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#827 Fix autoowners periodic job
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  images/autoowners/Dockerfile
  images/autoowners/build_and_push_from_local.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#828 Fix ci-search deployment
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#831 Use k8s-prow git image as base
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  images/autoowners/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, size/S

#834 Add bazelisk to the bootstrap image
  images/bootstrap/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#836 ci-search: set fs group for mounted volumes
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/services/ci-search/patches/statefulset.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#837 cert-manager readme
  github/ci/services/cert-manager/README.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#840 Create jobs for kubevirt-userguide image
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#841 update URLs to *.ci.kubevirt.io
  github/ci/prow-deploy/kustom/base/manifests/local/nginx-ingress.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/yq_scripts/config.yaml
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/services/ci-search/manifests/ingress.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#842 Removed testgrid annotations from non-compatible jobs.
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#843 sriov lanes, Add podAntiAffinity of sriov-pod-multi
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.20.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.23.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.24.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.26.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.29.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.30.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.31.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.32.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.33.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.34.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.35.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.36.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#844 Fix kubevirt e2e periodics
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#846 Add presubmit for rehearse plugin
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#789 Publish kubevirtci images to quay
  github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#848 Create jobs for sigs update
  github/ci/prow/files/config.yaml
  github/ci/prow/files/jobs/kubevirt/community/community-postsubmits.yaml
  github/ci/prow/files/jobs/kubevirt/community/community-presubmits.yaml
  github/ci/prow/files/labels.yaml
  github/ci/prow/files/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#839 Update to add repo user-guide to CI automation
  github/ci/prow/files/config.yaml
  github/ci/prow/files/jobs/kubevirt/user-guide/user-guide-periodics.yaml
  github/ci/prow/files/jobs/kubevirt/user-guide/user-guide-presubmits.yaml
  github/ci/prow/files/labels.yaml
  github/ci/prow/files/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#857 ci-search: add job-uri-prefix
  github/ci/services/ci-search/patches/statefulset.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#858 ci-search: set index-bucket to kubevirt-prow
  github/ci/services/ci-search/patches/statefulset.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#838 Update to user-guide Dockerfile and spelling dictionary
  images/kubevirt-userguide/Dockerfile
  images/yaspeller/.yaspeller.json
Labels: approved, dco-signoff: yes, lgtm, size/M

#849 Update to set correct python image for user-guide builds
  github/ci/prow/files/jobs/kubevirt/user-guide/user-guide-periodics.yaml
  github/ci/prow/files/jobs/kubevirt/user-guide/user-guide-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#847 Add testgrid config and transfigure jobs
  github/ci/prow/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-periodics.yaml
  github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
  github/ci/prow/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-postsubmits.yaml
  github/ci/prow/files/jobs/kubevirt/community/community-postsubmits.yaml
  github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
  github/ci/prow/files/jobs/kubevirt/csi-driver/csi-driver-postsubmits.yaml
  github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml
  github/ci/prow/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-postsubmits.yaml
  github/ci/prow/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-periodics.yaml
  github/ci/prow/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-postsubmits.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt-tutorial/kubevirt-tutorial-periodics.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt.github.io/kubevirt-github-io-periodics.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
  github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
  github/ci/prow/files/jobs/kubevirt/macvtap-cni/macvtap-cni-postsubmits.yaml
  github/ci/prow/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-postsubmits.yaml
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/prow/files/jobs/kubevirt/user-guide/user-guide-periodics.yaml
  github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-periodics.yaml
  github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml
  github/ci/testgrid/README.md
  github/ci/testgrid/gen-config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#863 Add jobs for kubernetes-nmstate release-0.37
  github/ci/prow/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.37.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#865 user-guide: Update to add htmlproofer plugin and dependencies
  images/kubevirt-userguide/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, size/S

#864 Add missing gh token to testgrid config upload job
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#823 sriov cni, Add NetworkAttachmentDefinition missing namespace
  cni-plugins/sriov-passthrough-cni/deploy/multus-cni.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#870 Use a base image with the right config-forker
  WORKSPACE
  releng/release-tool/Dockerfile.release-tool-base
Labels: approved, dco-signoff: yes, lgtm, size/XS

#872 jobconfig fork for release-0.37
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.37.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XL

#873 sriov release 0.37, Add sriov-poc-multi podAntiAffinity
  github/ci/prow/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.37.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#866 user-guide: Fix python environment
  github/ci/prow/files/jobs/kubevirt/user-guide/user-guide-periodics.yaml
  github/ci/prow/files/jobs/kubevirt/user-guide/user-guide-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#874 Add missing options to transfigure upload call
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#876 Fix user-guide jobs
  github/ci/prow/files/jobs/kubevirt/user-guide/user-guide-periodics.yaml
  github/ci/prow/files/jobs/kubevirt/user-guide/user-guide-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#877 user-guide: Fix venv path
  github/ci/prow/files/jobs/kubevirt/user-guide/user-guide-periodics.yaml
  github/ci/prow/files/jobs/kubevirt/user-guide/user-guide-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#878 Update grafana
  github/ci/prometheus/templates/grafana.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#879 Minimalistic tide dashboard
  github/ci/prometheus/templates/dashboards.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#860 Add peribolos configuration and job
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow/files/orgs.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XL

#881 [HCO] Require Sanity Checks on PR to master
  github/ci/prow/files/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#882 Make peribolos job update org configuration
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#883 Create presubmit for kubevirt orgs config changes
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#880 Cache bazel 4.0 in bootstrap image
  images/bootstrap/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#885 Update OWNERS to reflect current situation
  OWNERS
  github/ci/OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/S

#886 Remove org admin
  github/ci/prow/files/orgs.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#887 Add label definition for dco-signoff
  github/ci/prow/files/labels.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#888 Add some other missing labels to default section
  github/ci/prow/files/labels.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#889 Change release notes to refer to quay.io
  releng/release-tool/release-tool.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#890 Add separate CDI destructive lane for destructive tests
  github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#891 Remove duplicate kubevirt/containerized-data-importer
  github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#894 A new fedora based bootstrap image
  images/bootstrap/Dockerfile
  images/bootstrap/create_bazel_cache_rcs.sh
  images/bootstrap/entrypoint.sh
  images/bootstrap/runner.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#895 Release bootstrap image on quay.io
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#898 Fix labels by removing the duplicates
  github/ci/prow/files/labels.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#896 Add presubmit to check labels.yaml
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#901 Configure docker userland binary paths
  images/bootstrap/runner.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#871 Periodically Check for a new Fedora version and create a new CDI
  github/ci/prow/files/jobs/kubevirt/common-templates/common-templates-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#900 Don't use proxy for the bootstrap job for now
  github/ci/prow/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#904 Fix minor bootstrap issues
  images/bootstrap/Dockerfile
  images/bootstrap/create_bazel_cache_rcs.sh
Labels: approved, dco-signoff: yes, lgtm, size/S

#907 Revert #871
  github/ci/prow/files/jobs/kubevirt/common-templates/common-templates-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#902 CDI make the destructive lane required and always run
  github/ci/prow/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#906 user-guide: add branch protection settings, remove superfluous presubmit job
  github/ci/prow/files/config.yaml
  github/ci/prow/files/jobs/kubevirt/user-guide/user-guide-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M
