Repository kubevirt/project-infra, pull requests merged in 2021-10, with the labels that each got.

#1637 Switch hpp operator to use golang container
  github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner-operator/hostpath-provisioner-operator-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner-operator/hostpath-provisioner-operator-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1636 Set KubePodNotReady alert trigger to 90m in prow-workloads
  github/ci/services/prometheus-stack/manifests/rules/common/kubernetes-apps.yaml
  github/ci/services/prometheus-stack/manifests/rules/production-control-plane/kubernetes-apps.yaml
  github/ci/services/prometheus-stack/manifests/rules/production-e2e-workloads/kubernetes-apps.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1642 Remove linter for now
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt.github.io/kubevirt-github-io-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#1641 Rename kubernetes-apps PrometheusRule and rule group for common and cluster use cases
  github/ci/services/prometheus-stack/manifests/rules/common/kubernetes-apps.yaml
  github/ci/services/prometheus-stack/manifests/rules/production-control-plane/kubernetes-apps.yaml
  github/ci/services/prometheus-stack/manifests/rules/production-e2e-workloads/kubernetes-apps.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#1604 Add blackbox-exporter and probe + alert for prow.ci.kubevirt.io
  github/ci/services/prometheus-stack/manifests/rules/production-e2e-workloads/probes.yaml
  github/ci/services/prometheus-stack/manifests/stack/common/kube-prometheus-stack.yaml
  github/ci/services/prometheus-stack/manifests/stack/production-e2e-workloads/blackbox-exporter.yaml
  github/ci/services/prometheus-stack/secrets/production-control-plane/prometheus-stack-kube-prom-prometheus-scrape-confg/additional-scrape-configs.yaml
  github/ci/services/prometheus-stack/secrets/production-e2e-workloads/prometheus-stack-kube-prom-prometheus-scrape-confg/additional-scrape-configs.yaml
  github/ci/services/prometheus-stack/secrets/testing/prometheus-stack-kube-prom-prometheus-scrape-confg/additional-scrape-configs.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#1627 Add vm-image-builder image and jobs to handle it
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  images/vm-image-builder/Dockerfile
Labels: size/L, approved, lgtm, dco-signoff: yes

#1645 Move hpp(-operator) unit tests to phx-prow cluster
  github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner-operator/hostpath-provisioner-operator-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner/hostpath-provisioner-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1646 Skip release branches for 1.22 jobs
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#1620 Symlink prow-deploy requirements.txt to the file used on CI
  github/ci/prow-deploy/requirements.txt
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1644 Set default branch to main for cdi-api-reference repo
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1648 Bump bootstrap image used in nmstate publish job
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1647 Add test for copying branch rules on presubmits
  robots/pkg/kubevirt/cmd/copy/jobs.go
  robots/pkg/kubevirt/cmd/copy/jobs_test.go
Labels: size/L, approved, lgtm, dco-signoff: yes

#1650 NMO: Remove e2e from presubmits, clean postsubmit
  github/ci/prow-deploy/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-presubmits-master.yaml
Labels: size/M, dco-signoff: yes

#1651 Add kubot
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/services/common/k8s/pkg/wait/wait.go
  github/ci/services/kubot/BUILD.bazel
  github/ci/services/kubot/README.md
  github/ci/services/kubot/e2e/BUILD.bazel
  github/ci/services/kubot/e2e/e2e_test.go
  github/ci/services/kubot/hack/deploy.sh
  github/ci/services/kubot/manifests/full.yaml
  github/ci/services/kubot/patches/testing/deployment.yaml
  github/ci/services/kubot/secrets/production/kubeconfig/.gitkeep
  github/ci/services/kubot/secrets/production/slack-token/.gitkeep
  images/kubot/Dockerfile
  images/kubot/worker.coffee
Labels: size/L, approved, lgtm, dco-signoff: yes

#1654 Add always run disabler, fix PR branch and selection of releases for delete jobs job
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  robots/cmd/kubevirt/README.md
  robots/pkg/kubevirt/cmd/copy/BUILD.bazel
  robots/pkg/kubevirt/cmd/copy/jobs.go
  robots/pkg/kubevirt/cmd/copy/jobs_test.go
  robots/pkg/kubevirt/cmd/remove/BUILD.bazel
  robots/pkg/kubevirt/cmd/remove/always_run.go
  robots/pkg/kubevirt/cmd/remove/jobs.go
  robots/pkg/kubevirt/cmd/remove/jobs_test.go
  robots/pkg/kubevirt/cmd/remove/remove.go
  robots/pkg/kubevirt/release/BUILD.bazel
  robots/pkg/kubevirt/release/release.go
  robots/pkg/kubevirt/release/release_test.go
Labels: size/L, approved, lgtm, dco-signoff: yes

#1622 Adds new lane for running periodic realtime perf tests
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1664 Manual run of the config-forker from test-infra for 0.46
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.46.yaml
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#1667 add an optional presubmit e2e test on ARM64
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1671 Make the arm presubmit not run always
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1672 Add postsubmit to update testing manifests
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1556 Add nonroot gpu lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1674 (CDI) Add optional lanes to test a transition to newer k8s providers
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#1677 fix missing project-infra error in e2e test on ARM
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1680 Request an API repository for KubeVirt
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#1681 Add machadovilaca as member
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, ok-to-test, approved, lgtm, dco-signoff: yes

#1684 Remove unneded dep from WORKSPACE
  WORKSPACE
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1683 fix missing kubectl-path error
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1702 Perfscale-audit binary is missing from the Perf periodic
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes
