Repository kubevirt/project-infra, pull requests merged in 2021-11, with the labels that each got.

#1708 Add +x to mirror-crio.sh script
  hack/mirror-crio.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1699 Use unprivileged token for prow-deploy tests
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/prow-deploy/hack/test.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#1709 Do not use GIT_ASKPASS for prow-deploy-test
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/prow-deploy/hack/test.sh
  github/ci/prow-deploy/kustom/overlays/workloads-production/kustomization.yaml
  github/ci/prow-deploy/molecule/default/vars/kubevirtci-testing.yml
  github/ci/prow-deploy/tasks/secrets.yml
Labels: size/S, approved, lgtm, dco-signoff: yes

#1701 Fix workloads cluster deployment
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/kustom/components/docker-mirror-proxy/base/resources/deployment.yaml
  github/ci/prow-deploy/kustom/components/docker-mirror-proxy/base/resources/service.yaml
  github/ci/prow-deploy/kustom/components/greenhouse/base/resources/deployment.yaml
  github/ci/prow-deploy/kustom/overlays/workloads-production/resources/ingress-controller.yaml
  github/ci/prow-deploy/kustom/overlays/workloads-production/resources/metrics-server.yaml
  github/ci/prow-deploy/tasks/deploy.yml
Labels: size/S, approved, lgtm, dco-signoff: yes

#1707 periodic-publish-kubevirt-flakefinder-four-weekly-report: Increase timeout to 4h
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1715 HCO: move post submit to prow-workloads
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1716 HCO: add presubmit test to check the test util image before merging the PR
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1713 Make the required switch from 1.19, 1.20 to 1.21, 1.22 in CDI
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits-1.34.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits-1.38.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#1718 HCO: fix wrong image tag for quay.io/kubevirtci/bootstrap
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1719 add new group to allow rerun jobs in HCO
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1714 Add cwilkers to web maintainers
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1720 Make flaky sig-storage lanes optional
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1706 add presubmit job for branch release-0.47
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.47.yaml
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#1723 Make sig-storage presubmit lanes required again
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1724 Update kubevirt.github.io default branch to main
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt.github.io/kubevirt-github-io-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt.github.io/kubevirt-github-io-postsubmits.yaml
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1727 add prow jobs to configure the performance workload cluster
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#1728 Make main the default branch for kubevirt/client-go
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1729 Publish staging code together with the developer release
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#1731 remove runner.sh script from jobs using kubespray image
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1734 Include skopeo in the bootstrap image
  images/bootstrap/Dockerfile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1736 Add yq for managing secrets if not present
  hack/manage-secrets.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1737 testgrid: width compact
  github/ci/testgrid/default.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1725 Update to GitHub website and user-guide repos
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#1732 Integrate kubevirt/containerdisks repo with prow
  github/ci/prow-deploy/files/orgs.yaml
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#1740 Move jobs scheduled on phx-prow to ibm-prow-jobs
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-periodics.yaml
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits-v0.20.yaml
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits-v0.21.yaml
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits-v0.26.yaml
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits-v0.31.yaml
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner-operator/hostpath-provisioner-operator-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner/hostpath-provisioner-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-tutorial/kubevirt-tutorial-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-tutorial/kubevirt-tutorial-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-velero-plugin/kubevirt-velero-plugin-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.34.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.42.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/macvtap-cni/macvtap-cni-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/macvtap-cni/macvtap-cni-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-periodics.yaml
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.15.yaml
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.31.yaml
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.35.yaml
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.37.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#1741 Remove fdupont-redhat from org
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1742 Ensure that go is available for the developer build pusher
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1739 Initial set of jobs for kubevirt/containerdisks
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1745 Add fabiendupont to organization
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, approved, lgtm, needs-ok-to-test, dco-signoff: yes

#1733 Update prometheus' ci-health target
  github/ci/services/prometheus-stack/secrets/production-control-plane/prometheus-stack-kube-prom-prometheus-scrape-confg/additional-scrape-configs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1748 remove nodeSelector leftovers
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1749 Make go available for nightly builds
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1746 Bump bootstrap base image
  images/bootstrap/Dockerfile
Labels: size/S, approved, lgtm, dco-signoff: yes

#1751 Bump the bootstrap image to get a new skopeo version
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1752 Ignore unknown cotexts for nmstate/kubernetes-nmstate
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#1754 knmstate: fix typo
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1755 knmstate: Remove 0.47 future job
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits-0.47.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#1756 HCO remove the requied coverage/coveralls check, to solve a github issue
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1758 We need an absolute askpass path due to directory switching
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1753 Fixes for prow-performance bootstrap and deployment jobs.
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-performance-workloads/bootstrap.yml
  github/ci/prow-performance-workloads/hack/bootstrap.sh
  github/ci/prow-performance-workloads/hack/common.sh
  github/ci/prow-performance-workloads/hack/deploy.sh
  github/ci/prow-performance-workloads/inventory/prow-performance-workloads/README.md
  github/ci/prow-performance-workloads/inventory/prow-performance-workloads/group_vars/all/docker.yml
  github/ci/prow-performance-workloads/inventory/prow-performance-workloads/group_vars/etcd.yml
  github/ci/prow-performance-workloads/inventory/prow-performance-workloads/group_vars/k8s_cluster/addons.yml
  github/ci/prow-performance-workloads/inventory/prow-performance-workloads/group_vars/k8s_cluster/k8s-cluster.yml
  github/ci/prow-performance-workloads/inventory/prow-performance-workloads/group_vars/k8s_cluster/k8s-net-calico.yml
  github/ci/prow-performance-workloads/inventory/prow-performance-workloads/group_vars/kube-proxy.yml
  github/ci/prow-performance-workloads/roles/bootstrap/tasks/control-plane.yml
  github/ci/prow-performance-workloads/roles/bootstrap/tasks/main.yml
  github/ci/prow-performance-workloads/roles/bootstrap/tasks/workers.yml
Labels: size/L, approved, lgtm, dco-signoff: yes

#1744 Fix testgrid tests
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
  github/ci/testgrid/hack/check.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1760 Make 1.19 check-provision optional
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1761 Remove check-provision-k8s-1.19 as k8s-1.19 was removed
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#1763 Add -R for release-note-none
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  hack/git-pr.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#1765 Add orelmisan to the organization
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, ok-to-test, approved, lgtm, dco-signoff: yes

#1771 Rebuild golang image if bootstrap changes
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1766 sriov-1.19, Readd check-up-kind-1.19-sriov lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1772 kubevirt/containerdisks needs golang now
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1773 Add e2e validation job for capik
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-api-provider-kubevirt/OWNERS
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-api-provider-kubevirt/cluster-api-provier-kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1775 Make golang available for capik
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-api-provider-kubevirt/cluster-api-provier-kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1776 Fix bazel call of presubmit-remover
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1774 cnao, unit-tests, Update unit-test lane image
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.42.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.44.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.53.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.58.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#1757 Backport kubevirt release job to release-0.36
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1779 Add Barakmor1 to the community
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, approved, lgtm, needs-ok-to-test, dco-signoff: yes
