Repository kubevirt/project-infra, pull requests merged in 2021-07, with the labels that each got.

#1399 Update the image for cgroupsv2 jobs
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1400 Deploy Prow exporter
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/kustomization.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/prow-exporter-deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/prow-exporter-service.yaml
  github/ci/services/prometheus-stack/BUILD.bazel
  github/ci/services/prometheus-stack/manifests/service-monitors/common/greenhouse.yaml
  github/ci/services/prometheus-stack/manifests/service-monitors/common/namespace.yaml
  github/ci/services/prometheus-stack/manifests/service-monitors/production-control-plane/pushgateway.yaml
  hack/bump-prow.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#1262 Add fossa analysis presubmit manual and postsubmit
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/kustomization.yaml
  github/ci/prow-deploy/kustom/overlays/workloads-production/kustomization.yaml
  github/ci/prow-deploy/tasks/secrets.yml
  github/ci/prow-deploy/vars/kubevirtci-testing/secrets.yml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1364 [DRAFT] add periodics cluster sync test for ARM
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1403 Fix Prow exporter deployment
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/kustomization.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/prow-exporter-deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/prow-exporter-rbac.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/prow-exporter-service.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1404 Add namespace for fossa token
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/kustomization.yaml
  github/ci/prow-deploy/kustom/overlays/workloads-production/kustomization.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1413 Reduce Thanos retention
  github/ci/services/prometheus-stack/manifests/stack/production-control-plane/thanos.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1405 Fix namespaces for secrets in kustomize
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/kustomization.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1412 Bump PFs of SR-IOV nodes to 4
  github/ci/prow-deploy/vars/workloads-production/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1411 Upgrade build system
  .bazelversion
  BUILD.bazel
  WORKSPACE
  external-plugins/rehearse/plugin/BUILD.bazel
  external-plugins/rehearse/plugin/handler/handler.go
  external-plugins/rehearse/plugin/handler/handler_test.go
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/services/cert-manager/BUILD.bazel
  github/ci/services/ci-search/BUILD.bazel
  github/ci/services/kuberhealthy/BUILD.bazel
  github/ci/services/prometheus-stack/BUILD.bazel
  github/ci/services/sippy/BUILD.bazel
  go.mod
  go.sum
  go_third_party.bzl
  releng/release-tool/BUILD.bazel
  robots/cmd/flake-issue-creator/BUILD.bazel
  robots/cmd/kubevirt-presubmit-requirer/BUILD.bazel
  robots/pkg/mock/prow/github/generated_mock_client.go
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#1415 Run uploader for project-infra
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1416 Add periodic nightly release job for ARM64
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1418 Update Prometheus settings
  github/ci/services/prometheus-stack/manifests/stack/common/kube-prometheus-stack.yaml
  github/ci/services/prometheus-stack/patches/production-control-plane/prometheus.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1419 Make fossa presubmit run always
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1406 Update yaspeller dictionary file
  images/yaspeller/.yaspeller.json
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1401 add presubmit job for branch release-0.43
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.43.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#1424 Add cwilkers to members of KubeVirt org
  github/ci/prow-deploy/files/orgs.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#1425 Added joherr/jobbler to members
  github/ci/prow-deploy/files/orgs.yaml
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#1421 Add ci-usage-exporter
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/kustomization.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/ci-usage-exporter-deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/ci-usage-exporter-service.yaml
  github/ci/services/prometheus-stack/manifests/service-monitors/production-control-plane/ci-usage-exporter.yaml
  robots/cmd/ci-usage-exporter/BUILD.bazel
  robots/cmd/ci-usage-exporter/main.go
  robots/pkg/ci-usage-exporter/metrics/BUILD.bazel
  robots/pkg/ci-usage-exporter/metrics/main.go
  robots/pkg/ci-usage-exporter/metrics/metrics_test.go
  robots/pkg/ci-usage-exporter/metrics/resources.go
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#1388 Add KubeVirt Velero plugin repository and team
  github/ci/prow-deploy/files/orgs.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1389 Update non-root lanes to 1.21
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1426 Scrape directly Prow exporter metrics
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/kustomization.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/ci-usage-exporter-service.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/prow-exporter-service.yaml
  github/ci/services/prometheus-stack/manifests/service-monitors/production-control-plane/common.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1427 ssp-operator: change merge_method to 'merge'
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1429 Update deck links
  github/ci/README.md
  robots/cmd/flake-issue-creator/main.go
  robots/cmd/flakefinder/report.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#1430 Added CI utilization dashboard
  github/ci/services/prometheus-stack/manifests/stack/production-control-plane/grafana.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1420 Add Matthew Arnold to kubevirt members.
  github/ci/prow-deploy/files/orgs.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1431 Add local PV for greenhouse in workloads cluster
  github/ci/prow-deploy/kustom/components/greenhouse/hostpath/kustomization.yaml
  github/ci/prow-deploy/kustom/components/greenhouse/hostpath/patches/JsonRFC6902/deployment.yaml
  github/ci/prow-deploy/kustom/components/greenhouse/hostpath/resources/storage.yaml
  github/ci/prow-deploy/kustom/components/greenhouse/pv/kustomization.yaml
  github/ci/prow-deploy/kustom/components/greenhouse/pv/patches/JsonRFC6902/deployment.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1414 Fix cgroupv2 jobs
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1312 Job to verify that go.mod, go.sum and vendor folders are in sync
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1434 Tune greenhouse to not occupy the whole disk
  github/ci/prow-deploy/kustom/components/greenhouse/hostpath/kustomization.yaml
  github/ci/prow-deploy/kustom/components/greenhouse/hostpath/patches/JsonRFC6902/deployment.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1433 Do not run optional lanes on doc changes
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1437 Expose job's always_run and brancher settings
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/ci-usage-exporter-deployment.yaml
  robots/pkg/ci-usage-exporter/metrics/metrics_test.go
  robots/pkg/ci-usage-exporter/metrics/resources.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#1280 Add windows-sysprep lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1440 Revert "Do not run optional lanes on doc changes"
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1441 Fix commenter jobs suddenly failing with q invalid
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1423 rhcos-slb, Adding presubmits lane for main branch
  github/ci/prow-deploy/files/jobs/RHsyseng/rhcos-slb/rhcos-slb-presubmits.yaml
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1443 Add hmac tool to prow deploy image
  images/prow-deploy/Dockerfile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1447 Only deploy Prow on relevant changes
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1445 Update Prometheus settings
  github/ci/services/prometheus-stack/manifests/stack/common/kube-prometheus-stack.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1442 Set base branch to main for flakefinder jobs
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1446 Add configuration for GitHub webhooks reconciliation
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/molecule/default/molecule.yml
  github/ci/prow-deploy/tasks/deploy.yml
  github/ci/prow-deploy/vars/ibmcloud-production/main.yml
  github/ci/prow-deploy/vars/kubevirtci-testing/secrets.yml
  github/ci/prow-deploy/vars/workloads-production/main.yml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1449 Update pull-cdi-unit-test job
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1451 Add remaining repos to managed webhooks configuration
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1452 Remove new lines in retester query
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1457 Increase Prometheus CPU resources in control plane
  github/ci/services/prometheus-stack/patches/production-control-plane/prometheus.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1456 EnsureProviderExists should not touch existing
  robots/pkg/kubevirtci/kubevirtci.go
  robots/pkg/kubevirtci/kubevirtci_test.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1459 Define greenhouse CPU resources
  github/ci/prow-deploy/kustom/components/greenhouse/base/resources/deployment.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1455 Project and CI configuration for KubeVirt Velero plugin
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-velero-plugin/kubevirt-velero-plugin-presubmits.yaml
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1460 Bump test-infra commenter image to restore queries
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  hack/update-jobs-with-latest-image.sh
Labels: approved, dco-signoff: yes, lgtm, size/M

#1293 Require compute and operator for non-root
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1466 Move uploader to robots
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  robots/cmd/uploader/BUILD.bazel
  robots/cmd/uploader/README.md
  robots/cmd/uploader/uploader.go
  robots/pkg/mirror/BUILD.bazel
  robots/pkg/mirror/bazel.go
  robots/pkg/mirror/bazel_test.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#1467 Add RedHatQE/openshift-python-wrapper to project
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1469 Indent lines under plugins section
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#1468 Add RedHatQE/openshift-python-wrapper to managed webhooks
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1471 Make 1.20-sig-compute required
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1474 Bump cherrypicker image
  github/ci/prow-deploy/kustom/base/manifests/local/cherrypicker_deployment.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1479 Add jobs to test and push relase-blocker image
  external-plugins/release-blocker/BUILD.bazel
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/release-blocker_deployment.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#1475 Add CDI ARM build periodic
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M
