Repository kubevirt/project-infra, pull requests merged in 2022-02, with the labels that each got.

#1884 Deploy rook on the migration test job
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1885 Add a GOPROXY fallback if the main proxy rejects us
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1888 Fix VERSION for building and pushing tagged NMO
  github/ci/prow-deploy/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1875 Add HPP ceph lane
  github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner/hostpath-provisioner-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1890 Add jberkus to our org
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1892 cnao: Run release only on main and "release-"
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1886 Add the github credentials preset for a selection of prowjobs
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/community/community-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-postsubmits.yaml
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1838 add density scaling performance test, ranging from 200, 400, and 600 VMis
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#1894 Change GIT_ASKPASS env variable back to using the relative path
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1895 Move migration tests to a separate lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1896 Choose correct TARGET for migration tests
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1893 Add github credentials preset for kubevirt prowjobs
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1880 user-guide: check-links presubmit
  github/ci/prow-deploy/files/jobs/kubevirt/user-guide/user-guide-presubmits.yaml
Labels: size/S, approved, lgtm, needs-ok-to-test, dco-signoff: yes

#1606 Rename the NonRoot featureGate to correct one
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: lifecycle/stale, size/S, approved, lgtm, dco-signoff: yes

#1902 Make migration tests required and remove setting the storage backend
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#1903 Set storage backend for migrations lanes
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, dco-signoff: yes

#1907 Reset custom GIT_ASKPASS path in bump-cdi job after overwrite from preset
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1908 Remove GITHUB_TOKEN from github preset due to issues in some jobs
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1906 Add nonroot equivalent to migration lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1912 Make check-testgrid-config job required again
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1911 Make 1.20 check-provision jobs optional for kubevirtci
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1913 Remove check-provision for 1.20 providers
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1914 Add github credentials preset required for secrets
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1921 Sync version Istioctl version 1.13
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1916 Add dteplits to the organization
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, approved, lgtm, needs-ok-to-test, dco-signoff: yes

#1920 Add basic FlakeFinder report explanations
  robots/cmd/flakefinder/README.md
  robots/cmd/flakefinder/ff_build_popup.png
  robots/cmd/flakefinder/ff_overview.png
  robots/cmd/flakefinder/ff_weekly.png
Labels: size/M, approved, lgtm, dco-signoff: yes

#1924 Add kind-1.23-vgpu lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#1922 Add preset for GCS credentials to subset of prowjobs
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#1923 Make Brian an owner of the kubevirt org
  github/ci/prow-deploy/files/orgs.yaml
Labels: approved, lgtm

#1927 knmstate: Call publish only on main
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1928 Add preset for GCS credentials to remaining prowjobs
  github/ci/prow-deploy/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/libguestfs-appliance/libguestfs-appliance-periodics.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#1926 Make kind-1.23-vgpu lane run always
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1934 Update kubevirt builder image for newer bazel version
  github/ci/prow-deploy/files/jobs/kubevirt/community/community-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  hack/update-jobs-with-latest-image.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#1919 Add manifests to deploy loki and promtail to kubevirt-ci clusters
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/services/loki/BUILD.bazel
  github/ci/services/loki/README.md
  github/ci/services/loki/e2e/BUILD.bazel
  github/ci/services/loki/e2e/e2e_test.go
  github/ci/services/loki/hack/deploy.sh
  github/ci/services/loki/manifests/common/loki.yaml
  github/ci/services/loki/manifests/common/namespace.yaml
  github/ci/services/loki/manifests/common/promtail.yaml
  github/ci/services/loki/secrets/production-control-plane/gcs/.gitkeep
  github/ci/services/loki/secrets/production-control-plane/loki-config/loki.yaml
  github/ci/services/loki/secrets/testing/gcs/service-account.json
  github/ci/services/loki/secrets/testing/loki-config/loki.yaml
Labels: size/XL, approved, lgtm, dco-signoff: yes
