Repository kubevirt/project-infra, pull requests merged in 2022-08, with the labels that each got.

#2234 Release configs for kubevirt/kubevirt release branch release-0.56
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.56.yaml
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#2232 Single-node increase timeout
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2229 Use 2 nodes in pull-kubevirt-e2e-k8s-1.22-sig-monitoring
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2236 mirror: Update istio images naming so we can use them with istio operator
  hack/images_to_mirror.csv
  hack/mirror-images.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#2238 Move multiarch bootstrap jobs to prow-workloads cluster
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2235 Add presubmit unit test job for csi-driver
  github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2237 Add area/instancetype label
  github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2241 Disable the release-blocker plugin until it is fixed
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2240 Adjust HPP push jobs to build multi-arch images
  github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner-operator/hostpath-provisioner-operator-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner/hostpath-provisioner-postsubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2244 change time when the job run
  github/ci/prow-deploy/files/jobs/kubevirt/libguestfs-appliance/libguestfs-appliance-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2245 add debug info for libguestfs-appliance job
  github/ci/prow-deploy/files/jobs/kubevirt/libguestfs-appliance/libguestfs-appliance-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2218 Create bootstrap-legacy image for existing docker bootstrap prow jobs
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  images/bootstrap-legacy/Dockerfile
  images/bootstrap-legacy/README.md
  images/bootstrap-legacy/create_bazel_cache_rcs.sh
  images/bootstrap-legacy/entrypoint.sh
  images/bootstrap-legacy/runner.sh
  images/golang-legacy/Dockerfile
Labels: size/XL, approved, lgtm, dco-signoff: yes

#2246 Remove -gcs-workers flag from crier deployment
  github/ci/prow-deploy/README.md
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/branch-protector.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/cherrypicker_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/label-sync-kubevirt.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/label-sync-nmstate.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/crier_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/deck_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/ghproxy.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/hook_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/horologium_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/needs-rebase_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/prow_controller_manager_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/prowjob-crd/prowjob_customresourcedefinition.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/sinker_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/statusreconciler_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/tide_deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/crier_deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/prow-exporter-deployment.yaml
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#2250 add linter lane to csi-driver
  github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2251 Added fossa presubmit job for cdi
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2253 Update timeout for multiarch bootstrap jobs to 5 hours
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2243 Fix and enable release blocker plugin
  external-plugins/rehearse/plugin/handler/handler.go
  external-plugins/rehearse/plugin/main.go
  external-plugins/release-blocker/main.go
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/release-blocker_deployment.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2055 Replace docker with podman in bootstrap image
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  images/bootstrap/87-podman.conflist
  images/bootstrap/Dockerfile
  images/bootstrap/containers.conf
  images/bootstrap/runner.sh
Labels: size/L, approved, lgtm, dco-signoff: yes

#2190 Update flake-report-creator to show failuresForJobs in report and json
  hack/flake-report-creator.sh
  robots/cmd/flake-report-creator/cmd/jenkins.go
  robots/cmd/flakefinder/report_test.go
  robots/pkg/flakefinder/report_data.go
Labels: size/M, approved, lgtm, dco-signoff: yes

#2254 publish-kubevirtci: Increase timeout
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2261 Fix path to kubevirt-user-guide image in build and publish
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2262 Update autoowners image builder to golang 1.18
  images/autoowners/Dockerfile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2263 Add presubmit for build of kubevirt.github.io
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt.github.io/kubevirt-github-io-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2189 Update kubevirt.github.io container Dockerfile
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  images/kubevirt-kubevirt.github.io/Dockerfile
Labels: size/M, approved, lgtm, dco-signoff: yes

#2265 Update kubevirt.github.io jobs to pull from repo
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  images/kubevirt-kubevirt.github.io/Dockerfile
Labels: size/S, approved, lgtm, dco-signoff: yes

#2266 Replaced CWD reference in COPY
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  images/kubevirt-kubevirt.github.io/Dockerfile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2260 Update project-infra prowjobs to use the new podman based bootstrap
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#2270 Allow for only amd64 image builds in mulitarch image script
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  images/publish_multiarch_image.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#2268 Add periodic job for vgpu test lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2271 Update multiarch publish jobs to use legacy bootstrap image
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2275 csi-driver presumbits: Correct e2e test lane
  github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-presubmits.yaml
  github/ci/testgrid/gen-config.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2233 capk: sonobuoy conformance lane
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-api-provider-kubevirt/cluster-api-provier-kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2131 ovs-cni: Use podman on presubmit jobs
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/ovs-cni/ovs-cni-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2127 bridge marker: Use podman on presubmit jobs
  github/ci/prow-deploy/files/jobs/kubevirt/bridge-marker/bridge-marker-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2274 Remove check-provision job for 1.22-ipv6 as provider no longer exists
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2281 Fix periodic sysprep name to use 1.22
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2283 Fix secrets periodic key check clone reference
  github/ci/prow-deploy/files/jobs/kubevirt/secrets/secrets-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2278 Set always_run: true for DV GC lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2284 Fix pod antiaffinity for check-up-kind-1.23-vgpu
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2289 Add podAntiAffinity for vgpu presubmits
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2248 Enable nonroot sriov
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2293 Make DV GC lane required
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2292 Remove slack notifications from vgpu periodic
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2294 Keep make in the final image as well as git
  images/kubevirt-kubevirt.github.io/Dockerfile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2295 Add topologyKey to podAntiAffinity rules of vgpu
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2277 csi-driver postsubmit: update container image
  github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-postsubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2298 Add reference to project-infra repo for multiarch periodic
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2267 kubevirtci, presubmit: Increase max_concurrency
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2272 Update kubevirt.github.io jobs to use new container
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt.github.io/kubevirt-github-io-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt.github.io/kubevirt-github-io-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt.github.io/kubevirt-github-io-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2125 cnao: Use podman on presubmit jobs
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2128 kubemacpool: Use podman on presubmit jobs
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2285 macvtap: Use podman on postsubmit jobs
  github/ci/prow-deploy/files/jobs/kubevirt/macvtap-cni/macvtap-cni-postsubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2286 bridge marker: Use podman on postsubmit jobs
  github/ci/prow-deploy/files/jobs/kubevirt/bridge-marker/bridge-marker-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2287 cnao: Use podman on postsubmit jobs
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2290 kmp: Use podman on postsubmit jobs
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2300 Disable slack reporting for secrets periodic
  github/ci/prow-deploy/files/jobs/kubevirt/secrets/secrets-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2302 knmstate: Rebase on rust branch at future lane
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2273 Switch kubevirtci prowjobs to use podman in container setup
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2288 k8s nmstate: Use podman on postsubmit jobs
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes
