Repository kubevirt/project-infra, pull requests merged in 2022-11, with the labels that each got.

#2424 Fix rehearse plugin to rebase on target main branch
  external-plugins/rehearse/plugin/handler/handler.go
  github/ci/prow-deploy/kustom/base/manifests/local/prow-rehearse-deployment.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2426 images_to_mirror: Add kind node image v1.25.2
  hack/images_to_mirror.csv
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2425 kubevirtci, presubmit: Add optional job to check kind-1.25-sriov
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2400 Update CDI prow jobs to use the podman bootrap image
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2429 Add CI plugin config for test-benchmarks
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2430 Add missing common-instancetypes prow configuration
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2433 cnao: add multus-dynamic-networks functests to presubmits
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2427 Fix kubevirt lanes automation
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  robots/pkg/kubevirt/cmd/remove/always_run_test.go
  robots/pkg/kubevirt/cmd/remove/jobs_test.go
  robots/pkg/kubevirt/cmd/remove/testdata/should_modify/kubevirt-periodics.yaml
  robots/pkg/kubevirt/cmd/remove/testdata/should_modify/kubevirt-presubmits.yaml
  robots/pkg/kubevirt/cmd/remove/testdata/should_not_modify/kubevirt-periodics.yaml
  robots/pkg/kubevirt/cmd/remove/testdata/should_not_modify/kubevirt-presubmits.yaml
  robots/pkg/kubevirt/prowjobconfigs/jobconfig.go
Labels: size/M, approved, lgtm, dco-signoff: yes

#2434 Set enable CI report for test-benchmarks
  github/ci/prow-deploy/files/jobs/kubevirt/test-benchmarks/test-benchmarks-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2414 Add circuit breaker to flake-report-creator
  hack/flake-report-creator.sh
  robots/pkg/circuitbreaker/BUILD.bazel
  robots/pkg/circuitbreaker/circuitbreaker.go
  robots/pkg/circuitbreaker/circuitbreaker_test.go
  robots/pkg/jenkins/BUILD.bazel
  robots/pkg/jenkins/builds.go
  robots/pkg/jenkins/builds_test.go
Labels: size/XL, approved, lgtm, dco-signoff: yes

#2436 cnao: make multus-dynamic-networks lane mandatory
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2432 Add common-instancetypes pre and post submit jobs
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2435 Add optional presubmit to test cluster-sync against perf cluster
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2437 Only publish common-instancetypes image when it changes
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2441 Disable kubevirt 1.22 always run
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2418 Swap root and nonroot
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2443 Update ovs-cni postsubmit jobs to use podman
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/ovs-cni/ovs-cni-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2442 [sig-performance] Increase node memory and job memory request
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2446 images_to_mirror: Add kind node image v1.23.13
  hack/images_to_mirror.csv
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2447 kubevirtci, presubmit: Add optional job to check kind-1.23-sriov
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: approved, lgtm, dco-signoff: yes

#2451 Increase memory request of publish-kubevirtci job
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2452 Update libguetfs periodics
  github/ci/prow-deploy/files/jobs/kubevirt/libguestfs-appliance/libguestfs-appliance-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2456 Move capk e2e prowjob back to using dind
  github/ci/prow-deploy/files/jobs/kubernetes-sigs/cluster-api-provider-kubevirt/cluster-api-provider-kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2458 Bump common-instancetypes-builder
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2457 Revert "Move capk e2e prowjob back to using dind (#2456)"
  github/ci/prow-deploy/files/jobs/kubernetes-sigs/cluster-api-provider-kubevirt/cluster-api-provider-kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2455 Replace inline pgp-bot-key volumes with a preset
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.47.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.48.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.49.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.50.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.51.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.52.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.53.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.54.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.55.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.56.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.57.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.58.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/secrets/secrets-presubmits.yaml
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  robots/pkg/kubevirt/cmd/remove/testdata/should_modify/kubevirt-periodics.yaml
  robots/pkg/kubevirt/cmd/remove/testdata/should_not_modify/kubevirt-periodics.yaml
Labels: size/L, ok-to-test, approved, lgtm, dco-signoff: yes

#2461 Add additional image store to podman conf
  images/bootstrap/Dockerfile
  images/bootstrap/storage.conf
Labels: size/L, approved, lgtm, dco-signoff: yes

#2463 Increase node memory for 0.58 performance lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.58.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2460 Use the new unified web container image for user-guide
  github/ci/prow-deploy/files/jobs/kubevirt/user-guide/user-guide-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/user-guide/user-guide-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2468 Increase timeout by 30mins on sig monitoring presubmit
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2469 Update iholder's username to iholder101
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2466 Add newline to commit msg for bump prow jobs
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2474 Revert "Add newline to commit msg for bump prow jobs (#2466)"
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2475 Change CDI image postsubmits back to dind
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2477 Add K8s-1.23 SR-IOV lane jobs
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#2481 presubmit, kubevirtci: Switch to check-up-kind-1.23-sriov
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2478 Add new presubmit for kubevirtci 1.26 provider, update creator to manually create presubmits
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
  robots/cmd/kubevirtci-presubmit-creator/main.go
  robots/pkg/jenkins/builds_test.go
Labels: size/L, approved, lgtm, dco-signoff: yes

#2459 cnao, presubmit: Add kube secondary dns lane
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2486 Switch check-provision-1.22 to optional
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2488 Increase timeout for publish kubevirtci
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2484 Create 1.26 lanes for kubevirt
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  robots/pkg/kubevirt/cmd/copy/jobs.go
Labels: size/L, approved, lgtm, dco-signoff: yes

#2490 prow: Add KubeSecondaryDNS basic config
  github/ci/prow-deploy/files/orgs.yaml
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2489 kubevirtci, presubmit: Introduce k8s-1.25-ipv6
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2492 kubesecondarydns, presubmit: Fix e2e lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubesecondarydns/kubesecondarydns-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2480 Add check-provision job for 1.25-fips
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2494 Add periodic unit tests and kind e2e tests for Arm64 Cluster
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2351 Add unit test and e2e test for Arm64
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes
