Repository kubevirt/project-infra, pull requests merged in 2022-12, with the labels that each got.

#2497 Adding kind/ labels to help categorise release notes
  github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2500 presubmit, ksd: Update image
  github/ci/prow-deploy/files/jobs/kubevirt/kubesecondarydns/kubesecondarydns-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2491 kubevirt, presubmit: Introduce k8s-1.25-ipv6-sig-network
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2502 presubmit, cnao, ksd: Make lane required
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2496 kubevirt, presubmits: Add psa-sig-network lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2503 Increase memory requests of bootstrap image build jobs
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2501 bootstrap files: Add bind-utils
  images/bootstrap-legacy/Dockerfile
  images/bootstrap/Dockerfile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2505 kubevirt, presubmits: run pull-kubevirt-unit-test-arm64 on Arm Cluster 2
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2487 Update the performance lanes to use the 1.25 provider
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2506 Remove 1.22 presubmit and periodic lanes
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XL, approved, lgtm, dco-signoff: yes

#2508 Increase memory request/limit for publish of shared images
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2495 Add image bump for prowjobs to hack/bump-prow.sh
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  hack/bump-prow.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#2510 Set check-up-kind-1.23-vgpu to optional
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2509 Set check provision for 1.26 to run always
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2512 Increase thanos data retention for 1hr resolution to 1 year
  github/ci/services/prometheus-stack/manifests/stack/production-control-plane/thanos.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2513 Fix prow binary pathes
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2514 single stack: Switch to k8s-1.25-ipv6
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2515 Add provision check for PSA
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2511 Add daemonset for shared images to prow-workloads cluster
  github/ci/prow-deploy/kustom/overlays/workloads-production/kustomization.yaml
  github/ci/prow-deploy/kustom/overlays/workloads-production/resources/shared-images-controller.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2518 Add preset for podman shared images store
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2517 Reduce length of image tag to be looked for
  hack/update-jobs-with-latest-image.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2519 Bump sig compute migration lanes
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2498 Make the performance job voting and running per commit
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2516 Update PSA jobs and use new way to enable it
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2210 Generate a test-report over a set of builds in HTML
  go.mod
  hack/test-report.sh
  robots/cmd/test-report/BUILD.bazel
  robots/cmd/test-report/Makefile
  robots/cmd/test-report/README.md
  robots/cmd/test-report/compute-config.yaml
  robots/cmd/test-report/default-config.yaml
  robots/cmd/test-report/main.go
  robots/cmd/test-report/main_test.go
  robots/cmd/test-report/network-config.yaml
  robots/cmd/test-report/ssp-config.yaml
  robots/cmd/test-report/storage-config.yaml
  robots/cmd/test-report/test-report.gohtml
  robots/pkg/test-report/BUILD.bazel
  robots/pkg/test-report/test_report.go
  robots/pkg/test-report/test_report_test.go
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#2520 Temporary workaround for windows2016 lane issue
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2522 FIPS: remove unnecessary presubmit job and add optional sig-compute lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2525 Add gcs credentials to windows related e2e jobs
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2524 Update bootstrap images to use Fedora 37
  images/bootstrap-legacy/Dockerfile
  images/bootstrap/Dockerfile
  images/golang/Dockerfile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2526 Enable the windows e2e presubmit lane for all kubevirt PRs
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes
