Repository kubevirt/project-infra, pull requests merged in 2022-06, with the labels that each got.

#2136 Add codingben to members
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, approved, lgtm, needs-ok-to-test, dco-signoff: yes

#2137 Extend default artifact filename regex
  robots/cmd/flake-report-creator/cmd/jenkins.go
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2140 Update runner.sh to exit when docker daemon fails to start
  images/bootstrap/runner.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2141 Fix: override GIT_ASKPASS to make the job work again
  github/ci/prow-deploy/files/jobs/kubevirt/community/community-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2124 kubevirt: add lane used for running clean code checks
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2133 Set check-provision-k8s-1.24 to required to test new provider
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2145 k8s-1.24-ipv6: Add provision lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2148 add member usrbinkat
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, approved, lgtm, needs-ok-to-test, dco-signoff: yes

#2154 Add ansible output highlighting
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2155 Fix highlight expression
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2161 kubevirt/presubmits/lint: Add privileged security context
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2158 cgroupsv2: Add periodics and run_if_changed
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#2162 Add priority class for windows e2e jobs
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.50.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.51.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.52.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.53.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow-deploy/kustom/overlays/workloads-production/resources/priority-classes.yaml
  github/ci/prow-deploy/tasks/deploy.yml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2163 Fix windows priority class by adding to prowjob spec
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.50.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.51.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.52.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.53.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2152 Add json output to flake-report-creator
  hack/flake-report-creator.sh
  hack/update-scripts-with-latest-image.sh
  robots/cmd/flake-report-creator/cmd/jenkins.go
  robots/cmd/flake-report-creator/cmd/jenkins_test.go
  robots/cmd/push.sh
  robots/pkg/flakefinder/report_data.go
Labels: size/L, kind/enhancement, approved, lgtm, dco-signoff: yes, area/flakefinder

#2164 Adding aburdenthehand to the KubeVirt org
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, approved, lgtm, needs-ok-to-test, dco-signoff: yes

#2166 Increase node memory for perf jobs
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2132 Add new kubeconfig secret required to deploy prow services
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/branch-protector.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/cherrypicker_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/label-sync-kubevirt.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/label-sync-nmstate.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/crier_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/deck_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/ghproxy.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/hook_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/horologium_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/needs-rebase_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/prow_controller_manager_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/sinker_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/statusreconciler_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/tide_deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/kustomization.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/prow-exporter-deployment.yaml
  github/ci/prow-deploy/molecule/default/prepare.yml
  github/ci/prow-deploy/tasks/secrets.yml
Labels: size/L, approved, lgtm, dco-signoff: yes

#2169 cgroups, storage: Add additonal folders
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2168 cgroups: Make lanes non optional
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2171 kubevirtci, alpine: Increase timeout to 20m
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2165 Add kubevirt periodics cron timetable printer
  go.mod
  go.sum
  robots/cmd/kubevirtperiodics/main.go
Labels: size/L, approved, lgtm, dco-signoff: yes

#2172 Mirror kind-node image from docker.io to quay.io
  hack/images_to_mirror.csv
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2170 add detailed information of the performance cluster
  docs/infra-layout.svg
  docs/infrastructure-components.md
  docs/performance-cluster.md
Labels: size/L, approved, lgtm, dco-signoff: yes

#2149 sig-network, ipv6: Bump provider to 1.24
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2175 kubevirtci kubevirt bump: Increase periodic rate
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2095 emphasize tests with higher number of failures over those with higher ratio
  robots/pkg/flakefinder/report_data.go
  robots/pkg/flakefinder/report_data_test.go
Labels: size/L, kind/enhancement, approved, lgtm, dco-signoff: yes, area/flakefinder

#2174 Add optional CDI Ceph lane with DV GC enabled
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2176 Fix CDI Ceph GC lane automation script call
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2177 Update golang image to use go 1.17.8
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  images/golang/Dockerfile
Labels: size/M, approved, lgtm, dco-signoff: yes

#2178 Disable coveralls reporting due to service outage
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes
