Repository kubevirt/project-infra, pull requests merged in 2022-05, with the labels that each got.

#2069 Increase performance job memory
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2066 knmstate: add e2e upgrade lane
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2063 Fix config-bootstrapper call
  github/ci/prow-deploy/tasks/deploy.yml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2065 Add presubmit for decryption checking
  github/ci/prow-deploy/files/jobs/kubevirt/secrets/secrets-presubmits.yaml
  github/ci/prow-deploy/files/orgs.yaml
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2077 Add brianmcarey to approvers in OWNERS
  OWNERS
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2078 Increase periodic performance jobs mem
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2079 Update flakefinder images with sort fix
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-periodics.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2082 Increase memory request to 14Gi for kubevirtci presubmits
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2083 Use podman for mkpj.sh script if installed
  hack/mkpj.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#1918 flake-report-creator jenkins: Use css for popup
  robots/cmd/flake-report-creator/cmd/jenkins.go
Labels: size/M, approved, lgtm, dco-signoff: yes

#2074 sriov: Run cluster-down only once in trap
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2081 flakefinder: fix timeouts for jenkins build retrieval
  Makefile
  WORKSPACE
  go.mod
  go.sum
  go_third_party.bzl
  robots/cmd/flake-report-creator/cmd/BUILD.bazel
  robots/cmd/flake-report-creator/cmd/jenkins.go
Labels: size/M, approved, lgtm, dco-signoff: yes

#2070 Release configs for kubevirt/kubevirt release branch release-0.53
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.53.yaml
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#2087 prow-deploy: delete priority classes before re-deployment
  github/ci/prow-deploy/tasks/deploy.yml
  github/ci/prow-deploy/vars/kubevirtci-testing/secrets.yml
  github/ci/prow-deploy/vars/workloads-production/main.yml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2090 prow-deploy: fix missing ansbile variable for deployment
  github/ci/prow-deploy/vars/ibmcloud-production/main.yml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2086 Add mirror for previous minor release of cri-o
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
  hack/mirror-crio.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2068 sriov: Introduce place holder DaemonSet
  github/ci/prow-deploy/kustom/overlays/workloads-production/resources/place-holder.yaml
  github/ci/prow-deploy/kustom/overlays/workloads-production/resources/priority-classes.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2091 prow-deploy: add the place-holder daemonset to kustomize list
  github/ci/prow-deploy/kustom/overlays/workloads-production/kustomization.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2088 remove legacy automation for creating container disks for fedora and centos
  github/ci/prow-deploy/files/jobs/kubevirt/common-templates/OWNERS
  github/ci/prow-deploy/files/jobs/kubevirt/common-templates/common-templates-periodics.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2093 sriov: Add namespace to the place holder ds
  github/ci/prow-deploy/kustom/overlays/workloads-production/resources/place-holder.yaml
  github/ci/prow-deploy/tasks/deploy.yml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2094 kubevirtci, sriov: Add missing pc
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2096 periodic, sriov: Add missing pc
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2092 prow-deploy: disable usage of remote caching for release configs
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.34.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.36.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.37.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.38.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.39.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.40.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.41.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.42.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.43.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.44.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.45.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.46.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.47.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.48.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.49.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.50.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.51.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.52.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.53.yaml
Labels: size/XL, approved, lgtm

#2098 Update bootstrap image to Fedora 36
  images/bootstrap/Dockerfile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2099 cnao, Add a new stable branch release-0.76
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.76.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#2089 Add ssh secret to access private repos with prow
  github/ci/prow-deploy/files/jobs/kubevirt/secrets/secrets-presubmits.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/kustomization.yaml
  github/ci/prow-deploy/kustom/overlays/workloads-production/kustomization.yaml
  github/ci/prow-deploy/tasks/secrets.yml
  github/ci/prow-deploy/vars/kubevirtci-testing/secrets.yml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2097 kmp, add a new stable branch release_v0.38
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits-v0.38.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2101 Update ci-maintainers for kubot
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2100 Fix cnao release0.76 lanes
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.76.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2104 Remove previous minor release of cri-o from mirror job
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2103 release-0.52, sriov: Add missing pc (#2096)
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.52.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2042 Use NonRoot instead of NonRootExperimental
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.47.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.48.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.49.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.50.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.51.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.52.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2102 Remove branch protection for secrets
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2108 cnao: add monitoring lane for release-0.65
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.65.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2109 cnao: add monitoring lane to release-0.76
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.76.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2111 Add custom highlighter patterns for kubevirt
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#1962 Add periodic job for kubevirt-velero-plugin
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-velero-plugin/kubevirt-velero-plugin-periodics.yaml
  github/ci/testgrid/gen-config.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2107 Improve alert message for high percentage of errors in Grafana
  github/ci/services/loki/manifests/common/rules.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2113 Add kvaps to org members
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, approved, lgtm, needs-ok-to-test, dco-signoff: yes

#2110 Add repo onboarding documentation
  docs/how-to-onboard-a-repository.md
  docs/prow_webhook_configuration.png
Labels: size/M, approved, lgtm, dco-signoff: yes

#2020 Add 1.23 vgpu cluster up check
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2117 Remove GIMME_GO_VERSION from kind prow jobs
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2116 Narrow down image bump to only use images with valid tag
  hack/update-jobs-with-latest-image.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2115 Update labels for project-infra, fix some issues
  github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2121 Add cri-o version 1.24 to periodic mirror job for 1.24 provider
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2105 Add prow debug serviceaccount and KUBECONFIG generation script
  github/ci/prow-deploy/kustom/base/manifests/local/prow-debug-rbac.yaml
  hack/generate-prow-debug-kubeconfig.sh
Labels: size/L, approved, lgtm, dco-signoff: yes

#2123 Add geetikakay to the org
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, ok-to-test, approved, lgtm, dco-signoff: yes

#2126 HCO: Add tests for the new release-1.7 branch
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.7.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2129 Add prnaraya to the org
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, ok-to-test, approved, lgtm, dco-signoff: yes

#2135 Update ci search alert description to better reflect error
  github/ci/services/loki/manifests/common/rules.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes
