Repository kubevirt/project-infra, pull requests merged in 2022-04, with the labels that each got.

#1996 Bump containerdisks repo to golang 1.17
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2004 cloud-provider-kubevirt: Make unit-tests presubmit mandatory
  github/ci/prow-deploy/files/jobs/kubevirt/cloud-provider-kubevirt/cloud-provider-kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2006 Add rescaling of pushgateway deployment
  github/ci/prow-deploy/tasks/deploy.yml
  github/ci/prow-deploy/vars/ibmcloud-production/main.yml
  github/ci/prow-deploy/vars/kubevirtci-testing/secrets.yml
  github/ci/prow-deploy/vars/workloads-production/main.yml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2001 [Release 0.51] IPv6 lane shouldn't be required and should be optional
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.51.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2007 Require pull-kubevirt-e2e-kind-1.23-vgpu-nonroot
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1900 Make NonRoot network lane required
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1889 Add docker debug
  images/bootstrap/README.md
  images/bootstrap/runner.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#2011 Revert "Make nonroot network lane required (#1900)"
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2012 Revert sriov rootless
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2013 Move all non sriov jobs to non sriov nodes
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2015 Remove kind 1.19
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2017 Update branch name for Tide Daily Merge Rate grafana panel
  github/ci/services/prometheus-stack/manifests/stack/production-control-plane/grafana.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2000 Add packages to bootstrap (to build multi-arch containers)
  images/bootstrap/Dockerfile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2018 Add priority classes for the sriov and vgpu jobs
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow-deploy/kustom/overlays/workloads-production/kustomization.yaml
  github/ci/prow-deploy/kustom/overlays/workloads-production/resources/priority-classes.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2016 Allow regular e2e workloads to be scheduled on SR-IOV nodes
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2021 Add priority classes to sriov and vgpu
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.30.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.34.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.36.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.37.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.38.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.39.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.40.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.41.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.42.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.43.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.44.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.45.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.46.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.47.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.48.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.49.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.50.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.51.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2025 cloud-provider-kubevirt: Change Presubmit Golang version to 1.17
  github/ci/prow-deploy/files/jobs/kubevirt/cloud-provider-kubevirt/cloud-provider-kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2026 Typo in one the new CDI lanes
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2022 Add job_name filter to prow job load dashboard
  github/ci/services/prometheus-stack/manifests/stack/production-control-plane/grafana.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#2019 Add node label configuration to prow config
  github/ci/prow-deploy/kustom/overlays/workloads-production/resources/bootstrap.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2029 kubevirtci: Add alpine provision presubmit job
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2033 kubevirtci, publish: Mount modules and devs
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2028 Add ceph to single replica lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2032 Skip reporting on pull-project-infra-check-testgrid-config due to failures
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2034 single-node lane: add a "focus all" option to avoid storage-req auto-focus
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2023 Request adding alromeros to org members
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, ok-to-test, approved, lgtm, dco-signoff: yes

#2035 Fork kubevirt prow job configs for release-0.52
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.52.yaml
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#2039 Bump kubevirtci test lane in HCO to k8s-1.23
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2037 labels: Introduce a new sig/code-quality label
  github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2043 Add opokornyy to the org
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, ok-to-test, approved, lgtm, dco-signoff: yes

#2046 add podman to kubevirt-infra-bootstrap image
  images/kubevirt-infra-bootstrap/Dockerfile
Labels: size/S, approved, lgtm, dco-signoff: yes

#2047 [containerdisks] Add a pipeline test presubmit job
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2038 Add namespace label to loki alerts
  github/ci/services/loki/manifests/common/rules.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2008 Fix path to bootstrap script for prow-workloads cluster
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2027 Reinstate goproxy.io
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2045 Enable CDI lane scripts
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#2048 Update base image common templates jobs
  github/ci/prow-deploy/files/jobs/kubevirt/common-templates/common-templates-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2044 Use go to run check-testgrid-config tests
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/testgrid/hack/check.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#2049 Verify containerdisks before pushing
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2051 Add quay oauth token to the quay credentials secret
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/overlays/workloads-production/kustomization.yaml
  github/ci/prow-deploy/templates/quay_credentials.j2
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2052 kubevirtci: Install libvirt + genisoimage
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2053 Force change for job definitions on release-0.52
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.52.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2050 Use go version 1.18 for check testgrid config
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#1960 Add plugin to testgrid dashboard
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-velero-plugin/kubevirt-velero-plugin-presubmits.yaml
  github/ci/testgrid/gen-config.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2056 Shard the job configs into configmaps per org
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/branch-protector.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/crier_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/deck_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/hook_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/horologium_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/prow_controller_manager_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/sinker_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/statusreconciler_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/tide_deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/ci-usage-exporter-deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/prow-exporter-deployment.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirtci-testing/resources/bootstrap.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#2060 Move config bootstrapping before deployment
  github/ci/prow-deploy/tasks/deploy.yml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2059 sig-performance: Increase timeout to 1h30m0s
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2064 sig-performance: Increase KUBEVIRT_MEMORY_SIZE to 10G
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes
