Repository kubevirt/project-infra, pull requests merged in 2022-10, with the labels that each got.

#2357 Add releng presubmit
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2365 Release configs for kubevirt/kubevirt release branch release-0.58
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.58.yaml
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#2366 Increase thanos compact PVC to 40Gi
  github/ci/services/prometheus-stack/manifests/stack/production-control-plane/thanos.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2321 Update kubevirt prowjobs to use the new podman in container setup
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#2367 Remove single-node lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2371 Update nonroot lanes to latest k8s version
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2299 cloud-provider-kubevirt: go 1.19
  github/ci/prow-deploy/files/jobs/kubevirt/cloud-provider-kubevirt/cloud-provider-kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2372 Increase thanos-compact pvc to 100Gi due to out space error
  github/ci/services/prometheus-stack/manifests/stack/production-control-plane/thanos.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2375 Add pre-submit for CNAO release-0.79
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.79.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#2376 Mirror istioctl 1.15
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2370 Update kubevirt-velero-plugin jobs to use new podman bootstrap
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-velero-plugin/kubevirt-velero-plugin-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-velero-plugin/kubevirt-velero-plugin-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-velero-plugin/kubevirt-velero-plugin-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2378 Mirror istio images 1.15
  hack/images_to_mirror.csv
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2381 Allow mirror images job to run privileged
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2339 Update CDI prow jobs to use the podman bootrap
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2384 Toggling wiki to 'true' for the community repo
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2385 Update libguestfs-appliance prowjobs to use podman bootstrap image
  github/ci/prow-deploy/files/jobs/kubevirt/libguestfs-appliance/libguestfs-appliance-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/libguestfs-appliance/libguestfs-appliance-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/test-benchmarks/test-benchmarks-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2392 Mirror cri-o version 1.25 to be used by 1.25 provider
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2393 Increase wait time for podman socket to be ready
  images/bootstrap/runner.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2383 Increase thanos compact cpu and memory limits
  github/ci/services/prometheus-stack/manifests/stack/production-control-plane/thanos.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2382 Update to kubectl-virt-plugin prowjobs to use podman
  github/ci/prow-deploy/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2398 Revert "Update CDI prow jobs to use the podman bootrap (#2339)"
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2410 Switch non-root sriov presubmit to optional
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2409 HCO: Add tests for the new release-1.8 branch
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.8.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2411 Make check-provision job for 1.25 provider required
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2412 Make fossa lane in CDI always run and required
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2397 bootstrap: add j2 to the img
  images/bootstrap/Dockerfile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2403 Fix the namespace assignment for hack/generate-prow-debug-kubeconfig.sh
  hack/generate-prow-debug-kubeconfig.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#2413 Use correct provider name for operator lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2416 Revert prow due to issue with applying sriov labels to pods
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/branch-protector.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/cherrypicker_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/label-sync-kubevirt.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/label-sync-nmstate.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/crier_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/deck_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/ghproxy.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/hook_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/horologium_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/needs-rebase_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/prow_controller_manager_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/prowjob-crd/prowjob_customresourcedefinition.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/sinker_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/statusreconciler_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/tide_deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/prow-exporter-deployment.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2359 Update capk and cloud provider presubmits to use podman
  github/ci/prow-deploy/files/jobs/kubernetes-sigs/cluster-api-provider-kubevirt/cluster-api-provider-kubevirt-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cloud-provider-kubevirt/cloud-provider-kubevirt-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-api-provider-kubevirt/OWNERS
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-api-provider-kubevirt/cluster-api-provier-kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2404 Reenable reporting for FOSSA presubmit
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2402 Update csi-driver prowjobs to use podman bootstrap
  github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2406 Switch rootful vgpu lane to be optional
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2387 Update hco prowjobs to use the podman bootstrap image
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2405 Ad Shelly as a velero-plugin admin
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2419 Remove DV GC lanes, as it is enabled by default
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2415 Add common-instancetypes repo to KubeVirt
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2394 Update nmstate presubmit to use podman bootstrap
  github/ci/prow-deploy/files/jobs/nmstate/nmstate/nmstate-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2422 Upgrade rehearsal deployment to latest image version
  github/ci/prow-deploy/kustom/base/manifests/local/prow-rehearse-deployment.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes
