Repository kubevirt/project-infra, pull requests merged in 2023-12, with the labels that each got.

#3105 Update runtime for limiter cloud function to latest go 1.21
  go.mod
  limiter/Makefile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3110 common-instancetypes: Bump builder image
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3045 Update bootstrap image of 0.49 sig-network lanes
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.49.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3112 Switch 0.53 nonroot network lanes to podman bootstrap
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.53.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3109 common-instancetypes: Check for clean tree in presubmits
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3113 Enable PodSecurityAdmission for remaining lanes
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3119 fix, botreview, publish: needs to run privileged
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3111 Update mirror-crio.sh to sync new cri-o repos
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
  hack/mirror-crio.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#3121 Update infra components doc to capture recent changes
  docs/infrastructure-components.md
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3120 refactor, botreview: align result structs into one
  external-plugins/botreview/review/BUILD.bazel
  external-plugins/botreview/review/bump_kubevirtci.go
  external-plugins/botreview/review/bump_kubevirtci_test.go
  external-plugins/botreview/review/image_update.go
  external-plugins/botreview/review/image_update_test.go
  external-plugins/botreview/review/prow_autobump.go
  external-plugins/botreview/review/prow_autobump_test.go
  external-plugins/botreview/review/result.go
  external-plugins/botreview/review/review.go
Labels: size/L, approved, lgtm, dco-signoff: yes

#3125 report, flake-stats: filter root lanes from report
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  robots/cmd/flake-stats/main.go
Labels: size/S, approved, lgtm, dco-signoff: yes

#3130 Make the 1.29 kubevirtci presubmit required
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3132 common-instancetypes: Add presubmits to validate individual preferences
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#3133 bazel, golang: update to go 1.20.12
  .bazelversion
  WORKSPACE
  images/bootstrap/Dockerfile
Labels: size/S, approved, lgtm, dco-signoff: yes

#3135 Revert enable psa for root
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3137 Remove loki service as no longer required
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/services/loki/BUILD.bazel
  github/ci/services/loki/README.md
  github/ci/services/loki/e2e/BUILD.bazel
  github/ci/services/loki/e2e/e2e_test.go
  github/ci/services/loki/hack/deploy.sh
  github/ci/services/loki/manifests/common/loki.yaml
  github/ci/services/loki/manifests/common/namespace.yaml
  github/ci/services/loki/manifests/common/promtail.yaml
  github/ci/services/loki/manifests/common/rules.yaml
  github/ci/services/loki/secrets/production-control-plane/gcs/.gitkeep
  github/ci/services/loki/secrets/production-control-plane/loki-config/loki.yaml
  github/ci/services/loki/secrets/testing/gcs/service-account.json
  github/ci/services/loki/secrets/testing/loki-config/loki.yaml
  go_third_party.bzl
Labels: size/XL, approved, lgtm, dco-signoff: yes

#3138 common-instancetypes: Add Validation OS presubmit
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes
