Repository kubevirt/project-infra, pull requests merged in 2023-03, with the labels that each got.

#2644 Remove PSA from rootful kubevirt perodic lanes
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2643 Create initial label config for good-first-issue
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2646 Remove rootful kubevirt presubmit lanes
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#2639 Port test name layout enhancements
  hack/flake-report-creator.sh
  robots/cmd/flake-report-creator/cmd/jenkins-report-template.gohtml
  robots/cmd/flakefinder/report.gohtml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2608 Add document on AMD SEV testing cluster
  docs/amd-infra-layout.svg
  docs/amd-sev-cluster.md
Labels: size/M, approved, lgtm, dco-signoff: yes

#2620 Update bazel remote cache flag to --remote_cache
  images/bootstrap/create_bazel_cache_rcs.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2628 Update kubevirtci-bumper to bump minor version of alt providers
  robots/pkg/kubevirtci/kubevirtci.go
  robots/pkg/kubevirtci/kubevirtci_test.go
Labels: size/M, approved, lgtm, dco-signoff: yes

#2580 single stack providers: Use the robust provider
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2649 Add filtering to test-report
  hack/test-report.sh
  robots/cmd/test-report/cmd/execution/execution.go
  robots/cmd/test-report/cmd/execution/execution_test.go
  robots/cmd/test-report/cmd/execution/ssp-config.yaml
  robots/cmd/test-report/cmd/execution/test-report.gohtml
  robots/pkg/test-report/test_report.go
Labels: size/L, approved, lgtm, dco-signoff: yes

#2656 HCO: Add tests for the new release-1.9 branch
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.9.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2654 kubevirt, vgpu: Update lane name
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2658 [hco] align 1.8 and 1.9 configurations
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.8.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2660 Revert "Run hack/bump-prow-job-images.sh (#2650)"
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits.yaml
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/ovs-cni/ovs-cni-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/ovs-cni/ovs-cni-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubernetes-sigs/cluster-api-provider-kubevirt/cluster-api-provider-kubevirt-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/bridge-marker/bridge-marker-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/bridge-marker/bridge-marker-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cloud-provider-kubevirt/cloud-provider-kubevirt-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/controller-lifecycle-operator-sdk/controller-lifecycle-operator-sdk-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner-operator/hostpath-provisioner-operator-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner-operator/hostpath-provisioner-operator-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner/hostpath-provisioner-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner/hostpath-provisioner-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubesecondarydns/kubesecondarydns-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-tutorial/kubevirt-tutorial-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-velero-plugin/kubevirt-velero-plugin-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-velero-plugin/kubevirt-velero-plugin-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-velero-plugin/kubevirt-velero-plugin-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/libguestfs-appliance/libguestfs-appliance-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/libguestfs-appliance/libguestfs-appliance-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/macvtap-cni/macvtap-cni-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/macvtap-cni/macvtap-cni-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-presubmits-master.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/qe-tools/qe-tools-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/secrets/secrets-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/terraform-provider-kubevirt/terraform-provider-kubevirt-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/test-benchmarks/test-benchmarks-presubmits.yaml
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-presubmits.yaml
  github/ci/prow-deploy/files/jobs/nmstate/nmstate/nmstate-presubmits.yaml
Labels: size/XL, approved, lgtm, dco-signoff: yes

#2641 sig-network: Add optional and weekly jobs to run tests with MultusV4
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2667 Revert lifecycle-operator-sdk presubmit to docker
  github/ci/prow-deploy/files/jobs/kubevirt/controller-lifecycle-operator-sdk/controller-lifecycle-operator-sdk-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2668 Bump kubevirtci on controller-lifecycle-operator-sdk-e2e
  github/ci/prow-deploy/files/jobs/kubevirt/controller-lifecycle-operator-sdk/controller-lifecycle-operator-sdk-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2634 k3d-sriov: Replace kind with k3d for SR-IOV jobs
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#2669 Update sig-monitoring presubmit to use k8s-1.26-centos9 target
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2652 common-instancetypes: Add presubmits for release-0.1
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-0.1.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2671 Add assafad to the org
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, ok-to-test, approved, lgtm, dco-signoff: yes

#2670 kubevirt, periodics, SR-IOV: Reduce rate
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2673 containerdisks: Send alert emails for failures in periodics
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
  github/ci/testgrid/gen-config.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2666 Create sig-release repo and release-team
  github/ci/prow-deploy/files/orgs.yaml
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2659 Update 1.26 kubevirtci image name to match provider name
  images/shared-images-controller/main.go
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2675 Bump shared images controller to the latest published image
  github/ci/prow-deploy/kustom/overlays/workloads-production/resources/shared-images-controller.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2661 Add support for /rehearse <job-name>
  external-plugins/rehearse/Makefile
  external-plugins/rehearse/plugin/handler/handler.go
  external-plugins/rehearse/plugin/handler/handler_test.go
  hack/print-workspace-status-no-git-tag.sh
Labels: size/L, approved, lgtm, dco-signoff: yes

#2674 Update user and cluster name for new perf cluster prometheus stack
  github/ci/services/prometheus-stack/BUILD.bazel
  github/ci/services/prometheus-stack/manifests/stack/production-performance-workloads/local-path-storage.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2677 Update rehearse deployment, add deployment update script
  external-plugins/rehearse/Makefile
  github/ci/prow-deploy/kustom/base/manifests/local/prow-rehearse-deployment.yaml
  hack/update-deployments-with-latest-image.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#2681 Migrate sig-compute e2e lanes to the new workloads cluster
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2685 Add optional presubmit lane for k8s 1.27
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2683 feat(containerdisks): Add presubmit test job
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2690 Remove mykaul from kubevirt org
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2691 Remove fromanirh from org since user doesn't exist any more
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2692 Make the 1.27 check-provision presubmit required
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes
