Repository kubevirt/project-infra, pull requests merged in 2023-06, with the labels that each got.

#2630 vm-image-builder: update vm-image-builder
  images/vm-image-builder/Dockerfile
  images/vm-image-builder/README.md
  images/vm-image-builder/qemu.conf
  images/vm-image-builder/start_libvirtd.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#2787 add scrape.sh to automate generating weekly perf-report
  robots/cmd/perf-report-creator/scrape.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#2795 Add CDI non-CSI lane
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2631 Arm64: Add jobs for build multi-arch vm-image-builder image
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2803 Remove bare-metal selector as running on control-plane cluster
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2772 kubevirt, presubmit: Bump kind SR-IOV to k8s-1.27 and re-enable instead of k3d
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2797 Reduce retries, add exponential backoff
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/prow-deploy/hack/test.sh
  github/ci/prow-deploy/kustom/base/manifests/local/prow-rehearse-deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/release-blocker_deployment.yaml
  github/ci/prow-deploy/kustom/components/greenhouse/base/resources/deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/ci-usage-exporter-deployment.yaml
  github/ci/prow-deploy/molecule/default/converge.yml
  github/ci/prow-deploy/molecule/default/retry-pod-status.yml
  github/ci/prow-deploy/molecule/default/smoke_tests.yml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2802 Fix git blame extraction regex
  robots/cmd/test-label-analyzer/cmd/stats.go
  robots/pkg/test-label-analyzer/stats.go
  robots/pkg/test-label-analyzer/stats_test.go
Labels: size/M, approved, lgtm, dco-signoff: yes

#2600 provision manager: Add presubmit job
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2809 Make non-csi lane in CDI mandatory
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2810 Update to Fedora 38 and go 1.19.9 in the bootstrap images
  images/bootstrap/Dockerfile
  images/golang/Dockerfile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2818 add ability to plot data after a given date
  robots/cmd/perf-report-creator/main.go
  robots/cmd/perf-report-creator/plot.go
Labels: size/S, approved, lgtm, dco-signoff: yes

#2821 stop using relative paths for OUTPUT_DIR
  robots/cmd/perf-report-creator/scrape.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2823 periodic, sriov: Fix version
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2822 presubmit, kubevirtci, vgpu: Bump to 1.27
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2815 Update e2e presubmits to run etcd in memory
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2828 Release configs for kubevirt/kubevirt release branch release-1.0
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#2830 Give pull-containerized-data-importer-e2e-ceph 6h to complete
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2829 Add crio 1.27 to the kubevirt mirror
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2831 Use rehearse image with fix for release branch issue
  github/ci/prow-deploy/kustom/base/manifests/local/prow-rehearse-deployment.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2832 Make hostpath provisioner operator unit test lane required
  github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner-operator/hostpath-provisioner-operator-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2826 kubevirt e2e Arm64: using kind-1.27 cluster to run e2e test on Arm64
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2824 kubevirt, vgpu: Bump to 1.27
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2837 Turn off flapping alerts
  github/ci/services/prometheus-stack/manifests/rules/common/node-exporter-alerting.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2773 Create periodic job for perf-report-creator
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2840 Disable flapping alerts UnusualDiskReadWrite and job
  github/ci/services/prometheus-stack/manifests/rules/common/kubernetes-apps.yaml
  github/ci/services/prometheus-stack/manifests/rules/common/node-exporter-alerting.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2848 disable cdi apidocs job
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2847 Disable pull-kubevirt-apidocs for 0.59 & 1.0 branches
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2850 Remove k3d sriov periodic job as provider no longer exists
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2852 Use --all flag when cleaning up podman containers in bootstrap pod
  images/bootstrap/runner.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2854 Update preset bazel version to match kubevirt builder image
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2855 common-instancetypes: Add release-0.3 presubmits
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-0.3.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2857 CDI linter lane use golang container
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2858 Give aburdenthehand and xpivarc 'write' permissions to help out with kubevirt/kubevirt releases
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2860 Enable presubmit to check make apidocs
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes
