Repository kubevirt/project-infra, pull requests merged in 2023-01, with the labels that each got.

#2534 Update remaining jobs to use podman
  github/ci/prow-deploy/files/jobs/kubevirt/ansible-kubevirt-modules/ansible-kubevirt-modules-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2532 hco,presubmit: Update golang bootstrap image
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2530 Add check-provision-k8s-1.26-centos9
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2538 Fix bootstrap image version for arm64 workloads
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2539 Set 1.26 lanes to run on every PR
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  robots/pkg/kubevirt/cmd/remove/always_run.go
Labels: size/L, approved, lgtm, dco-signoff: yes

#2540 Build multiarch bootstrap image as part of postsubmit job
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  images/publish_multiarch_image.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#2541 Add periodic test lanes for new k8s-1.26-centos9 provider
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#2542 Set 1.26 lanes to gating
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2543 Enable reporting on ARM64 presubmits
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2546 Remove 1.23 kubevirt lanes
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  robots/pkg/kubevirt/cmd/remove/jobs.go
Labels: size/XL, approved, lgtm, dco-signoff: yes

#2548 ksd: remove the release-note plugin from ksd
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2547 Add hidden (always_run: false, optional: true) presubmit lanes for centos9
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#2551 Install Material theme to user-guide container
  images/kubevirt-user-guide/Dockerfile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2554 Update kubvirt builder image
  github/ci/prow-deploy/files/jobs/kubevirt/community/community-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  hack/update-jobs-with-latest-image.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#2555 Make prow-bump use pr-creator image
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2559 Make kubevirt fossa check optional due to failures
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2561 Enable PSA on 1.26 provision-check presubmits
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2552 `kubevirt get periodics/presubmits` : output html overview of prowjobs for kubevirt/kubevirt
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  robots/cmd/kubevirt/BUILD.bazel
  robots/cmd/kubevirt/README.md
  robots/cmd/kubevirt/main.go
  robots/cmd/kubevirtperiodics/BUILD.bazel
  robots/cmd/kubevirtperiodics/main.go
  robots/pkg/kubevirt/BUILD.bazel
  robots/pkg/kubevirt/cmd/BUILD.bazel
  robots/pkg/kubevirt/cmd/get/BUILD.bazel
  robots/pkg/kubevirt/cmd/get/get.go
  robots/pkg/kubevirt/cmd/get/periodics.go
  robots/pkg/kubevirt/cmd/get/periodics.gohtml
  robots/pkg/kubevirt/cmd/get/periodics_test.go
  robots/pkg/kubevirt/cmd/get/presubmits.go
  robots/pkg/kubevirt/cmd/get/presubmits.gohtml
  robots/pkg/kubevirt/root.go
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#2563 Add cri-o version 1.26 to kubevirt mirror
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2553 Cleanup of 1.23 kubevirt presubmit lanes and add 1.26 periodic root lanes
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#2358 Add pull-project-infra-test-github-ci-services
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2565 Add jcanocan tot the Kubevirt org
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2566 knmstate: Use podman for presubmit
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2567 Add /var/log/audit path to Arm64 e2e periodic lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2558 Add vm-console-proxy repository to kubevirt organization
  github/ci/prow-deploy/files/orgs.yaml
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2570 Remove k8s version from csi driver presubmits
  github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2572 Revert "knmstate: Use podman for presubmit"
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2557 Enable PSA on 1.26 lanes
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#2573 common-instancetypes: Switch merge_method to merge
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2574 Switch merge_methods of kubevirt/common-templates and kubevirt/containerdisks to merge
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2579 Restore 1.26 compute lane name
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2581 kubevirtci, k8s-1.26-ipv6: Remove presubmit job
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2583 Temporarily move pinc jobs to prow-workloads cluster
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.58.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2431 Update release-tool with --existing-branch cli arg for cutting tags out of specific branches
  releng/release-tool/release-tool.go
Labels: size/M, approved, lgtm, dco-signoff: yes

#2362 Update golang to 1.19.1
  .bazelversion
  Makefile
  WORKSPACE
  go.mod
  go.sum
  go_third_party.bzl
  robots/pkg/ci-usage-exporter/metrics/metrics_test.go
Labels: size/L, approved, lgtm, dco-signoff: yes
