Repository kubevirt/project-infra, pull requests merged in 2023-05, with the labels that each got.

#2739 Use make target for rehearse push
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/prow-rehearse-deployment.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2743 Move network kubevirt e2e lanes to the new workloads cluster
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.57.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.58.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#2735 Move CDI e2e lanes to the new workloads cluster
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits-1.34.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits-1.38.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits-1.43.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits-1.49.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2747 Increase max concurrency of vpgu e2e lane to 2
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2749 Revert "Increase max concurrency of vpgu e2e lane to 2 (#2747)"
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2750 Move containerdisks e2e jobs to new workloads cluster
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2753 Create publish job for test-report image
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2754 Skip reporting on the arm64 e2e jobs due to flaky lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2745 Bump base images for infra containers
  images/kubevirt-infra-bootstrap/Dockerfile
  images/prow-deploy/Dockerfile
  images/ruby/Dockerfile
  images/shared-images-controller/Containerfile
  images/vm-image-builder/Dockerfile
Labels: size/S, approved, lgtm, dco-signoff: yes

#2756 [HCO] start testing on k8s 1.26 and 1.27
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2759 [HCO] remove k8s 1.24 and 1.25 from main
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2751 Move hpp, kvp and csi prow jobs to new workloads cluster
  github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner/hostpath-provisioner-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-velero-plugin/kubevirt-velero-plugin-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-velero-plugin/kubevirt-velero-plugin-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2763 Move sig-network lanes for 0.58 back to old workloads cluster
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.58.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2746 Move kubevirtci prowjobs to new workloads cluster
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2766 Skip reporting on the failing fossa presubmit check
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2742 perf-report-creator: update regex and plot.go to include all graphs in one index.html
  robots/cmd/perf-report-creator/main.go
  robots/cmd/perf-report-creator/plot.go
Labels: size/L, ok-to-test, approved, lgtm, dco-signoff: yes

#2768 Fix skip report job config attribute
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2771 Create storage repo for performance data
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2775 mirror: Add kindest/node:v1.27.1
  hack/images_to_mirror.csv
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2778 docs: update ssp-operator description
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2779 Actually use ci-maintainers alias
  OWNERS
  OWNERS_ALIASES
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2765 Revert "Move sig-network lanes for 0.58 back to old workloads cluster…
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.58.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2770 kubevirtci, SR-IOV: Bump kind version and enable it
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2784 Add older versions of cri-o to mirror for backports
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2781 Move remaining prow jobs to the new workloads cluster
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits-v0.38.yaml
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits-v0.39.yaml
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits.yaml
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/ovs-cni/ovs-cni-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/ovs-cni/ovs-cni-presubmits-0.29.yaml
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/ovs-cni/ovs-cni-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubernetes-sigs/cluster-api-provider-kubevirt/cluster-api-provider-kubevirt-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/ansible-kubevirt-modules/ansible-kubevirt-modules-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/bridge-marker/bridge-marker-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/bridge-marker/bridge-marker-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cloud-provider-kubevirt/cloud-provider-kubevirt-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.76.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-0.1.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/controller-lifecycle-operator-sdk/controller-lifecycle-operator-sdk-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hostpath-provisioner-operator/hostpath-provisioner-operator-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubesecondarydns/kubesecondarydns-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.49.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.50.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.51.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.52.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.53.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.54.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.55.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.56.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.57.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.58.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/macvtap-cni/macvtap-cni-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/node-maintenance-operator/node-maintenance-operator-presubmits-release-0.9.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/terraform-provider-kubevirt/terraform-provider-kubevirt-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/vm-import-operator/vm-import-operator-presubmits.yaml
Labels: size/XL, approved, lgtm, dco-signoff: yes

#2774 perf-report-creator: modify to scrape sig-scale jobs in density cluster
  robots/cmd/perf-report-creator/main.go
Labels: size/M, ok-to-test, approved, lgtm, dco-signoff: yes

#2785 Increase sig-monitoring e2e test timeout
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2782 Make 1.27 sig lanes gating
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2790 Remove 1.24 kubevirt test prow jobs
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XL, approved, lgtm, dco-signoff: yes

#2792 Remove old prowjobs that target the old workloads cluster
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#2788 rehearse-plugin: checkout branch(es) from job spec
  external-plugins/rehearse/plugin/handler/handler.go
  external-plugins/rehearse/plugin/handler/handler_test.go
Labels: size/M, approved, lgtm, dco-signoff: yes

#2786 Update prow images, patch prow deployments to remove unnecessary mounts
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/branch-protector.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/cherrypicker_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/label-sync-kubevirt.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/label-sync-nmstate.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/crier_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/deck_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/ghproxy.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/hook_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/horologium_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/needs-rebase_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/prow_controller_manager_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/prowjob-crd/prowjob_customresourcedefinition.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/sinker_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/statusreconciler_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/tide_deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/crier_deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/deck_deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/hook_deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/prow_controller_manager_deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/sinker_deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/prow-exporter-deployment.yaml
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#2796 Remove old workload clusters deployment files
  github/ci/prow-arm-workloads/bootstrap.yml
  github/ci/prow-arm-workloads/hack/bootstrap.sh
  github/ci/prow-arm-workloads/hack/common.sh
  github/ci/prow-arm-workloads/hack/deploy.sh
  github/ci/prow-arm-workloads/inventory/prow-arm-workloads/group_vars/all/all.yml
  github/ci/prow-arm-workloads/inventory/prow-arm-workloads/group_vars/all/docker.yml
  github/ci/prow-arm-workloads/inventory/prow-arm-workloads/group_vars/etcd.yml
  github/ci/prow-arm-workloads/inventory/prow-arm-workloads/group_vars/k8s-cluster/addons.yml
  github/ci/prow-arm-workloads/inventory/prow-arm-workloads/group_vars/k8s-cluster/k8s-cluster.yml
  github/ci/prow-arm-workloads/inventory/prow-arm-workloads/group_vars/k8s-cluster/k8s-net-calico.yml
  github/ci/prow-arm-workloads/inventory/prow-arm-workloads/inventory.ini
  github/ci/prow-arm-workloads/roles/bootstrap/tasks/additional_kernel_modules.yml
  github/ci/prow-arm-workloads/roles/bootstrap/tasks/main.yml
  github/ci/prow-deploy/kustom/overlays/workloads-production/.gitignore
  github/ci/prow-deploy/kustom/overlays/workloads-production/kustomization.yaml
  github/ci/prow-deploy/kustom/overlays/workloads-production/resources/bootstrap.yaml
  github/ci/prow-deploy/kustom/overlays/workloads-production/resources/ingress-controller.yaml
  github/ci/prow-deploy/kustom/overlays/workloads-production/resources/metrics-server.yaml
  github/ci/prow-deploy/kustom/overlays/workloads-production/resources/multus-cni.yaml
  github/ci/prow-deploy/kustom/overlays/workloads-production/resources/place-holder.yaml
  github/ci/prow-deploy/kustom/overlays/workloads-production/resources/priority-classes.yaml
  github/ci/prow-deploy/kustom/overlays/workloads-production/resources/shared-images-controller.yaml
  github/ci/prow-deploy/vars/workloads-production/main.yml
  github/ci/prow-workloads/bootstrap.yml
  github/ci/prow-workloads/hack/bootstrap.sh
  github/ci/prow-workloads/hack/common.sh
  github/ci/prow-workloads/hack/deploy.sh
  github/ci/prow-workloads/inventory/prow-workloads/group_vars/all/docker.yml
  github/ci/prow-workloads/inventory/prow-workloads/group_vars/etcd.yml
  github/ci/prow-workloads/inventory/prow-workloads/group_vars/k8s-cluster/addons.yml
  github/ci/prow-workloads/inventory/prow-workloads/group_vars/k8s-cluster/k8s-cluster.yml
  github/ci/prow-workloads/inventory/prow-workloads/group_vars/k8s-cluster/k8s-net-calico.yml
  github/ci/prow-workloads/inventory/prow-workloads/inventory.ini
  github/ci/prow-workloads/roles/bootstrap/tasks/additional_kernel_modules.yml
  github/ci/prow-workloads/roles/bootstrap/tasks/main.yml
Labels: size/XXL, approved, lgtm, dco-signoff: yes
