Repository kubevirt/project-infra, pull requests merged in 2023-09, with the labels that each got.

#2969 Remove check provision job for k8s-1.25 provider
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2966 Delete cgroupsv2 test jobs, since >=1.26 cgroups v2 is default
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#2968 Switch docker to podman in prowjob scripts
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2975 Use correct container for fcos image, rename dir
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  images/fcos/Dockerfile
  images/fedora-coreos-kubevirt/Dockerfile
Labels: size/S, approved, lgtm, dco-signoff: yes

#2973 Bump performance and network single stack presubmits to use 1.27
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2974 Bump sig-performance periodics to use 1.27
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2978 Add cri-o version 1.28 to the kubevirt mirror
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2972 Update kubevirtci to use podman based golang image
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2981 Update the prow-deploy test job to use podman and latest kind
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirtci-testing/resources/ingress-nginx-controller.yaml
  github/ci/prow-deploy/molecule/default/Dockerfile.j2
  github/ci/prow-deploy/molecule/default/molecule.yml
  github/ci/prow-deploy/molecule/default/prepare.yml
  github/ci/prow-deploy/molecule/default/smoke_tests.yml
  github/ci/prow-deploy/molecule/default/vars/kubevirtci-testing.yml
  images/prow-deploy/Dockerfile
  images/prow-deploy/requirements.txt
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#2984 Switch publish kubevirtci prowjob back to docker
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2987 cnao, release 0.89: Add presubmits
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.89.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#2986 Upgrade shared-images-controller to latest podman version
  images/shared-images-controller/go.mod
  images/shared-images-controller/go.sum
Labels: size/M, approved, lgtm, dco-signoff: yes

#2991 Fix typo in cluster name for kubevirt build presubmit
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2994 hco: require fresher golang env
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.10.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2995 Temporarily move prow deploy test lane back to old cluster
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2950 Generalize flakefinder for future gerrit usage
  go.mod
  robots/cmd/flakefinder/BUILD.bazel
  robots/cmd/flakefinder/main.go
  robots/cmd/flakefinder/report.go
  robots/pkg/flakefinder/BUILD.bazel
  robots/pkg/flakefinder/api/BUILD.bazel
  robots/pkg/flakefinder/api/types.go
  robots/pkg/flakefinder/downloader.go
  robots/pkg/flakefinder/downloader_test.go
  robots/pkg/flakefinder/flakefinder.go
  robots/pkg/flakefinder/github/BUILD.bazel
  robots/pkg/flakefinder/github/github.go
Labels: size/L, approved, lgtm, dco-signoff: yes

#2997 test-label-analyzer: validate command line args
  robots/cmd/test-label-analyzer/cmd/filter/matching-tests.go
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2999 Add flakefinder urls to flake-stats report per day headlines
  robots/cmd/flake-stats/flake-stats.gohtml
  robots/cmd/flake-stats/main.go
Labels: size/M, approved, lgtm, dco-signoff: yes

#2948 Generate support matrix for kubevirt/kubevirt
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
  robots/pkg/kubevirt/cmd/get/BUILD.bazel
  robots/pkg/kubevirt/cmd/get/get.go
  robots/pkg/kubevirt/cmd/get/release-model.go
  robots/pkg/kubevirt/cmd/get/support-matrix.go
  robots/pkg/kubevirt/cmd/get/support-matrix.gomd
Labels: size/XL, approved, lgtm, dco-signoff: yes

#3000 Fix update-support-matrix job for sig-release
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2990 Deploy greenhouse and docker-mirror-proxy to new control plane cluster
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/kustom/components/docker-mirror-proxy/pv/patches/JsonRFC6902/deployment.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/kustomization.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/patches/JsonRFC6902/prow-namespace.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/patches/StrategicMerge/docker-mirror_deployment.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/resources/admin-rbac.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/resources/bootstrap.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/resources/docker-mirror-proxy_pvc.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/yq_scripts/README
  github/ci/prow-deploy/vars/kubevirt-prow-control-plane/main.yml
Labels: size/L, approved, lgtm, dco-signoff: yes
