Repository kubevirt/project-infra, pull requests merged in 2023-08, with the labels that each got.

#2913 HCO: Add tests for the new release-1.10 branch
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.10.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2916 common-instancetypes: Increase node memory in functest
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2917 Rename kubernetes.kubevirt repo to kubevirt.core
  github/ci/prow-deploy/files/orgs.yaml
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2921 Disable required status checks in kubevirt.core
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2923 Add k8s-seccomp-generator repository and team
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2906 Bump podman to v4.6 in shared-images-controller
  images/shared-images-controller/go.mod
  images/shared-images-controller/go.sum
Labels: size/L, approved, lgtm, dco-signoff: yes

#2925 Add Nithish Karthik as a Community Member
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, ok-to-test, approved, lgtm, dco-signoff: yes

#2928 k8s-seccomp-generator: update maintainers
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2930 Add anchor link to each test
  robots/cmd/flake-stats/flake-stats.gohtml
  robots/cmd/flake-stats/main.go
Labels: size/M, approved, lgtm, dco-signoff: yes

#2936 Run check-tests-for-flakes in parallel, set memory
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2937 Add avlitman to kubevirt members
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, ok-to-test, approved, lgtm, dco-signoff: yes

#2938 Update kubevirt-csi-driver presubmit golang to 1.20
  github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2939 [testgrid]: adding sig-monitoring lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2944 Skip ceph wffc lane on release branches
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2942 ssp-operator: Archive kubevirt-ssp-operator & kubevirt-template-validator
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2949 [Fix] Nithish Karthik - Update Github Handle
  github/ci/prow-deploy/files/orgs.yaml
Labels: size/XS, ok-to-test, approved, lgtm, dco-signoff: yes

#2955 Turn `always_run` off for 1.25 and on for 1.28
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2951 Add ARG ARCH in Dockerfile of bootstrap-legacy and golang-legacy
  images/bootstrap-legacy/Dockerfile
  images/golang-legacy/Dockerfile
Labels: size/S, approved, lgtm, dco-signoff: yes

#2958 Set check-provision-k8s-1.25 to always-run false
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2961 project-infra postsubmit: increase the memory limit for build multiarch legacy images
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2962 Increase timeout for publish bootstrap legacy job
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2934 Add process document and PR template for adding repos
  .github/PULL_REQUEST_TEMPLATE/add_repo.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  docs/how-to-add-a-new-repository.md
Labels: size/L, approved, lgtm, dco-signoff: yes

#2957 Reenable FOSSA license check
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2963 CDI push builder images on release branches
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2953 Add labels for sigs
  github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2965 Remove PR pending from reports doc as flake stats merged
  docs/reports.md
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2933 Move orgs.yaml to its own folder
  docs/debugging-resources/prow.md
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/prow-deploy/files/orgs.yaml
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Labels: size/XXL, approved, lgtm, dco-signoff: yes
