Repository kubevirt/project-infra, pull requests merged in 2023-04, with the labels that each got.

#2687 Migrate kubevirtci check-provision jobs to new workloads cluster
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#2696 Add responses on rehearse
  external-plugins/rehearse/plugin/handler/handler.go
  external-plugins/rehearse/plugin/handler/handler_test.go
  github/ci/prow-deploy/kustom/base/manifests/local/prow-rehearse-deployment.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#2697 Move CNAO presubmits to new cluster
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2700 Update kubevirtci presubmit memory requests to match e2e jobs
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2663 add a subcommand to scrape json results from performance jobs
  go.mod
  go.sum
  robots/cmd/perf-report-creator/README.md
  robots/cmd/perf-report-creator/api.go
  robots/cmd/perf-report-creator/main.go
  robots/cmd/perf-report-creator/plot.go
  robots/cmd/perf-report-creator/record.go
  robots/pkg/querier/queries.go
Labels: size/XXL, ok-to-test, approved, lgtm, dco-signoff: yes

#2701 Remove check provision lane for 1.25 PSA as no longer needed
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2706 Move vgpu workloads to the new workloads cluster
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2707 Move release sig-compute and sig-operator lanes to new workloads cluster
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.49.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.50.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.51.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.52.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.53.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.54.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.55.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.56.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.57.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.58.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#2708 Bump podman to v4.5.0 in shared images controller
  images/shared-images-controller/go.mod
  images/shared-images-controller/go.sum
Labels: size/L, approved, lgtm, dco-signoff: yes

#2702 kubevirt: Add publish-kubevirt-builder postsubmit job
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2709 Move project-infra prowjobs from old workloads cluster
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2721 Revert move of prow-deploy-test
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2716 Move kubevirtci vm provider check provisions back to old cluster
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2718 Increase memory request for test-github-ci-services
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2719 sriov-passthru-cni: Enable allocation restriction of system reserved PFs
  cni-plugins/sriov-passthrough-cni/README.md
  cni-plugins/sriov-passthrough-cni/plugin/sriov-passthrough-cni
Labels: size/S, approved, lgtm, dco-signoff: yes

#2717 Update bazel WORKSPACE, add missing files
  WORKSPACE
  external-plugins/rehearse/plugin/handler/BUILD.bazel
  go_third_party.bzl
  images/shared-images-controller/BUILD.bazel
  robots/cmd/perf-report-creator/BUILD.bazel
  robots/pkg/flakefinder/BUILD.bazel
Labels: size/L, approved, lgtm, dco-signoff: yes

#2694 Add presubmits and periodics for k8s 1.27
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#2713 Add the help plugin to a number of projects
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2720 feat(virtctl): Add individual presubmit jobs for artifacts
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#2722 Move sig storage e2e jobs for main branch to new cluster
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2727 containerdisks: Always run cirros pipeline
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2724 sriov-passtru-cni: Use file instead of env var for reserved ifaces
  cni-plugins/sriov-passthrough-cni/README.md
  cni-plugins/sriov-passthrough-cni/plugin/sriov-passthrough-cni
Labels: size/S, approved, lgtm, dco-signoff: yes

#2730 Improve plugin help for rehearse plugin
  external-plugins/rehearse/plugin/main.go
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2715 Add a custom dependabot for our projects
  robots/cmd/dependabot/BUILD.bazel
  robots/cmd/dependabot/main.go
  robots/cmd/job-config-validator/BUILD.bazel
  robots/cmd/job-config-validator/main.go
  robots/pkg/dependabot/BUILD.bazel
  robots/pkg/dependabot/api/BUILD.bazel
  robots/pkg/dependabot/api/api.go
  robots/pkg/dependabot/api/testdata/kubevirt.json
  robots/pkg/dependabot/api/testdata/project-infra.json
  robots/pkg/dependabot/dependabot.go
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#2729 Introduce check for bazel configurations
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2732 Create dependabot job
  Makefile
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2731 Move SRIOV e2e prow jobs to the new cluster
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.49.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.50.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.51.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.52.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.53.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.54.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.55.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.56.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.57.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.58.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#2680 Test tooling: introduce test-label-analyzer cli - generate a page of quarantined tests for kubevirt/kubevirt
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  robots/cmd/test-label-analyzer/BUILD.bazel
  robots/cmd/test-label-analyzer/Makefile
  robots/cmd/test-label-analyzer/README.md
  robots/cmd/test-label-analyzer/cmd/BUILD.bazel
  robots/cmd/test-label-analyzer/cmd/filter.go
  robots/cmd/test-label-analyzer/cmd/root.go
  robots/cmd/test-label-analyzer/cmd/stats.go
  robots/cmd/test-label-analyzer/cmd/stats.gohtml
  robots/cmd/test-label-analyzer/cmd/stats_test.go
  robots/cmd/test-label-analyzer/cmd/test_suite_test.go
  robots/cmd/test-label-analyzer/cmd/testdata/BUILD.bazel
  robots/cmd/test-label-analyzer/cmd/testdata/migration_test.go.ginkgooutline.json
  robots/cmd/test-label-analyzer/cmd/testdata/simple_test.go
  robots/cmd/test-label-analyzer/main.go
  robots/pkg/test-label-analyzer/BUILD.bazel
  robots/pkg/test-label-analyzer/config.go
  robots/pkg/test-label-analyzer/ginkgo.go
  robots/pkg/test-label-analyzer/stats.go
  robots/pkg/test-label-analyzer/stats_test.go
  robots/pkg/test-label-analyzer/test_suite_test.go
  robots/pkg/test-label-analyzer/time.go
  robots/pkg/test-label-analyzer/time_test.go
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#2736 Move CNAO release lanes to the new workloads cluster
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.53.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.58.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.65.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.79.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.85.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2737 rehearse plugin: fix comparison of jobs
  WORKSPACE
  external-plugins/rehearse/plugin/handler/BUILD.bazel
  external-plugins/rehearse/plugin/handler/handler.go
  external-plugins/rehearse/plugin/handler/handler_test.go
  go.mod
  go.sum
  go_third_party.bzl
Labels: size/L, approved, lgtm, dco-signoff: yes
