Repository kubevirt/project-infra, pull requests merged in 2023-02, with the labels that each got.

#2578 Make 1.26 PSA network lane gating
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2588 Update kubevirt periodics job and project-infra to 1.19
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2584 Make 1.26 PSA storage lane gating
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2590 Remove 1.23 cgroupsv2 periodic lanes
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2591 kubevirt get presubmits: add env var list
  robots/pkg/kubevirt/cmd/get/presubmits.gohtml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2595 Temporarily move 0.53 jobs to prow-workloads due to image cache issue
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.53.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2575 Add workaround for cri-o version 1.24
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
  hack/mirror-crio.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#2582 common-instancetypes: Add basic functional test coverage
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2594 Release configs for kubevirt/kubevirt release branch release-0.59
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#2596 Add container env variable output to periodics
  robots/pkg/kubevirt/cmd/get/periodics.gohtml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2598 Remove PSA optional jobs
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#2599 Convert periodic into postsubmit
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2560 Create dequarantine robot
  go.mod
  hack/test-report.sh
  robots/cmd/test-report/BUILD.bazel
  robots/cmd/test-report/README.md
  robots/cmd/test-report/cmd/BUILD.bazel
  robots/cmd/test-report/cmd/dequarantine/BUILD.bazel
  robots/cmd/test-report/cmd/dequarantine/dequarantine.go
  robots/cmd/test-report/cmd/dequarantine/execute.go
  robots/cmd/test-report/cmd/dequarantine/execute_test.go
  robots/cmd/test-report/cmd/dequarantine/report.go
  robots/cmd/test-report/cmd/dequarantine/testdata/dequarantine-report-data.json
  robots/cmd/test-report/cmd/dequarantine/testdata/no-results.json
  robots/cmd/test-report/cmd/dequarantine/testdata/no-test-results.json
  robots/cmd/test-report/cmd/dequarantine/testdata/one-test-passing.json
  robots/cmd/test-report/cmd/dequarantine/testdata/some-tests-skipped-but-two-passing-in-skipped.json
  robots/cmd/test-report/cmd/dequarantine/testdata/some-tests-skipped.json
  robots/cmd/test-report/cmd/dequarantine/testdata/test-failing.json
  robots/cmd/test-report/cmd/dequarantine/testdata/test-fixed.json
  robots/cmd/test-report/cmd/dequarantine/testdata/test-passing.json
  robots/cmd/test-report/cmd/dequarantine/testdata/test-some-passing-some-failing.json
  robots/cmd/test-report/cmd/execution/BUILD.bazel
  robots/cmd/test-report/cmd/execution/compute-config.yaml
  robots/cmd/test-report/cmd/execution/default-config.yaml
  robots/cmd/test-report/cmd/execution/execution.go
  robots/cmd/test-report/cmd/execution/execution_test.go
  robots/cmd/test-report/cmd/execution/network-config.yaml
  robots/cmd/test-report/cmd/execution/ssp-config.yaml
  robots/cmd/test-report/cmd/execution/storage-config.yaml
  robots/cmd/test-report/cmd/execution/test-report.gohtml
  robots/cmd/test-report/cmd/root.go
  robots/cmd/test-report/main.go
  robots/pkg/test-report/test_report.go
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#2602 Add presubmit for job-config-validator
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2603 Update go.mod for job-config-validator
  go.mod
  go.sum
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2604 Update podman version to latest in shared-images-controller
  images/shared-images-controller/go.mod
  images/shared-images-controller/go.sum
Labels: size/XL, approved, lgtm, dco-signoff: yes

#2605 Remove unused presubmit lane for testing against perf cluster
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2607 release-configs: remove usage of Bazel remote cache
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.57.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.58.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#2609 common-instancetypes: Fix run_if_changed for func test
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2613 common-instancetypes: rework run_if_changed one final time
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2615 Set check-provision-k8s-1.26-centos9 to required
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2610 Make 1.26 CentOS Stream 9 based provider default for gating 1.26 lanes, remove explicit centos9 lanes
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#2606 Add template prowjobs for testing against SEV cluster
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#2611 release-0.59: backport switch for 1.26 gating lanes to CentOS Stream 9 with PSA enabled
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#2619 containerdisks - Mark both presubmits as required and increase the golang version to 1.19
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#2623 Merge split operator lanes
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2626 terraform-provider-kubevirt: e2e test changes
  github/ci/prow-deploy/files/jobs/kubevirt/terraform-provider-kubevirt/terraform-provider-kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#2616 Update 1.26 periodics to use 1.26 CentOS 9 provider
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#2617 Add csv output to kubevirt get
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  robots/pkg/kubevirt/cmd/get/BUILD.bazel
  robots/pkg/kubevirt/cmd/get/periodics.go
  robots/pkg/kubevirt/cmd/get/periodics.gocsv
  robots/pkg/kubevirt/cmd/get/presubmits.go
  robots/pkg/kubevirt/cmd/get/presubmits.gocsv
Labels: size/L, approved, lgtm, dco-signoff: yes

#2622 Add keepalive for sshuttle tunnel in SEV lanes
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#2632 Update podman to v4.4.2 in shared-images-controller
  images/shared-images-controller/go.mod
  images/shared-images-controller/go.sum
Labels: size/S, approved, lgtm, dco-signoff: yes

#2638 Remove bugzilla search queries from ci-search statefulset
  github/ci/services/ci-search/manifests/full.yaml
  github/ci/services/ci-search/patches/statefulset.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes
