Repository kubevirt/project-infra, pull requests merged in 2024-01, with the labels that each got.

#3156 common-instancetypes: Use bump-common-instancetypes.sh
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3124 fix, botreview: handle deleted files in kubevirtci-bump, improve commenting
  external-plugins/botreview/review/BUILD.bazel
  external-plugins/botreview/review/bump_kubevirtci.go
  external-plugins/botreview/review/bump_kubevirtci_test.go
  external-plugins/botreview/review/image_update.go
  external-plugins/botreview/review/image_update_test.go
  external-plugins/botreview/review/prow_autobump.go
  external-plugins/botreview/review/result.go
  external-plugins/botreview/review/result_test.go
  external-plugins/botreview/review/review.go
  external-plugins/botreview/review/review_test.go
  external-plugins/botreview/review/testdata/kubevirt/ci-bump-remove-provider-local/bump-kci.patch00
  external-plugins/botreview/review/testdata/kubevirt/ci-bump-remove-provider-local/bump-kci.patch01
  external-plugins/botreview/review/testdata/kubevirt/ci-bump-remove-provider-local/bump-kci.patch02
  external-plugins/botreview/review/testdata/kubevirt/ci-bump-remove-provider-local/bump-kci.patch03
  external-plugins/botreview/review/testdata/kubevirt/ci-bump-remove-provider-local/bump-kci.patch04
  external-plugins/botreview/review/testdata/kubevirt/ci-bump-remove-provider-local/bump-kci.patch05
  external-plugins/botreview/review/testdata/kubevirt/eviction-strategy-doc/eviction-strategy-doc.patch0
  external-plugins/botreview/review/testdata/kubevirt/eviction-strategy-doc/eviction-strategy-doc.patch1
  external-plugins/botreview/review/testdata/kubevirt/eviction-strategy-doc/eviction-strategy-doc.patch2
  external-plugins/botreview/review/testdata/kubevirt/eviction-strategy-doc/eviction-strategy-doc.patch3
  external-plugins/botreview/review/testdata/kubevirt/eviction-strategy-doc/eviction-strategy-doc.patch4
  external-plugins/botreview/review/testdata/kubevirt/fix-containerdisks-migration/fix-containerdisks-migrations.patch00
  external-plugins/botreview/review/testdata/kubevirt/fix-containerdisks-migration/fix-containerdisks-migrations.patch01
  external-plugins/botreview/review/testdata/kubevirt/fix-containerdisks-migration/fix-containerdisks-migrations.patch02
  external-plugins/botreview/review/testdata/kubevirt/fix-containerdisks-migration/fix-containerdisks-migrations.patch03
  external-plugins/botreview/review/testdata/kubevirt/fix-containerdisks-migration/fix-containerdisks-migrations.patch04
  external-plugins/botreview/review/testdata/kubevirt/fix-containerdisks-migration/fix-containerdisks-migrations.patch05
  external-plugins/botreview/review/testdata/kubevirt/fix-containerdisks-migration/fix-containerdisks-migrations.patch06
  external-plugins/botreview/review/testdata/kubevirt/fix-containerdisks-migration/fix-containerdisks-migrations.patch07
  external-plugins/botreview/review/testdata/kubevirt/fix-containerdisks-migration/fix-containerdisks-migrations.patch08
  external-plugins/botreview/review/testdata/kubevirt/fix-containerdisks-migration/fix-containerdisks-migrations.patch09
  external-plugins/botreview/review/testdata/kubevirt/fix-containerdisks-migration/fix-containerdisks-migrations.patch10
  external-plugins/botreview/review/testdata/kubevirt/fix-containerdisks-migration/fix-containerdisks-migrations.patch11
  external-plugins/botreview/review/testdata/kubevirt/fix-containerdisks-migration/fix-containerdisks-migrations.patch12
  external-plugins/botreview/review/testdata/kubevirt/fix-containerdisks-migration/fix-containerdisks-migrations.patch13
  external-plugins/botreview/review/testdata/kubevirt/fix-containerdisks-migration/fix-containerdisks-migrations.patch14
  external-plugins/botreview/review/testdata/kubevirt/fix-containerdisks-migration/fix-containerdisks-migrations.patch15
  external-plugins/botreview/review/testdata/kubevirt/fix-containerdisks-migration/fix-containerdisks-migrations.patch16
  go.mod
  go.sum
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#3151 Remove filtering of needs-ok-to-test from retester query
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3154 Set the kubevirtci 1.29 presubmit lane to be required
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3152 Add sysctl to bootstrap image as needed by runner script
  images/bootstrap/Dockerfile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3159 Add step to disable unsupported lanes when enabling new lanes
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3161 cnao, release 0.91: Add presubmits
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.91.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#3163 prow-deploy: fix context name in reconcile webhook task
  github/ci/prow-deploy/tasks/deploy.yml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3145 project-infra, labels: add group to allow applying labels
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3170 prow-deploy: Remove deployment files that are specific to the old cluster
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/.gitignore
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/kustomization.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/crier_deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/deck-rolebinding-subject-prow-name.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/deck_deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/gcsweb-deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/ghproxy_deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/hook_deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/prow-jobs-namespace.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/prow-jobs-rolebinding-rules.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/prow-namespace.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/prow-rehearse-deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/prow_controller_manager_deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/pushgateway_deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/rolebinding-subject-prow-name-deck.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/rolebinding-subject-prow-name-tide.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/rolebinding-subject-prow-namespace.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/sinker_deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/JsonRFC6902/tide_deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/StrategicMerge/crier_role.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/StrategicMerge/deck_role.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/StrategicMerge/docker-mirror_deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/StrategicMerge/ghproxy.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/patches/StrategicMerge/prow_controller_manager_role.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/bootstrap.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/ci-usage-exporter-deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/ci-usage-exporter-service.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/docker-mirror-proxy_pvc.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/hook-rbac.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/horologium-rbac.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/prow-exporter-deployment.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/prow-exporter-rbac.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/prow-exporter-service.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/resources/sinker-rbac.yaml
  github/ci/prow-deploy/kustom/overlays/ibmcloud-production/yq_scripts/README
  github/ci/prow-deploy/vars/ibmcloud-production/main.yml
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#3165 kubevirt,periodics: update rootful lanes to 1.29
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3131 botreview, strategy: add kubevirt uploader
  external-plugins/botreview/review/BUILD.bazel
  external-plugins/botreview/review/kubevirt_uploader.go
  external-plugins/botreview/review/kubevirt_uploader_test.go
  external-plugins/botreview/review/result.go
  external-plugins/botreview/review/review.go
  external-plugins/botreview/review/review_test.go
  external-plugins/botreview/review/testdata/kubevirt/uploader/uploader-autoupdate.patch00
Labels: size/XL, approved, lgtm, dco-signoff: yes

#3171 HCO: add 1.28 lane, remove 1.26
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3103 plugins: Introduce phased plugin
  docs/infrastructure-components.md
  external-plugins/phased/Makefile
  external-plugins/phased/plugin/BUILD.bazel
  external-plugins/phased/plugin/handler/BUILD.bazel
  external-plugins/phased/plugin/handler/handler.go
  external-plugins/phased/plugin/main.go
  external-plugins/phased/plugin/phased_suite_test.go
  external-plugins/phased/plugin/phased_test.go
  external-plugins/phased/plugin/server/BUILD.bazel
  external-plugins/phased/plugin/server/eventsserver.go
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
  github/ci/prow-deploy/kustom/base/kustomization.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/prow-phased-deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/prow-phased-service.yaml
  images/phased
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#3172 Update multus v4 lanes to test against kubernetes 1.29
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3176 kubevirt,presubmits: make 1.26 lanes optional
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3180 prow-deploy, fix: Role and RoleBinding for statusreconciler
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/statusreconciler_rbac.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/resources/admin-rbac.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3183 phased plugin: Use commenter bot token
  github/ci/prow-deploy/kustom/base/manifests/local/prow-phased-deployment.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3179 phased plugin: Add intro to bot comments
  external-plugins/phased/plugin/handler/handler.go
  external-plugins/phased/plugin/phased_test.go
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3184 phased: Enable run_before_merge for phase 2 jobs
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3136 sig-release: create upcoming-changes.md periodically
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  releng/feature-announce/BUILD.bazel
  releng/feature-announce/feature-announce.go
  releng/feature-announce/feature-announce_test.go
  releng/feature-announce/upcoming-changes.gomd
Labels: size/XL, approved, lgtm, dco-signoff: yes

#3181 kubevirt,s390x: Add optional presubmit to test s390x crossbuild of kubevirt
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3187 kubevirt,presubmits: remove bump-kubevirtci and sev presubmits
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.56.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.57.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.58.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.1.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#3182 Update golang to 1.21.6
  WORKSPACE
  external-plugins/botreview/review/review_test.go
  go.mod
  images/golang/Dockerfile
Labels: size/S, approved, lgtm, dco-signoff: yes

#3189 kubevirt,presubmits: Make 1.29 lanes required
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3192 Add prow control-plane metrics dashboard
  github/ci/services/grafana/manifests/grafana.yaml
Labels: size/XL, approved, lgtm, dco-signoff: yes

#3199 phased plugin: Update image
  github/ci/prow-deploy/kustom/base/manifests/local/prow-phased-deployment.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3195 kubevirt,presubmits: increase memory requests for prow-control-plane jobs
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3178 kubevirt, presubmit: Make k8s-1.27/1.28 lanes phase2
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3205 presubmits: Fix phases
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3204 Fix flag for feature-announce call
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3185 prow, test runtimes: push test runtimes for jobs to pushgateway
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/services/grafana/manifests/grafana.yaml
  robots/cmd/push-test-metrics/BUILD.bazel
  robots/cmd/push-test-metrics/README.md
  robots/cmd/push-test-metrics/heatmap.png
  robots/cmd/push-test-metrics/main.go
  robots/cmd/push-test-metrics/test_time.png
Labels: size/XL, approved, lgtm, dco-signoff: yes

#3206 common-instancetypes: Add release version to job names
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-0.1.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-0.3.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-0.4.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3200 presubmits: Bump ipv6 lane to k8s-1.29
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3209 Fix kubevirt push-test-metrics job
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3211 Remove omeryahud from ssp team
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3201 HCO: Add tests for the new release-1.11 branch
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.11.yaml
Labels: size/M, ok-to-test, approved, lgtm, dco-signoff: yes

#3212 kubevirt: Remove test lanes using the older k8s-1.26 provider
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#3214 containerdisks: Update to golang 1.21.6
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3218 Remove 'codingben' from the kubevirt organization
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/OWNERS
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/OWNERS
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-tekton-tasks/OWNERS
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3215 kubevirt,presubmits: set monitoring lane to trigger manually
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3220 Revert "Remove 'codingben' from the kubevirt org"
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3222 containerdisks: Drop rhcos test lane
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3223 Remove emeritus admins
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3224 cnao, presubmits: Convert multus-dynamic-networks to required
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3208 kubevirt, presubmits: Convert more jobs to phase 2
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3210 Fix prow job load dashboard
  github/ci/services/grafana/manifests/grafana.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes
