Repository kubevirt/project-infra, pull requests merged in 2024-12, with the labels that each got.

#3795 KubeSecondaryDNS: Nominate Or Shoval for approver
  github/ci/prow-deploy/files/jobs/kubevirt/kubesecondarydns/OWNERS
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3784 periodics: Job to cleanup leftover machines in the Google Cloud account
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  hack/gcp-cluster-deprovision.sh
Labels: size/L, approved, lgtm, dco-signoff: yes

#3776 per-test-execution: add html report
  docs/reports.md
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  robots/cmd/per-test-execution/BUILD.bazel
  robots/cmd/per-test-execution/README.md
  robots/cmd/per-test-execution/main.go
  robots/cmd/per-test-execution/main_test.go
  robots/cmd/per-test-execution/per-test-execution-top-x.gohtml
Labels: size/XL, approved, lgtm, dco-signoff: yes

#3796 kubevirt, presubmits: Temporarily switch s390x tests to optional
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.4.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3797 kubesecondarydns, presubmits: Add build and unit-tests for s390x
  github/ci/prow-deploy/files/jobs/kubevirt/kubesecondarydns/kubesecondarydns-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3799 kubevirtci,presubmit: Remove unnecessary dind preset from kind presubmit lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3798 Revert "kubevirt, presubmits: Temporarily switch s390x tests to optional (#3796)
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.4.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3802 etcd in mem for non CSI lane as well
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3804 kubevirt,performance: Bump presubmit and periodic performance lanes to kubernetes v1.31
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  robots/cmd/perf-report-creator/graph.sh
  robots/cmd/perf-report-creator/scrape.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#3800 ci-search: Increase max-age for results to 28 days
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/services/ci-search/patches/statefulset.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3803 images: Fix build of kubevirt.github.io image
  images/kubevirt-kubevirt.github.io/Dockerfile
  images/kubevirt-kubevirt.github.io/Gemfile
  images/kubevirt-kubevirt.github.io/Rakefile
Labels: size/S, approved, lgtm, dco-signoff: yes

#3801 preset,cleanup: Remove dind preset which is no longer used by these project-infra prow jobs
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3744 bootstrap: Update to fedora 41 base image
  images/bootstrap/Containerfile
  images/golang/Containerfile
  images/pr-creator/Containerfile
  images/publish_multiarch_image.sh
  images/vm-image-builder/Containerfile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3809 monitoring,grafana: add links to prow and testgrid
  github/ci/services/grafana/manifests/grafana.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3813 periodics: Increase deprovisioning timeout to 60 mins
  hack/gcp-cluster-deprovision.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3816 kubevirtci,presubmit: Move failing check-provision-alpine-with-test-tooling to optional
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3815 kubevirtci,presubmit: Add check for new kind-1.31 provider
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3820 skip-review: add for kubevirtci minor version bump
  docs/labels.md
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3811 Make some critical CDI lanes required
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3819 Add export PLATFORMS=all to post-submit jobs for bridge-marker
  github/ci/prow-deploy/files/jobs/kubevirt/bridge-marker/bridge-marker-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3823 per-test-execution: run with set k8s version
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  robots/cmd/per-test-execution/main.go
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3812 Fix repeated access token generation for gcs calls in s390x
  images/bootstrap/gcs_restapi.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3830 kubevirt,presubmit: Enable k8s-1.32 lanes to always run and remove old k8s-1.29 lanes
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#3831 kubevirtci,presubmit: Remove the check-provision job for k8s-1.29
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3566 Prow jobs for publishing k8s provider multi arch images
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes, sig/ci

#3817 chore:(common-instancetypes): Add periodic and specify golang version
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3835 chore(common-instancetypes): Bump builder to v20241217-0005325
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3838 chore(common-instancetypes): Add tests lanes for CentOS Stream 10
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3825 project-infra: add make targets lint and coverage
  .golangci.yaml
  Makefile
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  hack/lint.sh
  releng/release-tool/release-tool.go
  robots/pkg/kubevirt/cmd/get/support-matrix.go
Labels: size/L, approved, lgtm, dco-signoff: yes

#3847 golangci-lint: disallow automatic updating of go.mod
  .golangci.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3848 chore(common-instancetypes): Add test lane for CentOS Stream 10 in release 1.2
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.2.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3856 Add HCO presbmit lanes for branch release-1.14
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.14.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3857 HCO: Add new lane for k8s-1.32
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3829 kubemacpool: Add stable branch release-0.45 lane
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits-v0.45.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3858 cnao: Add stable release-0.97 branch presubmit
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.97.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#3806 kubevirt,monitoring: Update monitoring presubmit to v1.31 and add periodic monitoring lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3861 HCO: bump golang to 1.23
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes
