Repository kubevirt/project-infra, pull requests merged in 2024-06, with the labels that each got.

#3450 image,cache: Disable images cached for e2e jobs
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3451 image,cache: Disable image cache for e2e jobs
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: size/XS, dco-signoff: yes

#3452 image,cache: Enable the in cluster container image cache
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3455 labels: Add wg/ipam group label
  docs/labels.md
  github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3457 kubevirt, goveralls, releases: skip reporting
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.1.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3453 prow, e2e, monitoring: add failure rate panel
  github/ci/services/grafana/manifests/grafana.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#3446 bootstrap: update to Fedora 40
  images/bootstrap/Dockerfile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3458 Revert "labels: Add wg/ipam group label (#3455)"
  docs/labels.md
  github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3464 images,golang: Bump go version 1.22.2
  images/golang/Dockerfile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3463 prow, referee, metrics: update metrics on open/close
  external-plugins/referee/metrics/retests.go
  external-plugins/referee/metrics/retests_test.go
  external-plugins/referee/server/server.go
Labels: size/M, approved, lgtm, dco-signoff: yes

#3467 periodic,docker-proxy: Add check for docker mirror proxy CA certificate expiration
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  hack/check-docker-proxy-ca-cert.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#3469 prow, external-plugin, referee: fix instance
  github/ci/services/grafana/manifests/grafana.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3470 prow, tide, priority: add configuration
  docs/labels.md
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3471 doc: document how to renew the docker-mirror-proxy CA certificate
  docs/how-to-renew-docker-mirror-proxy-ca-cert.md
  hack/check-docker-proxy-ca-cert.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#3472 Release configs for kubevirt/kubevirt release branch release-1.3
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.3.yaml
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#3476 vm-image-builder: update vm-image-builder for s390x
  images/vm-image-builder/Dockerfile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3474 add periodic s390x cross-build nightly job.
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3477 kubevirt,v1.3: Update required jobs for v1.3 to always run
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.3.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3475 periodic: Update docker proxy CA cert check to run on workloads cluster
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3479 kubevirt,presubmit: Add optional presubmit lane to run fuzz testing
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3459 add periodic prow job to run on s390x cluster.
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3484 kubevirt,presubmit: Enable vgpu presubmits and set to required
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.1.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.3.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3483 kubevirt,presubmits: Remove bazel cache from v1.3 presubmits
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.3.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3485 bootstrap: Ignore podman warning for deprecation of cgroups v1
  images/bootstrap/runner.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3490 kubevirt,s390x: Enable s390x cross compilation build to always run
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3492 prow: Add ipam-extensions basic config
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3487 Add virt-api and virt-controller resource utilization to benchmarks
  robots/cmd/perf-report-creator/graph.sh
  robots/cmd/perf-report-creator/scrape.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#3481 common-instancetypes-periodics: Add initial job for release-1.1
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-periodics.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3498 kubevirt,presubmits: Remove goveralls jobs from recent release job configs
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.1.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.3.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#3496 kubevirtci,presubmit: Add test lane for kind-1.30-vgpu provider
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes
