Repository kubevirt/project-infra, pull requests merged in 2024-09, with the labels that each got.

#3619 kubevirt,periodic: Use pr-creator image for bump-rpms periodic job
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3620 kubevirt,presubmits: Update to sig-compute lane to only run parallel
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3621 docs: Fix rolebinding example for serviceaccount creation
  docs/how-to-add-a-prow-cluster.md
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3622 kubevirt,periodic: Update compute migrations periodic to kubernetes v1.31
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3623 HCO: add test to new release branch 1.13
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.13.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3624 hco: add lane 1.31; remove lane 1.29
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3625 github, labels: move testing to category area
  github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3615 project-infra: remove root reviewers with low activity
  OWNERS
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3634 prow, monitoring: add panel of failure % by SIG
  github/ci/services/grafana/manifests/grafana.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#3633 github, labels: add triage/infra-issue
  docs/labels.md
  github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3613 add periodic e2e tests job for s390x.
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3638 update bootstrap to include which pkg.
  images/bootstrap/Dockerfile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3639 bootstrap: Add workaround for corrupted image pulls with podman
  images/bootstrap/Dockerfile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3640 kumemacpool, postsubmit: Push stable branch latest commits
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-postsubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3618 Add dasionov as a community member
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3641 Adding presubmits for aaq release-v1.3
  github/ci/prow-deploy/files/jobs/kubevirt/application-aware-quota/application-aware-quota-presubmits-1.3.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3643 kubevirt,presubmit: Move s390x unit test job to new bare-metal cluster
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3617 Enable multiarch builds for pr-creator image
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  images/pr-creator/Dockerfile
Labels: size/S, approved, lgtm, dco-signoff: yes

#3644 kubevirt,periodic: Switch s390x unit test jobs to new cluster
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3552 Add s390x unit test job
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3647 Modified the message that only top level approvers can change blocker…
  external-plugins/release-blocker/server.go
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3650 kubevirt,arm64: Stop reporting on failing ARM64 e2e lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3649 Archive repository ansible-kubevirt-modules
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3629 Add an optional presubmit job for kwok performance tests
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3656 Revert "common-instancetypes: Use kubevirtcti in release branches
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.0.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.1.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3627 Add nightly build periodic job for s390x
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3626 kubevirt,presubmits: update storage lanes to run with etcd in mem
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.3.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3660 sig-ci: run quarantined tests report in the morning
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3659 CDI,presubmits: update lanes to run with etcd in mem
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3666 Revert "bootstrap: Add workaround for corrupted image pulls with podman (#3639)"
  images/bootstrap/Dockerfile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3655 approvers: add commenter that marks stale PRs
  docs/labels.md
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3668 prow-deploy,presubmit: update nginx deployment to use only image tag
  github/ci/prow-deploy/kustom/overlays/kubevirtci-testing/resources/ingress-nginx-controller.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3670 common-instancetypes-periodics: Don't post PR to SSP
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3671 approver,review: fix label name in query
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3672 kubevirt,presubmits: fix typo in kwok presubmit
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3499 kubevirt,vgpu: Bump vgpu lanes to use new kind-1.30-vgpu provider
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3675 kubevirtci,presubmit: Remove check for kind-1.27-vgpu
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3677 Revert "kubevirt,arm64: Stop reporting on failing ARM64 e2e lane"
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3648 Added REST based API calls for GCS as gsutil isn't supported for s390x in bootstrap image
  images/bootstrap/Dockerfile
  images/bootstrap/gcs_restapi.sh
Labels: size/L, approved, lgtm, dco-signoff: yes, sig/ci

#3614 kubevirt, labels: rename code-quality into cleanup
  docs/labels.md
  github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3678 kubevirtci,kind,check-up: add for 1.28
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3681 Added optional presubmit check-provision-k8s-1.30-s390x
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes, sig/ci

#3682 Increase the timeout to 4hrs for the kubevirtbuilder post submit job .
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3683 HCO: only build the test utils image on the main branch
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3684 fix: removing docker-mirror-proxy label for check-provision-k8s-1.30-s390x
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3685 kubevirtci,presubmit: Remove image proxy from s390x presubmit
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes
