Repository kubevirt/project-infra, pull requests merged in 2024-07, with the labels that each got.

#3502 Add OpenSUSE presubmits for containerdisks
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3504 containerdisks: Update opensuse presubmits
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3495 Enable NodeRestriction fg for 1.30 lanes
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3505 common-instancetypes: Add OpenSUSE Tumbleweed and Leap presubmits
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3506 docs, reports: update merge queue link
  docs/reports.md
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3507 containerdisks: Remove centos presubmit
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3511 ci, reporting: fix kubevirt presubmit list generation
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3514 operator lifecycle sdk: delegate k8s version decisions to repo scripts
  github/ci/prow-deploy/files/jobs/kubevirt/controller-lifecycle-operator-sdk/controller-lifecycle-operator-sdk-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3512 Move pull-cdi-goveralls to kubevirt-prow-workloads
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirt-prow-workloads/kustomization.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3515 bootstrap: Remove cgroups=disabled from containers.conf
  images/bootstrap/containers.conf
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3508 project-infra, bazel: move presubmits to pure go
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  robots/pkg/validation/content.go
Labels: size/M, approved, lgtm, dco-signoff: yes

#3510 common-instancetypes: Introduce Fedora arm64 presubmits
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3519 common-instancetypes: Add remaining arm64 presubmits
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#3298 Add presubmit prow job to run unit tests on s390x cluster
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3518 sig-ci: add label for sig
  docs/labels.md
  github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3520 referee, prow: update metrics for commit changes
  external-plugins/referee/Makefile
  external-plugins/referee/server/server.go
Labels: size/S, approved, lgtm, dco-signoff: yes

#3521 bootstrap: add explicit install of fuse-overlayfs
  images/bootstrap/Dockerfile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3525 chore: add ssp-operator branch protection
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3526 kubevirt,presubmit: Stop reporting failing arm64 unit tests
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3527 prow,config: Update default bazel version v5.4.1
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3528 kubevirt,nightly: revert nightly builds to use previous job image
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3529 fix,bootstrap: Fix sed to change to permissive for short-name-mode
  images/bootstrap/runner.sh
  images/publish_multiarch_image.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3532 CSI-Driver: Bump go to 1.22.5
  github/ci/prow-deploy/files/jobs/kubevirt/csi-driver/csi-driver-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3533 kubevirtci,presubmit: Add check-provision lane for new k8s-1.31 provider
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3535 Don't ignore errors
  releng/release-tool/release-tool.go
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3513 chore: enable branch protection for kubevirt-tekton-tasks
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3538 kubevirtci,presubmit: Set check-provision for k8s-1.31 to always run and be required
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3542 user-guide, publish: fix job error on no pushable changes
  github/ci/prow-deploy/files/jobs/kubevirt/user-guide/user-guide-postsubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3544 kubevirt,arm64: Skip reporting on the arm64 conformance lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3546 bootstrap: leave short-name-mode as default enforcing
  images/bootstrap/runner.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3547 kubevirtci, ensure-only-latest-three: fix future provider removal
  robots/pkg/kubevirtci/BUILD.bazel
  robots/pkg/kubevirtci/kubevirtci.go
  robots/pkg/kubevirtci/kubevirtci_test.go
Labels: size/M, approved, lgtm, dco-signoff: yes

#3543 kubevirt: Add optional kubernetes 1.31 presubmits & periodics
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#3550 prow, referee: enable pull_request events, fix switch
  external-plugins/referee/server/server.go
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3549 prow, referee: notify PR author instead of commenter
  external-plugins/referee/server/server.go
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3555 project-infra, deployment, update: use generated tag
  external-plugins/botreview/Makefile
  external-plugins/referee/Makefile
  github/ci/prow-deploy/kustom/base/manifests/local/referee-deployment.yaml
  hack/update-deployments-with-latest-image.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#3556 Doc: change namespace for token export
  docs/how-to-add-a-prow-cluster.md
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3537 fix: add -c param to kubevirt-tekton-tasks script
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-tekton-tasks/tekton-tasks-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3557 kubevirt, presubmits: Set unit-tests for s390x to be required
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3560 kubevirt,presubmits: Set failing apidocs presubmit to optional
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3561 Revert "kubevirt,presubmits: Set failing apidocs presubmit to optional (#3560)"
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes
