Repository kubevirt/project-infra, pull requests merged in 2024-04, with the labels that each got.

#3320 Request an API repository for Application Aware Quota
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3338 HCO: add new line for K8s 1.29
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3339 common-instancetypes-periodics: Add stable branch names to subject of PRs
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3336 kubevirt,periodic: remove kubernetes version from sysprep lane name
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3328 Add jschintag to kubevirt members
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3341 common-instancetypes: Add release-1.0 pre-submits
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.0.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#3342 common-instancetypes-periodics: Limit syncs to once a week
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3345 prow, labels, github: Add sig/observability label
  github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3343 sig-performance: Fail on error
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3348 kubectl-virt, presubmit: remove shellcheck since it's unreliable
  github/ci/prow-deploy/files/jobs/kubevirt/kubectl-virt-plugin/kubectl-virt-plugin-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3334 prow-deploy,presubmit: Wait for prow pods to be created before checking if ready
  github/ci/prow-deploy/tasks/tests.yml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3351 Revert "Run hack/bump-prow.sh (#3340)"
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/branch-protector.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/cherrypicker_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/label-sync-kubevirt.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/label-sync-nmstate.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/crier_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/deck_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/ghproxy.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/hook_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/horologium_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/needs-rebase_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/prow_controller_manager_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/sinker_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/statusreconciler_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/tide_deployment.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/resources/prow-exporter-deployment.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3353 containerdisks: Bump go version to 1.22.2
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3335 kubevirtci,presubmit: Add presubmit to check centos base provisioning
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3358 Revert "Run hack/bump-prow.sh (#3354)"
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/branch-protector.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/cherrypicker_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/label-sync-kubevirt.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/label-sync-nmstate.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/crier_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/deck_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/ghproxy.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/hook_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/horologium_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/needs-rebase_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/prow_controller_manager_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/sinker_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/statusreconciler_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/tide_deployment.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/resources/prow-exporter-deployment.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3329 prow, plugin, rehearse: restrict access to rehearsal to project-infra top level approvers and job approvers
  external-plugins/rehearse/plugin/BUILD.bazel
  external-plugins/rehearse/plugin/handler/BUILD.bazel
  external-plugins/rehearse/plugin/handler/handler.go
  external-plugins/rehearse/plugin/handler/handler_test.go
  external-plugins/rehearse/plugin/main.go
  external-plugins/rehearse/plugin/rehearse_test.go
  external-plugins/testutils/fakegithub.go
Labels: size/L, approved, lgtm, dco-signoff: yes

#3364 prow, autobump: add config files, modify bump script
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow-deploy/prow-autobump-config.yaml
  github/ci/prow-deploy/prow-job-autobump-config.yaml
  hack/bump-prow.sh
Labels: size/L, approved, lgtm, dco-signoff: yes

#3357 Remove OVS-CNI postsubmit publishing images
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/ovs-cni/ovs-cni-postsubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3366 Request adding EduaredGomezEscandell to org members
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3350 Enable goveralls in containerized-data-importer
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3355 kubevirtci,presubmit: Remove check provision job for k8s-1.27 provider
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3369 Fix: CDI goveralls job must use its repository's token
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
  github/ci/prow-deploy/tasks/secrets.yml
  github/ci/prow-deploy/vars/kubevirtci-testing/secrets.yml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3365 prow, deployments: update with latest images
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  hack/bump-prow-deployment-images.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#3367 prow, labels, docs: add labels documentation generation
  Makefile
  docs/labels.md
  hack/labels/labels.md.gotemplate
  hack/labels/update.sh
Labels: size/L, approved, lgtm, dco-signoff: yes

#3372 Fix: CDI control plane has no access to Goveralls token
  github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/kustomization.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3374 prow, labels: update help wanted and good first issue
  docs/labels.md
  github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3375 prow, referee: enable plugin for halting prs
  github/ci/prow-deploy/kustom/base/manifests/local/referee-deployment.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3377 kubevirt,releases: Add change to mdev module name in vgpu release presubmits
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.1.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3368 kubevirt,presubmits: enable kubernetes v1.30 lanes to always run
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#3382 kubevirt,vgpu: Add change to mdev module name in vgpu 0.58 presubmits
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.58.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3385 kubevirt,presubmits: Move vgpu e2e test lanes to optional for main and recent releases
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.1.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3379 Add test lanes to AAQ version 1.2
  github/ci/prow-deploy/files/jobs/kubevirt/application-aware-quota/application-aware-quota-presubmits-1.2.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3381 kubevirt,vgpu: Fix antiaffinity rules for vgpu lanes to prevent collisions
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.1.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes
