Repository kubevirt/project-infra, pull requests merged in 2024-11, with the labels that each got.

#3720 Added optional presubmit check-provision-k8s-1.31-s390x
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes, sig/ci

#3687 tests,stats: generate per-test execution statistics csv
  robots/cmd/flake-stats/main.go
  robots/cmd/flake-stats/main_test.go
  robots/cmd/per-test-execution/BUILD.bazel
  robots/cmd/per-test-execution/config.yaml
  robots/cmd/per-test-execution/main.go
  robots/cmd/per-test-execution/main_test.go
  robots/pkg/flakefinder/BUILD.bazel
  robots/pkg/flakefinder/test_names.go
  robots/pkg/flakefinder/test_names_test.go
Labels: size/L, approved, lgtm, dco-signoff: yes

#3699 add preset-kubevirt-s390x-icr-credential to pull the s390x images from icr.io
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3722 prow: Manual bump of prow components
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/branch-protector.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/cherrypicker_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/crier_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/deck_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/ghproxy.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/grandmatriarch.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/hook_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/horologium_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/needs-rebase_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/pipeline_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/prow_controller_manager_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/sinker_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/statusreconciler_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/tide_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/tot_deployment.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/resources/prow-exporter-deployment.yaml
  hack/bump-prow.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#3701 devstats,repo_groups: modify job to use go generator
  github/ci/prow-deploy/files/jobs/kubevirt/community/community-postsubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3727 images: Update path to latest kubevirtci tag in shared-images
  images/shared-images-controller/main.go
Labels: size/S, approved, lgtm, dco-signoff: yes

#3738 prow,deploy,check: fix kubevirtci path
  github/ci/prow-deploy/hack/test.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3724 community,sigs: replace presubmit with make call
  github/ci/prow-deploy/files/jobs/kubevirt/community/community-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3725 common-instancetypes, release-1.2: Use kubevirt HEAD until 1.4 is released
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.2.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3737 prow-workloads: bump shared-images-controller to v20241105-ed1a7bc
  github/ci/prow-deploy/kustom/overlays/kubevirt-prow-workloads/resources/shared-images-controller.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3739 CDI periodic: add missing build for amd64
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3741 Bump containerdisk to golang 1.22.8
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3743 CDI: Fix amd64 nightly build
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3747 Bump golang 1.22.9
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3746 grafana: update cluster-up path for grafana test presubmit
  github/ci/services/grafana/hack/test.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3693 kubevirt,governance: improve script to remove inactive org users
  hack/remove-users-without-contributions.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#3748 use artifacts result directory to read pref/scale data
  robots/cmd/perf-report-creator/main.go
Labels: size/M, approved, lgtm, dco-signoff: yes

#3755 HCO: Fix K8s versions
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3752 Made optional presubmit check-provision-k8s-1.30-s390x mandatory now
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3754 increase the hco periodic timeout
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3745 build: Dependabot bumps & fixes
  WORKSPACE
  go.mod
  go.sum
  go_third_party.bzl
Labels: size/XL, approved, lgtm, dco-signoff: yes

#3757 flake-stats,ci: generate calendar page for flake stats
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  robots/cmd/flake-stats-index-page/BUILD.bazel
  robots/cmd/flake-stats-index-page/README.md
  robots/cmd/flake-stats-index-page/main.go
Labels: size/L, approved, lgtm, dco-signoff: yes

#3753 Made optional presubmit check-provision-k8s-1.31-s390x mandatory
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3761 community,generate: add project-infra extra_ref
  github/ci/prow-deploy/files/jobs/kubevirt/community/community-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3760 kubevirt,release: add alert email
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
  github/ci/testgrid/gen-config.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3763 needs-approver-review: avoid labelling PRs with changes requested
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3764 labels,sig/compute: migrate sig/virtualization
  docs/labels.md
  github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3766 ci: Add nestoracunablanco as a member of the community
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3769 kubevirt,nightly: fix periodic push job
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3772 [tekton-tasks] fix: wrong path of Containerfile
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-tekton-tasks/tekton-tasks-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3767 org,members: add cfilleke as org member
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3774 images: Remove legacy docker-in-docker bootstrap images as no longer needed
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  images/bootstrap-legacy/Dockerfile
  images/bootstrap-legacy/README.md
  images/bootstrap-legacy/create_bazel_cache_rcs.sh
  images/bootstrap-legacy/entrypoint.sh
  images/bootstrap-legacy/runner.sh
  images/golang-legacy/Dockerfile
Labels: size/XL, approved, lgtm, dco-signoff: yes

#3777 kubevirt,presubmits: Update release vgpu lanes to use custom bootstrap image
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.1.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.3.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3779 community,sigs.yaml: remove sigs.yaml validation
  github/ci/prow-deploy/files/jobs/kubevirt/community/community-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3770 needs-approver-review: enable management by GH team
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3782 peribolos,org: increase job timeout
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3781 governance,org: replace devstats source
  hack/remove-users-without-contributions.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#3780 kubevirtci,presubmits: Add optional presubmit lanes to test k8s-1.32 provider
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3783 common-instancetypes: Run ValidationOS lane on when tag/image changes
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3785 kubevirtci,presubmit: Enable check-provision for new k8s-1.32 provider
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3788 Prow jobs for publishing centos9 multi arch image
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3787 prow-deploy: Add virtci-gcs secret to the prow control plane cluster
  github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/kustomization.yaml
  github/ci/prow-deploy/tasks/secrets.yml
  github/ci/prow-deploy/vars/kubevirtci-testing/secrets.yml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3792 Made pre-submit job check-provision-k8s-1.30-s390x optional
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3791 kubevirt: Add optional presubmit and periodic lanes for new k8s-1.32 provider
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#3793 kubevirt,presubmit: Set k8s-1.32 sig-compute-serial to be explicitly optional
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, dco-signoff: yes
