Repository kubevirt/project-infra, pull requests merged in 2024-08, with the labels that each got.

#3565 kubevirtci,publish: update golang version to v1.22.5
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3564 Add/Update configuration for common-instancetypes release-1.1
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.1.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-periodics.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#3568 common-instancetypes: Update common-instancetypes-builder
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.1.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3571 common-instancetypes: Use kubevirtcti in release branches
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.0.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.1.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3574 images,shared-images: Update to use podman v5.2
  images/shared-images-controller/go.mod
  images/shared-images-controller/go.sum
Labels: size/XL, approved, lgtm, dco-signoff: yes

#3573 Create dra-pci-driver repository
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3575 common-instancetypes: Make pull-common-instancetypes required
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-0.1.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-0.3.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-0.4.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.0.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.1.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3576 kubevirt,presubmit: Set failing pull-kubevirt-apidocs to optional
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.1.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.3.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3578 Add TheRealSibasishBehera to KubeVirt Members
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3580 Revert "kubevirt,presubmit: Set failing pull-kubevirt-apidocs to optional"
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.1.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.3.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3581 Increasing the HCO tests memory, to try to fix flaky tests
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3583 kubemacpool, postsubmit: Fix to push last added tag
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3582 image,golang: Update default go version to v1.22.6
  images/golang/Dockerfile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3585 cnao: Add stable release-0.95 branch presubmit
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.95.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#3588 Correct skip branch regex in push-cdi-goveralls
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3591 Bump containerdisks to golang 1.22.6
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3590 Missing dra-pci-driver for approve and lgtm
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3592 Fix configuration for dra-pci-driver repo
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3593 dra-pci-driver: update team config in orgs.yaml
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3594 update-deployments-with-latest-image.sh: fix image_tag unbound var
  hack/update-deployments-with-latest-image.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3500 community, org: generate yaml with list of users access levels
  go.sum
  robots/cmd/org-access-check/BUILD.bazel
  robots/cmd/org-access-check/main.go
Labels: size/L, approved, lgtm, dco-signoff: yes

#3599 Add Acedus to KubeVirt Members
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3598 add aliamerj to kubevirt members
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3600 kubevirt,presubmit: enable kubernetes v1.31 lanes to always run
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#3603 Update autoowners container file to use full qualified image name
  images/autoowners/Dockerfile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3494 release, verification: add gpg key setup to release job
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3608 kubevirtci.periodic: Update go version used by bump centos periodic
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3610 kubevirtci,presubmit: Increase time out for check of provision manager
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3611 bootstrap: Increase podman pids_limit to 4096
  images/bootstrap/containers.conf
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3609 add aerosouund to the KubeVirt org
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3587 prow: Update prow-deploy and bumper to use new location for prow images
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/branch-protector.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/cherrypicker_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/crier_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/deck_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/ghproxy.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/grandmatriarch.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/hook_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/horologium_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/needs-rebase_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/pipeline_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/prow_controller_manager_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/sinker_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/statusreconciler_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/tide_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/tot_deployment.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/resources/prow-exporter-deployment.yaml
  github/ci/prow-deploy/prow-autobump-config.yaml
  github/ci/prow-deploy/prow-job-autobump-config.yaml
  hack/bump-prow.sh
  hack/mkpj.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#3604 cdi,postsubmit: Update the push of CDI builder to only run when there are changes
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes
