Repository kubevirt/project-infra, pull requests merged in 2024-10, with the labels that each got.

#3661 Move priority/backlog to global label definition
  docs/labels.md
  github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes, area/prow, hacktoberfest

#3665 Add the deprecation notice to label `triage/build-watcher`
  docs/labels.md
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes, hacktoberfest

#3689 Copy conformance-s390x.yaml to GCS in periodic-kubevirt-push-nightly-build-main-s390x
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3688 Add slim mode to check-provision-k8s-1.30-s390x prow job
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3692 hco,presubmit: Update golang image to fix issue pulling images in v1.13 lanes
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.13.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3694 Skip Kubevirt conformance tests temporarily for check-provision-k8s-1.30-s390x job
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3695 Add nirdothan to KubeVirt Members
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3698 hco,presubmit: Add unit-test job for s390x
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3696 Add kubectl installation to bootstrap image for s390x
  images/bootstrap/Dockerfile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3703 feat: Run the gocli tests on all presubmit runs to KubevirtCI
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3704 common-instancetypes: Add configuration for release-1.2
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.2.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-periodics.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#3705 common-instancetypes: Update common-instancetypes-builder
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.2.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3708 Add chandramerla as kubevirt org member
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3717 kubevirt,periodic: Increase etcd in mem capacity to 1G for storage periodics
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3716 kubevirt,periodic: Remove SEV periodic test lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3718 kubevirt,presubmit: Disable reporting on the failing arm64 e2e lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3715 Create optional sig-compute conformance lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3713 approvers,labels: remove needs-approvers-review
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3719 kubevirt,presubmit: Explicitly set compute conformance lane as optional
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes
