Repository kubevirt/project-infra, pull requests merged in 2024-05, with the labels that each got.

#3387 kubevirt,vgpu: Remove modprobe of vfio_mdev from release vgpu test lanes
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.58.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.1.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3386 cnao: Add new release-0.93 stable branch presubmit
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.93.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#3390 HCO: Set tests for release 1.12
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.12.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3391 kubevirtci, crio: Fix crio mirror by adding gcloud to PATH
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3389 kubevirt,fossa: Update fossa presubmit to be optional
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3393 CDI destructive dummy job for release branches
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3395 Revert "kubevirt,fossa: Update fossa presubmit to be optional (#3389)"
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3384 prow, plugin, rehearse: fix case issue for user name
  external-plugins/rehearse/plugin/handler/handler.go
  external-plugins/rehearse/plugin/handler/handler_test.go
Labels: size/L, approved, lgtm, dco-signoff: yes

#3362 kubevirt,presubmits: Add sig-compute-serial e2e test lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3396 prow, referee: fix build to point to kubevirt repo
  images/referee/Containerfile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3388 kubevirt,presubmit: Bump single stack ipv6 lane to 1.30
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3401 kubevirt,release-1.2: Fix setting vgpu test lane to optional
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3399 AAQ: trigger post submit jobs on new tag
  github/ci/prow-deploy/files/jobs/kubevirt/application-aware-quota/application-aware-quota-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3405 prow, rehearse: add ok-to-rehearse label check
  external-plugins/rehearse/plugin/handler/BUILD.bazel
  external-plugins/rehearse/plugin/handler/handler.go
  external-plugins/rehearse/plugin/handler/handler_test.go
  external-plugins/rehearse/plugin/handler/labels.go
  github/ci/prow-deploy/kustom/base/configs/current/labels/labels.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3402 common-instancetypes-periodics: Add sync jobs for release-1.0
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-periodics.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3407 HCO: Bump golang to 1.22
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3409 HCO: add 1.30 lane; remove 1.28 lane
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3408 kubevirt,vgpu: Stop vgpu presubmit lanes from always running against PRs
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.1.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3392 CDI: Make goveralls job always run, and run it on main
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3411 prow-deploy: Update prow-deploy test lane to use latest provider
  github/ci/prow-deploy/hack/test.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3410 common-instancetypes-periodics: Pass branch in main sync job
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3416 prow, rehearse: fix comment formatting for non approver
  external-plugins/rehearse/plugin/handler/handler.go
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3414 istio,mirror: Fix istio mirror by adding gcloud to PATH
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3415 kubevirt,periodic: Update bump-rpms job to use bootstrap image instead of the builder
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3380 prow, referee: add retest metrics
  external-plugins/referee/BUILD.bazel
  external-plugins/referee/README.md
  external-plugins/referee/ghgraphql/pullrequests.go
  external-plugins/referee/main.go
  external-plugins/referee/main_test.go
  external-plugins/referee/metrics/BUILD.bazel
  external-plugins/referee/metrics/doc.go
  external-plugins/referee/metrics/metrics.go
  external-plugins/referee/metrics/metrics_suite_test.go
  external-plugins/referee/metrics/metrics_test.go
  external-plugins/referee/metrics/retests.go
  external-plugins/referee/metrics/retests_test.go
  external-plugins/referee/server/BUILD.bazel
  external-plugins/referee/server/server.go
Labels: size/XL, approved, lgtm, dco-signoff: yes

#3420 Correct skip branch regex in pull-cdi-goveralls
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3423 Revert "bootstrap: Bump to Fedora 40 (#3373)"
  images/bootstrap/Dockerfile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3419 bump network lanes to using 3 nodes
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3425 prow-deploy: Add test_infra dir to prow-autobump-config
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/crier_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/deck_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/ghproxy.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/grandmatriarch.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/hook_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/horologium_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/needs-rebase_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/pipeline_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/prow_controller_manager_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/sinker_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/statusreconciler_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/tide_deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/test_infra/current/tot_deployment.yaml
  github/ci/prow-deploy/prow-autobump-config.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3427 periodic,common-instancetype: Add label checker to jobs to avoid unnecessary CI churn
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-periodics.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3428 presubmit,fossa: Set fossa presubmit lanes to optional
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3429 Revert "presubmit,fossa: Set fossa presubmit lanes to optional (#3428)"
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3434 kubevirtci, monitoring: add sig-compute-serial and sig-compute-migrations
  github/ci/services/grafana/manifests/grafana.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3435 kubevirci, presubmit: Fix run if changed condition
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3436 prow, stale, bot: query only public issues
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3439 shared-images-controller: Update to go v.1.22.3 & podman v5
  images/shared-images-controller/BUILD.bazel
  images/shared-images-controller/Containerfile
  images/shared-images-controller/go.mod
  images/shared-images-controller/go.sum
  images/shared-images-controller/main.go
Labels: size/L, approved, lgtm, dco-signoff: yes

#3438 prow, referee, monitoring: add retest metrics dashboard
  github/ci/prow-deploy/kustom/base/kustomization.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/referee-service.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/referee-servicemonitor.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirtci-testing/resources/monitoring.coreos.com/monitoring.coreos.com_servicemonitors.yaml
  github/ci/prow-deploy/tasks/deploy.yml
  github/ci/services/grafana/manifests/grafana.yaml
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#3440 release-tool: Update base image to fedora 39 & go version to v1.21.9
  WORKSPACE
  go.sum
  releng/release-tool/Dockerfile.release-tool-base
Labels: size/M, approved, lgtm, dco-signoff: yes

#3444 release-tool: fix make target in release-tool image publish postsubmit
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3448 fix capk presubmit
  github/ci/prow-deploy/files/jobs/kubernetes-sigs/cluster-api-provider-kubevirt/cluster-api-provider-kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3445 monitoring, referee, retests: replace with increase
  github/ci/services/grafana/manifests/grafana.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes
