Repository kubevirt/project-infra, pull requests merged in 2025-08, with the labels that each got.

#4300 Move perf results up a directory
  robots/cmd/perf-report-creator/main.go
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4302 cnao: Add presubmit for stable 0.100
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.100.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#4306 Add presubmits jobs to aaq 1.5
  github/ci/prow-deploy/files/jobs/kubevirt/application-aware-quota/application-aware-quota-presubmits-1.5.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#4243 Bump compute non-standard lanes to 1.33
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#4311 arm64: Move presubmits to kind-1.33
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes, wg/arch-arm

#4313 arm: Disable failing liveness check for old ARM cluster
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#4310 Add gustab-kamil as kubevirt member
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4316 kubevirtci,presubmits: Require the kind presubmits to pass when the kind providers are changed
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#4326 kubevirt,s390x: Temporarily move s390x unit test jobs to optional due to DNS issue
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.4.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.5.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.6.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4330 chore(common-instancetypes): Add test job for Debian 13
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#4328 [kubevirt/kubevirt]: make prom-rule-verify run conditional
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4334 chore(common-instancetypes): Add Debian 13 test jobs to releases
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.0.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.1.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.2.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.3.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.4.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes
