Repository kubevirt/project-infra, pull requests merged in 2025-03, with the labels that each got.

#3991 Update containerized-data-importer-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3988 hco,presubmit: Make s390x unit-test required
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3987 common-instancetypes: Add presubmits for release-1.3
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.3.yaml
Labels: size/XL, approved, lgtm, dco-signoff: yes

#3990 ci: Ubuntu s390x containerdisks job
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3997 phased plugin: Fix makefile
  external-plugins/phased/Makefile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3994 kubevirtci,presubmit: Increase max concurrency from 1 to 3
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#4004 fix: set the job as optional until the s390x pipelines are stable.
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4006 common-instancetypes: Introduce v1.3 periodic update bundle job
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-periodics.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#4007 Register OVS CNI 0.32 0.34 0.36
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/ovs-cni/ovs-cni-presubmits-0.32.yaml
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/ovs-cni/ovs-cni-presubmits-0.34.yaml
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/ovs-cni/ovs-cni-presubmits-0.36.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#3958 release-tool: fix config-forking
  Makefile
  images/release-tool-base/Containerfile
  images/release-tool/Containerfile
  releng/release-tool/release-tool.go
  releng/release-tool/release-tool_test.go
  releng/release-tool/testdata/jobconfig/kubevirt-presubmits-1.6.yaml
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#4014 fix: release-tool image push
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4010 kubevirtci,presubmit: Add check-provision lane for new k8s-1.33
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#4018 fix: let phased plugin run tests for skip-review PRs
  external-plugins/phased/plugin/handler/handler.go
  external-plugins/phased/plugin/phased_test.go
  robots/pkg/github/labels/labels.go
Labels: size/M, approved, lgtm, dco-signoff: yes

#4021 containerdisks: Bump golang version
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3164 plugins: Introduce test-subset plugin
  docs/infrastructure-components.md
  external-plugins/test-subset/Containerfile
  external-plugins/test-subset/Makefile
  external-plugins/test-subset/plugin/handler/handler.go
  external-plugins/test-subset/plugin/main.go
  external-plugins/test-subset/plugin/server/eventsserver.go
  external-plugins/test-subset/plugin/specify_suite_test.go
  external-plugins/test-subset/plugin/specify_test.go
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
  github/ci/prow-deploy/kustom/base/kustomization.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/test-subset-deployment.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/test-subset-rbac.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/test-subset-service.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/kustomization.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirt-prow-control-plane/patches/JsonRFC6902/test-subset-deployment.yaml
  images/test-subset
Labels: size/XXL, approved, lgtm, dco-signoff: yes

#4024 fix: add links to own prow and own merge workflow
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4025 fix: correct test-subset external-plugin compile source path
  external-plugins/test-subset/Containerfile
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/prow-deploy/kustom/base/manifests/local/test-subset-deployment.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#4022 Adds test lanes for Debian 11 and 12 preferences and containerdisks.
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#4027 fix(common-instancetypes): Fix test job debian names.
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4019 feat: make configurable no of max retests
  external-plugins/referee/main.go
  external-plugins/referee/server/server.go
  github/ci/prow-deploy/kustom/base/manifests/local/referee-deployment.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3945 In s390x publish centos9 and kubevirtci jobs, do GCS calls without auth where possible
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-postsubmits.yaml
  images/bootstrap/gcs_restapi.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#4034 fix: increase memory for check-provision-k8s
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4028 chore(common-instancetypes): Add presubmits of Debian for release-1.3
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.3.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#4038 common-instancetypes: Correct Debian release-1.3 job branch
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.3.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4039 common-instancetypes: Correct Debian release-1.3 job branch
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.3.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4036 fix: describe-images has a non optional hyphen
  hack/describe-pr-from-updated-images-in-diff.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4042 kubevirt,presubmit: Increase timeout for performance e2e presubmits
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.1.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.3.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.4.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.5.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#4000 Move migration lane to 1.32 Kubernetes
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.5.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#4043 fix: decrease number of max retests per commit
  github/ci/prow-deploy/kustom/base/manifests/local/referee-deployment.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4044 feat(test-subset): add debug statements to follow execution
  external-plugins/test-subset/plugin/handler/handler.go
Labels: size/S, approved, lgtm, dco-signoff: yes

#4002 add periodic kwok job with 100 vmi count to compare real vs simulated
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#4049 fix(check-tests-for-flakes): update env var used
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4055 prow,workloads: Increase resource requests/limits for image proxy and bazel cache
  github/ci/prow-deploy/kustom/overlays/prow-workloads/kustomization.yaml
  github/ci/prow-deploy/kustom/overlays/prow-workloads/patches/JsonRFC6902/docker_mirror_deployment.yaml
  github/ci/prow-deploy/kustom/overlays/prow-workloads/patches/JsonRFC6902/greenhouse_deployment.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#4054 Escape auth_header value with quotes
  images/bootstrap/gcs_restapi.sh
Labels: size/S, approved, lgtm, dco-signoff: yes

#4061 kubevirt,release-1.2: Move 1.27 sig-compute to optional due to constant failures
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4058 kubevirt,presubmit: Remove KUBEVIRT_NUM_NODES from compute-migrations lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes
