Repository kubevirt/project-infra, pull requests merged in 2025-06, with the labels that each got.

#4171 chore(autobump): add checkconfig script path
  github/ci/prow-deploy/prow-autobump-config.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4182 fix(code-lint): move job to workloads cluster
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4187 Add presubmits for AAQ 1.4
  github/ci/prow-deploy/files/jobs/kubevirt/application-aware-quota/application-aware-quota-presubmits-1.4.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#4136 chore(plugins): Remove release-note plugin from enhancements repo
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes, needs-approver-review

#4179 feat: ignore drafts when assigning reviewers to pull requests
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#4191 cri-o,mirror: fix cri-o repo location to match latest
  hack/mirror-crio.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4201 Revert "fix(s390x): disable reporting for most s390x presubmits"
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubesecondarydns/kubesecondarydns-presubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.4.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.5.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#4205 feat(arm64): re-add arm lanes for new cluster
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-0.59.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.0.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.1.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.2.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.3.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.4.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.5.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  github/ci/prow-deploy/kustom/overlays/prow-arm64-workloads/.gitignore
  github/ci/prow-deploy/kustom/overlays/prow-arm64-workloads/kustomization.yaml
Labels: size/XL, approved, lgtm, dco-signoff: yes

#4210 fix(arm,periodic): missing cgroup host mount
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#4211 HCO: Bump golang to 1.24
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#4212 kubevirt,arm: Move ARM presubmits to always_run: false due to issue with cluster
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4217 ci(jobs,arm): change periodic to 3xday, reduce concurrent runs
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4220 project-infra,presubmit: Increase timeout for github org config update presubmit
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4204 Add salawhaaat as a kubevirt member
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4030 prow, rehearse: improvements to comment
  external-plugins/rehearse/plugin/handler/handler.go
Labels: size/S, approved, lgtm, dco-signoff: yes

#4229 project-infra,periodic: fix arm cluster liveness check
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4235 Explicitly set provider for windows job
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes
