Repository kubevirt/project-infra, pull requests merged in 2025-01, with the labels that each got.

#3845 ci-search: use kubectl kustomize for deployment
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  github/ci/services/ci-search/README.md
  github/ci/services/ci-search/base/kustomization.yaml
  github/ci/services/ci-search/base/manifests/full.yaml
  github/ci/services/ci-search/base/manifests/ingress.yaml
  github/ci/services/ci-search/base/patches/statefulset.yaml
  github/ci/services/ci-search/hack/deploy.sh
  github/ci/services/ci-search/overlays/production/kustomization.yaml
  github/ci/services/ci-search/overlays/production/secrets/bugzilla-credentials
  github/ci/services/ci-search/overlays/testing/cluster-issuer.yaml
  github/ci/services/ci-search/overlays/testing/kustomization.yaml
  github/ci/services/ci-search/overlays/testing/secrets/bugzilla-credentials
  github/ci/services/ci-search/secrets/production/bugzilla-credentials/.gitkeep
Labels: size/L, approved, lgtm, dco-signoff: yes

#3865 lint: increase timeout
  .golangci.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3844 kubevirt,presubmits: Set v1.32 e2e lanes to required
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3870 flakefinder: update image references
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-periodics.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3871 flakefinder: add command
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/containerized-data-importer/containerized-data-importer-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: kind/bug, size/S, approved, lgtm, dco-signoff: yes

#3855 Add export PLATFORMS=all to post-submit jobs for kubemacpool.
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes, needs-approver-review

#3873 flakefinder: fix indexpagecreator
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow-deploy/files/jobs/nmstate/kubernetes-nmstate/kubernetes-nmstate-periodics.yaml
Labels: kind/bug, size/S, approved, lgtm, dco-signoff: yes, priority/critical-urgent

#3841 Move root CI lanes to 1.31
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3874 Create a new repo to track KubeVirt enhancements
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3866 test-label-analyzer: replace ginkgo cli call with stdout
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  robots/cmd/test-label-analyzer/cmd/BUILD.bazel
  robots/cmd/test-label-analyzer/cmd/stats.go
Labels: size/M, approved, lgtm, dco-signoff: yes

#3846 project-infra,periodics: execute jobs with go
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#3875 bugfix: use proper command setup for pr-creator go
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: kind/bug, size/M, approved, lgtm, dco-signoff: yes, area/automation

#3876 enhancements repo: drop admin and enable tide
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3877 kubevirt: Bump remaining v1.29 to Kubernetes v1.32
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes, kind/cleanup

#3878 kubevirtci,presubmit: Move check-up-kind-sriov to optional as constantly failing
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3885 chore,go: update go to 1.23
  external-plugins/phased/Containerfile
  external-plugins/rehearse/Containerfile
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  go.mod
  images/ci-usage-exporter/Containerfile
  images/flake-report-creator/Containerfile
  images/flakefinder/Containerfile
  images/golang/Containerfile
  images/indexpagecreator/Containerfile
  images/referee/Containerfile
  images/release-blocker/Containerfile
  images/release-tool/Containerfile
  images/test-report/Containerfile
Labels: size/M, approved, lgtm, dco-signoff: yes

#3887 shared-images: Add gocli and registry images to shared-images
  images/shared-images-controller/main.go
Labels: size/S, approved, lgtm, dco-signoff: yes

#3893 shared-images: Bump shared-images controller to the latest image v20250115-57bca5c
  github/ci/prow-deploy/kustom/overlays/kubevirt-prow-workloads/resources/shared-images-controller.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3894 kubevirtci,presubmit: Move check-provision-k8s-1.31-s390x to optional due to constant failure
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3902 kubevirtci,presubmits: Set vgpu presubmit lane back to being required
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3904 bug,kubevirt image bump: fix periodic job
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3903 bug: fix git-pr.sh commit message
  hack/git-pr.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3911 bootstrap: Increase max wait time for podman socket to be ready
  images/bootstrap/runner.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3914 Delay HCO periodic, to catch CDI nightly build
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3899 kubevirtci,presubmit: Make check-up-kind-sriov lane as required
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3905 chore: remove ginkgo install
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  images/test-label-analyzer/Containerfile
Labels: size/M, approved, lgtm, dco-signoff: yes

#3919 bug,ginkgo: fix handling no ginkgo import
  robots/cmd/test-label-analyzer/cmd/stats.go
  robots/cmd/test-label-analyzer/cmd/stats_test.go
  robots/cmd/test-label-analyzer/cmd/testdata/simple-basic_test.go
Labels: size/M, approved, lgtm, dco-signoff: yes

#3920 presubmits: Upgrade sig-network IPv6 lane
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3921 fix,shared-images: Registry image is not being pulled due to wrong image name
  images/shared-images-controller/main.go
Labels: size/XS, approved, lgtm, dco-signoff: yes

#3923 prow,bump: include shared-images-controller in prow deployment bump
  github/ci/prow-deploy/kustom/base/manifests/local/release-blocker_deployment.yaml
  github/ci/prow-deploy/kustom/overlays/kubevirt-prow-workloads/resources/shared-images-controller.yaml
  hack/update-deployments-with-latest-image.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#3924 shared-images: Reduce some duplication by moving golci and registry pull to for loop
  images/shared-images-controller/main.go
Labels: size/S, approved, lgtm, dco-signoff: yes

#3686 Archiving 25 inactive repos
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#3927 shared-images: Update to go 1.23.5 and podman v5.3.2
  images/shared-images-controller/Containerfile
  images/shared-images-controller/go.mod
  images/shared-images-controller/go.sum
Labels: size/L, approved, lgtm, dco-signoff: yes
