Repository kubevirt/project-infra, pull requests merged in 2025-05, with the labels that each got.

#4133 bootstrap: include awk in the bootstrap required by some jobs
  images/bootstrap/Containerfile
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4131 fix: repair broken regexp for PermaLinks
  robots/cmd/test-label-analyzer/cmd/stats.go
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4125 Enabled staticcheck linter
  .golangci.yaml
  external-plugins/phased/plugin/handler/handler.go
  external-plugins/rehearse/plugin/handler/handler.go
  external-plugins/testutils/fakegithub.go
  images/shared-images-controller/main.go
  releng/release-tool/release-tool.go
  releng/release-tool/release-tool_test.go
  robots/cmd/dependabot/main.go
  robots/cmd/flake-report-creator/cmd/jenkins_test.go
  robots/cmd/flake-report-creator/cmd/prow_test.go
  robots/cmd/flakefinder/index_test.go
  robots/cmd/flakefinder/report_test.go
  robots/cmd/kubevirtci-bumper/main.go
  robots/cmd/kubevirtci-presubmit-creator/main.go
  robots/cmd/kubevirtci-presubmit-remover/main.go
  robots/cmd/per-test-execution/main.go
  robots/cmd/perf-report-creator/plot.go
  robots/cmd/release-querier/main.go
  robots/cmd/test-label-analyzer/cmd/stats.go
  robots/cmd/test-report/cmd/execution/execution.go
  robots/cmd/uploader/uploader.go
  robots/pkg/ci-usage-exporter/metrics/metrics_test.go
  robots/pkg/circuitbreaker/circuitbreaker_test.go
  robots/pkg/flakefinder/build/rating_test.go
  robots/pkg/flakefinder/downloader.go
  robots/pkg/kubevirt/cmd/get/support-matrix.go
  robots/pkg/kubevirt/cmd/remove/always_run.go
  robots/pkg/kubevirt/cmd/require/presubmits.go
  robots/pkg/kubevirt/github/github.go
  robots/pkg/kubevirtci/kubevirtci.go
  robots/pkg/kubevirtci/kubevirtci_test.go
  robots/pkg/mirror/bazel.go
Labels: size/L, approved, lgtm, dco-signoff: yes

#4115 common-instancetypes: Add tests lanes for fedora preferences s390x
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#4143 access(org): add fossedihelm to release-team
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4110 aaq,builder: Ensure builder image is multi-arch
  github/ci/prow-deploy/files/jobs/kubevirt/application-aware-quota/application-aware-quota-postsubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#4146 test-subset: Increase log level
  external-plugins/test-subset/plugin/handler/handler.go
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4130 Add Scott Seago (sseago) to kubevirt maintainers
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4148 aaq,builder: Move job to prow-workloads for better performance
  github/ci/prow-deploy/files/jobs/kubevirt/application-aware-quota/application-aware-quota-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4154 test-subset: Fix secret
  github/ci/prow-deploy/kustom/base/manifests/local/test-subset-deployment.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4145 chore: skip review for automatic kubevirt rpm bump
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4153 feat: show detailed report output file path
  hack/contributions.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4151 kubevirtci,presubmit: Move the k8s-1.33 lane to required
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#4155 Fix the periodic-kubevirtci-bump-hco job
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4152 adding aqilbeig as a KubeVirt member
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4156 Add the `release-note-none` label to the HCO kvci bump job
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4144 chore(orgs.yaml): remove acardace from GitHub teams
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4149 IRSA mutation webhook for injecting virtiofs container to virt-launcher pod
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes

#4121 chore(common-instancetypes): Adjust CentOS 7 and OpenSuse test jobs
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.1.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.2.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-1.3.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/common-instancetypes/common-instancetypes-presubmits.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#4161 kubemacpool: 0.47 stable branch presubmit
  github/ci/prow-deploy/files/jobs/k8snetworkplumbingwg/kubemacpool/kubemacpool-presubmits-v0.47.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#4164 fix(cluster): move push-kubevirt-main to workloads
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4169 fix(restricted_labels): move approved-vep into org section
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
  hack/checkconfig.sh
Labels: size/M, approved, lgtm, dco-signoff: yes

#4166 cnao: Add presubmit job for release-0.99 stable branch
  github/ci/prow-deploy/files/jobs/kubevirt/cluster-network-addons-operator/cluster-network-addons-operator-presubmits-0.99.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes

#4173 Add proper description for HCO's bump kubevirtci PRs
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4170 chore(restricted_labels,gh teams): reorg & simplify
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
  github/ci/prow-deploy/kustom/base/configs/current/plugins/plugins.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes, kind/cleanup

#4158 ci: Fedora s390x containerdisks job
  github/ci/prow-deploy/files/jobs/kubevirt/containerdisks/containerdisks-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#4177 Adds lerrigatto as member
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4183 add maintainers for charts
  github/ci/prow-deploy/kustom/base/configs/current/orgs/orgs.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4162 feat(monitoring): add e2e lane runtimes dashboard
  github/ci/services/grafana/deploy/base/grafana.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes
