Repository kubevirt/project-infra, pull requests merged in 2025-09, with the labels that each got.

#4338 arm64: Use podman within the unit-test job
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes, ok-to-rehearse, wg/arch-arm

#4353 arm64,kubevirt: move lanes to always run false due to cluster change
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4356 HCO 1.13: Update k8s provider from 1.30 to 1.31
  github/ci/prow-deploy/files/jobs/kubevirt/hyperconverged-cluster-operator/hyperconverged-cluster-operator-presubmits-1.13.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4350 chore: bump go to 1.25
  .golangci.yaml
  Makefile
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-presubmits.yaml
  go.mod
  images/shared-images-controller/Containerfile
  images/shared-images-controller/go.mod
  limiter/limiter_test.go
  robots/cmd/kubevirtci-presubmit-creator/main.go
  robots/cmd/test-report/cmd/dequarantine/execute.go
  robots/cmd/test-report/cmd/dequarantine/execute_test.go
Labels: size/L, approved, lgtm, dco-signoff: yes

#4374 Request 16G RAM for nmstate tests
  github/ci/prow-deploy/files/jobs/nmstate/nmstate/nmstate-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4037 Automate creation of benchmarks data during kubevirt release
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
  robots/cmd/perf-report-creator/README.md
  robots/cmd/perf-report-creator/main.go
  robots/cmd/perf-report-creator/plot.go
  robots/cmd/perf-report-creator/release-graph.sh
  robots/cmd/perf-report-creator/shape.yaml
Labels: size/L, approved, lgtm, dco-signoff: yes, needs-approver-review

#4375 periodic,mirror: Update istioctl versions to mirror to match what has been used recently in kubevirtci
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4376 Generate v1.6 benchmarks data
  robots/cmd/perf-report-creator/shape.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#4371 crio,kubevirtci: automate the cri-o version bumps for the latest kubevirtci provider
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml
  hack/bump-crio-mirror-versions.sh
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4380 chore(require-presubmits): make 1.34 sig jobs required
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits-1.6.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
  robots/pkg/kubevirt/cmd/require/presubmits.go
Labels: size/M, approved, lgtm, dco-signoff: yes

#4391 Disable dry run and create a performance benchmarks PR
  github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-postsubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4398 CAPK: bump golang version to v1.24.7
  github/ci/prow-deploy/files/jobs/kubernetes-sigs/cluster-api-provider-kubevirt/cluster-api-provider-kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4399 feat: enable INVOKE_FUNCTEST_ONCE for flake checks
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4402 fix(kubevirt-tutorial): remove jobs for repo
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-tutorial/kubevirt-tutorial-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-tutorial/kubevirt-tutorial-presubmits.yaml
Labels: size/M, approved, lgtm, dco-signoff: yes

#4388 feat(tide): add invalid-commit-message label to tide query
  github/ci/prow-deploy/kustom/base/configs/current/config/config.yaml
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4406 feat(rehearse): collapse instructions
  external-plugins/rehearse/plugin/handler/handler.go
Labels: size/XS, approved, lgtm, dco-signoff: yes

#4385 Bump compute non-standard lanes to 1.34
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-periodics.yaml
  github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml
Labels: size/S, approved, lgtm, dco-signoff: yes
